events {}

http {
    # --- БЕЗОПАСНОСТЬ: ОСНОВНЫЕ НАСТРОЙКИ ---

    # Скрываем версию nginx в заголовках (было Server: nginx/1.29 -> станет Server: nginx)
    server_tokens off;

    # Защита от Clickjacking (запрещает открывать ваш сайт в iframe на чужих сайтах)
    add_header X-Frame-Options "SAMEORIGIN" always;

    # Защита от MIME-sniffing
    add_header X-Content-Type-Options "nosniff" always;

    # Включаем встроенный в браузер XSS-фильтр
    add_header X-XSS-Protection "1; mode=block" always;

    # HSTS: Говорит браузеру "Запомимни, этот сайт работает ТОЛЬКО по HTTPS" (на 1 год)
    # Включать только если уверены, что SSL работает стабильно!
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # --- SSL НАСТРОЙКИ (Best Practice) ---
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    # Более надежный список шифров
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";

    # --- Основной сайт ---
    server {
        listen 443 ssl;
        server_name bonds-lab.ru;

        client_max_body_size 50M;

        ssl_certificate     /etc/nginx/certs/bonds-lab.crt;
        ssl_certificate_key /etc/nginx/certs/bonds-lab.key;

        # --- БЛОКИРОВКА МУСОРА ОТ БОТОВ ---

        # Запрещаем доступ к скрытым файлам (.env, .git, .idea)
        # Исключение: .well-known (нужно для Let's Encrypt обновлений)
        location ~ /\.(?!well-known) {
            deny all;
        }

        # Блокируем попытки скана старых скриптов (php, asp, cgi)
        location ~* \.(php|pl|py|jsp|asp|sh|cgi)$ {
            return 444; # 444 - специальный код nginx "обрываем соединение без ответа"
        }

        location / {
            proxy_pass         http://bonds-client:3000;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }

        location /_next/image {
            proxy_pass http://bonds-client:3000/_next/image$is_args$args;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }
    }
}
