/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FinancialReportsDto,
  IngestLlmReportRequest,
} from '../models/index';
import {
    FinancialReportsDtoFromJSON,
    FinancialReportsDtoToJSON,
    IngestLlmReportRequestFromJSON,
    IngestLlmReportRequestToJSON,
} from '../models/index';

export interface ApiV1AdminReportsIngestPostRequest {
    ingestLlmReportRequest?: IngestLlmReportRequest;
}

/**
 * 
 */
export class AdminReportApi extends runtime.BaseAPI {

    /**
     */
    async apiV1AdminReportsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FinancialReportsDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/admin/reports`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FinancialReportsDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiV1AdminReportsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FinancialReportsDto> {
        const response = await this.apiV1AdminReportsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1AdminReportsIngestPostRaw(requestParameters: ApiV1AdminReportsIngestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/admin/reports/ingest`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IngestLlmReportRequestToJSON(requestParameters['ingestLlmReportRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1AdminReportsIngestPost(requestParameters: ApiV1AdminReportsIngestPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1AdminReportsIngestPostRaw(requestParameters, initOverrides);
    }

}
