/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AlternativeBondsResponse,
  PortfolioRequest,
  PortfolioResponse,
} from '../models/index';
import {
    AlternativeBondsResponseFromJSON,
    AlternativeBondsResponseToJSON,
    PortfolioRequestFromJSON,
    PortfolioRequestToJSON,
    PortfolioResponseFromJSON,
    PortfolioResponseToJSON,
} from '../models/index';

export interface ApiV1AnalyticsAlternativesIsinGetRequest {
    isin: string;
}

export interface ApiV1AnalyticsPortfolioPostRequest {
    portfolioRequest?: PortfolioRequest;
}

/**
 * 
 */
export class AnalyticsApi extends runtime.BaseAPI {

    /**
     */
    async apiV1AnalyticsAlternativesIsinGetRaw(requestParameters: ApiV1AnalyticsAlternativesIsinGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AlternativeBondsResponse>> {
        if (requestParameters['isin'] == null) {
            throw new runtime.RequiredError(
                'isin',
                'Required parameter "isin" was null or undefined when calling apiV1AnalyticsAlternativesIsinGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/analytics/alternatives/{isin}`.replace(`{${"isin"}}`, encodeURIComponent(String(requestParameters['isin']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AlternativeBondsResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1AnalyticsAlternativesIsinGet(requestParameters: ApiV1AnalyticsAlternativesIsinGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AlternativeBondsResponse> {
        const response = await this.apiV1AnalyticsAlternativesIsinGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1AnalyticsPortfolioPostRaw(requestParameters: ApiV1AnalyticsPortfolioPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortfolioResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/analytics/portfolio`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PortfolioRequestToJSON(requestParameters['portfolioRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortfolioResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1AnalyticsPortfolioPost(requestParameters: ApiV1AnalyticsPortfolioPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortfolioResponse> {
        const response = await this.apiV1AnalyticsPortfolioPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
