/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdminBondUpdateRequest,
  BondListResponse,
  BondRateType,
  CouponBindingDto,
  FinalBondResponse,
  Flag,
  MarketMapResponse,
  UpdateCreditRatingRequest,
} from '../models/index';
import {
    AdminBondUpdateRequestFromJSON,
    AdminBondUpdateRequestToJSON,
    BondListResponseFromJSON,
    BondListResponseToJSON,
    BondRateTypeFromJSON,
    BondRateTypeToJSON,
    CouponBindingDtoFromJSON,
    CouponBindingDtoToJSON,
    FinalBondResponseFromJSON,
    FinalBondResponseToJSON,
    FlagFromJSON,
    FlagToJSON,
    MarketMapResponseFromJSON,
    MarketMapResponseToJSON,
    UpdateCreditRatingRequestFromJSON,
    UpdateCreditRatingRequestToJSON,
} from '../models/index';

export interface ApiV1BondsFavoritesGetRequest {
    page?: number;
    pageSize?: number;
}

export interface ApiV1BondsGetRequest {
    currency?: string;
    nominalCurrency?: string;
    nominalStrict?: number;
    nominalFrom?: number;
    nominalTo?: number;
    priceFrom?: number;
    priceTo?: number;
    couponPrcFrom?: number;
    couponPrcTo?: number;
    couponQuantityPerYear?: number;
    amortizationFlag?: Flag;
    floatingCouponFlag?: Flag;
    marginAbleFlag?: Flag;
    forQualInvestorFlag?: Flag;
    hasEventsFlag?: Flag;
    singleBusinessFlag?: Flag;
    defaultFlag?: Flag;
    technicalDefaultFlag?: Flag;
    availableInTFlag?: Flag;
    availableInAutofollowFlag?: Flag;
    inPortfolioFlag?: Flag;
    portfolioFigis?: Array<string>;
    markedEmitentsFlag?: Flag;
    uniqueEmitentsFlag?: boolean;
    collectionId?: string;
    placementDateFrom?: Date;
    placementDateTo?: Date;
    matureDateFrom?: Date;
    matureDateTo?: Date;
    firstCallDateFrom?: Date;
    firstCallDateTo?: Date;
    firstMtyDateFrom?: Date;
    firstMtyDateTo?: Date;
    nextCouponDateFrom?: Date;
    nextCouponDateTo?: Date;
    creditRatingFrom?: string;
    creditRatingTo?: string;
    netDebtToEbitdaFrom?: number;
    netDebtToEbitdaTo?: number;
    totalDebtToEquityFrom?: number;
    totalDebtToEquityTo?: number;
    totalDebtToAssetsFrom?: number;
    totalDebtToAssetsTo?: number;
    ebitdaToInterestExpenseFrom?: number;
    ebitdaToInterestExpenseTo?: number;
    operatingCashFlowToTotalDebtFrom?: number;
    operatingCashFlowToTotalDebtTo?: number;
    ebitdaMarginFrom?: number;
    ebitdaMarginTo?: number;
    netProfitMarginFrom?: number;
    netProfitMarginTo?: number;
    returnOnAssetsFrom?: number;
    returnOnAssetsTo?: number;
    returnOnInvestmentFrom?: number;
    returnOnInvestmentTo?: number;
    currentRatioFrom?: number;
    currentRatioTo?: number;
    quickRatioFrom?: number;
    quickRatioTo?: number;
    sorts?: string;
    page?: number;
    pageSize?: number;
    yieldFrom?: number;
    yieldTo?: number;
    durationFrom?: number;
    durationTo?: number;
    currentYieldFrom?: number;
    currentYieldTo?: number;
    spreadFrom?: number;
    spreadTo?: number;
    rateType?: BondRateType;
    gSpreadFrom?: number;
    gSpreadTo?: number;
}

export interface ApiV1BondsIdCouponBindingPutRequest {
    id: string;
    couponBindingDto?: CouponBindingDto;
}

export interface ApiV1BondsIdCreditRatingPutRequest {
    id: string;
    updateCreditRatingRequest?: UpdateCreditRatingRequest;
}

export interface ApiV1BondsIdFavoritePostRequest {
    id: string;
}

export interface ApiV1BondsIdGetRequest {
    id: string;
}

export interface ApiV1BondsIsinIsinGetRequest {
    isin: string;
}

export interface ApiV1BondsMarketMapGetRequest {
    currency?: string;
    nominalCurrency?: string;
    nominalStrict?: number;
    nominalFrom?: number;
    nominalTo?: number;
    priceFrom?: number;
    priceTo?: number;
    couponPrcFrom?: number;
    couponPrcTo?: number;
    couponQuantityPerYear?: number;
    amortizationFlag?: Flag;
    floatingCouponFlag?: Flag;
    marginAbleFlag?: Flag;
    forQualInvestorFlag?: Flag;
    hasEventsFlag?: Flag;
    singleBusinessFlag?: Flag;
    defaultFlag?: Flag;
    technicalDefaultFlag?: Flag;
    availableInTFlag?: Flag;
    availableInAutofollowFlag?: Flag;
    inPortfolioFlag?: Flag;
    portfolioFigis?: Array<string>;
    markedEmitentsFlag?: Flag;
    uniqueEmitentsFlag?: boolean;
    collectionId?: string;
    placementDateFrom?: Date;
    placementDateTo?: Date;
    matureDateFrom?: Date;
    matureDateTo?: Date;
    firstCallDateFrom?: Date;
    firstCallDateTo?: Date;
    firstMtyDateFrom?: Date;
    firstMtyDateTo?: Date;
    nextCouponDateFrom?: Date;
    nextCouponDateTo?: Date;
    creditRatingFrom?: string;
    creditRatingTo?: string;
    netDebtToEbitdaFrom?: number;
    netDebtToEbitdaTo?: number;
    totalDebtToEquityFrom?: number;
    totalDebtToEquityTo?: number;
    totalDebtToAssetsFrom?: number;
    totalDebtToAssetsTo?: number;
    ebitdaToInterestExpenseFrom?: number;
    ebitdaToInterestExpenseTo?: number;
    operatingCashFlowToTotalDebtFrom?: number;
    operatingCashFlowToTotalDebtTo?: number;
    ebitdaMarginFrom?: number;
    ebitdaMarginTo?: number;
    netProfitMarginFrom?: number;
    netProfitMarginTo?: number;
    returnOnAssetsFrom?: number;
    returnOnAssetsTo?: number;
    returnOnInvestmentFrom?: number;
    returnOnInvestmentTo?: number;
    currentRatioFrom?: number;
    currentRatioTo?: number;
    quickRatioFrom?: number;
    quickRatioTo?: number;
    sorts?: string;
    page?: number;
    pageSize?: number;
    yieldFrom?: number;
    yieldTo?: number;
    durationFrom?: number;
    durationTo?: number;
    currentYieldFrom?: number;
    currentYieldTo?: number;
    spreadFrom?: number;
    spreadTo?: number;
    rateType?: BondRateType;
    gSpreadFrom?: number;
    gSpreadTo?: number;
}

export interface ApiV1BondsUpdateIdPutRequest {
    id: string;
    adminBondUpdateRequest?: AdminBondUpdateRequest;
}

/**
 * 
 */
export class BondApi extends runtime.BaseAPI {

    /**
     */
    async apiV1BondsFavoritesGetRaw(requestParameters: ApiV1BondsFavoritesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/bonds/favorites`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1BondsFavoritesGet(requestParameters: ApiV1BondsFavoritesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1BondsFavoritesGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiV1BondsFloaterBindingsPutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/bonds/floater-bindings`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1BondsFloaterBindingsPut(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1BondsFloaterBindingsPutRaw(initOverrides);
    }

    /**
     */
    async apiV1BondsGetRaw(requestParameters: ApiV1BondsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BondListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['currency'] != null) {
            queryParameters['Currency'] = requestParameters['currency'];
        }

        if (requestParameters['nominalCurrency'] != null) {
            queryParameters['NominalCurrency'] = requestParameters['nominalCurrency'];
        }

        if (requestParameters['nominalStrict'] != null) {
            queryParameters['NominalStrict'] = requestParameters['nominalStrict'];
        }

        if (requestParameters['nominalFrom'] != null) {
            queryParameters['NominalFrom'] = requestParameters['nominalFrom'];
        }

        if (requestParameters['nominalTo'] != null) {
            queryParameters['NominalTo'] = requestParameters['nominalTo'];
        }

        if (requestParameters['priceFrom'] != null) {
            queryParameters['PriceFrom'] = requestParameters['priceFrom'];
        }

        if (requestParameters['priceTo'] != null) {
            queryParameters['PriceTo'] = requestParameters['priceTo'];
        }

        if (requestParameters['couponPrcFrom'] != null) {
            queryParameters['CouponPrcFrom'] = requestParameters['couponPrcFrom'];
        }

        if (requestParameters['couponPrcTo'] != null) {
            queryParameters['CouponPrcTo'] = requestParameters['couponPrcTo'];
        }

        if (requestParameters['couponQuantityPerYear'] != null) {
            queryParameters['CouponQuantityPerYear'] = requestParameters['couponQuantityPerYear'];
        }

        if (requestParameters['amortizationFlag'] != null) {
            queryParameters['AmortizationFlag'] = requestParameters['amortizationFlag'];
        }

        if (requestParameters['floatingCouponFlag'] != null) {
            queryParameters['FloatingCouponFlag'] = requestParameters['floatingCouponFlag'];
        }

        if (requestParameters['marginAbleFlag'] != null) {
            queryParameters['MarginAbleFlag'] = requestParameters['marginAbleFlag'];
        }

        if (requestParameters['forQualInvestorFlag'] != null) {
            queryParameters['ForQualInvestorFlag'] = requestParameters['forQualInvestorFlag'];
        }

        if (requestParameters['hasEventsFlag'] != null) {
            queryParameters['HasEventsFlag'] = requestParameters['hasEventsFlag'];
        }

        if (requestParameters['singleBusinessFlag'] != null) {
            queryParameters['SingleBusinessFlag'] = requestParameters['singleBusinessFlag'];
        }

        if (requestParameters['defaultFlag'] != null) {
            queryParameters['DefaultFlag'] = requestParameters['defaultFlag'];
        }

        if (requestParameters['technicalDefaultFlag'] != null) {
            queryParameters['TechnicalDefaultFlag'] = requestParameters['technicalDefaultFlag'];
        }

        if (requestParameters['availableInTFlag'] != null) {
            queryParameters['AvailableInTFlag'] = requestParameters['availableInTFlag'];
        }

        if (requestParameters['availableInAutofollowFlag'] != null) {
            queryParameters['AvailableInAutofollowFlag'] = requestParameters['availableInAutofollowFlag'];
        }

        if (requestParameters['inPortfolioFlag'] != null) {
            queryParameters['InPortfolioFlag'] = requestParameters['inPortfolioFlag'];
        }

        if (requestParameters['portfolioFigis'] != null) {
            queryParameters['PortfolioFigis'] = requestParameters['portfolioFigis'];
        }

        if (requestParameters['markedEmitentsFlag'] != null) {
            queryParameters['MarkedEmitentsFlag'] = requestParameters['markedEmitentsFlag'];
        }

        if (requestParameters['uniqueEmitentsFlag'] != null) {
            queryParameters['UniqueEmitentsFlag'] = requestParameters['uniqueEmitentsFlag'];
        }

        if (requestParameters['collectionId'] != null) {
            queryParameters['CollectionId'] = requestParameters['collectionId'];
        }

        if (requestParameters['placementDateFrom'] != null) {
            queryParameters['PlacementDateFrom'] = (requestParameters['placementDateFrom'] as any).toISOString();
        }

        if (requestParameters['placementDateTo'] != null) {
            queryParameters['PlacementDateTo'] = (requestParameters['placementDateTo'] as any).toISOString();
        }

        if (requestParameters['matureDateFrom'] != null) {
            queryParameters['MatureDateFrom'] = (requestParameters['matureDateFrom'] as any).toISOString();
        }

        if (requestParameters['matureDateTo'] != null) {
            queryParameters['MatureDateTo'] = (requestParameters['matureDateTo'] as any).toISOString();
        }

        if (requestParameters['firstCallDateFrom'] != null) {
            queryParameters['FirstCallDateFrom'] = (requestParameters['firstCallDateFrom'] as any).toISOString();
        }

        if (requestParameters['firstCallDateTo'] != null) {
            queryParameters['FirstCallDateTo'] = (requestParameters['firstCallDateTo'] as any).toISOString();
        }

        if (requestParameters['firstMtyDateFrom'] != null) {
            queryParameters['FirstMtyDateFrom'] = (requestParameters['firstMtyDateFrom'] as any).toISOString();
        }

        if (requestParameters['firstMtyDateTo'] != null) {
            queryParameters['FirstMtyDateTo'] = (requestParameters['firstMtyDateTo'] as any).toISOString();
        }

        if (requestParameters['nextCouponDateFrom'] != null) {
            queryParameters['NextCouponDateFrom'] = (requestParameters['nextCouponDateFrom'] as any).toISOString();
        }

        if (requestParameters['nextCouponDateTo'] != null) {
            queryParameters['NextCouponDateTo'] = (requestParameters['nextCouponDateTo'] as any).toISOString();
        }

        if (requestParameters['creditRatingFrom'] != null) {
            queryParameters['CreditRatingFrom'] = requestParameters['creditRatingFrom'];
        }

        if (requestParameters['creditRatingTo'] != null) {
            queryParameters['CreditRatingTo'] = requestParameters['creditRatingTo'];
        }

        if (requestParameters['netDebtToEbitdaFrom'] != null) {
            queryParameters['NetDebtToEbitdaFrom'] = requestParameters['netDebtToEbitdaFrom'];
        }

        if (requestParameters['netDebtToEbitdaTo'] != null) {
            queryParameters['NetDebtToEbitdaTo'] = requestParameters['netDebtToEbitdaTo'];
        }

        if (requestParameters['totalDebtToEquityFrom'] != null) {
            queryParameters['TotalDebtToEquityFrom'] = requestParameters['totalDebtToEquityFrom'];
        }

        if (requestParameters['totalDebtToEquityTo'] != null) {
            queryParameters['TotalDebtToEquityTo'] = requestParameters['totalDebtToEquityTo'];
        }

        if (requestParameters['totalDebtToAssetsFrom'] != null) {
            queryParameters['TotalDebtToAssetsFrom'] = requestParameters['totalDebtToAssetsFrom'];
        }

        if (requestParameters['totalDebtToAssetsTo'] != null) {
            queryParameters['TotalDebtToAssetsTo'] = requestParameters['totalDebtToAssetsTo'];
        }

        if (requestParameters['ebitdaToInterestExpenseFrom'] != null) {
            queryParameters['EbitdaToInterestExpenseFrom'] = requestParameters['ebitdaToInterestExpenseFrom'];
        }

        if (requestParameters['ebitdaToInterestExpenseTo'] != null) {
            queryParameters['EbitdaToInterestExpenseTo'] = requestParameters['ebitdaToInterestExpenseTo'];
        }

        if (requestParameters['operatingCashFlowToTotalDebtFrom'] != null) {
            queryParameters['OperatingCashFlowToTotalDebtFrom'] = requestParameters['operatingCashFlowToTotalDebtFrom'];
        }

        if (requestParameters['operatingCashFlowToTotalDebtTo'] != null) {
            queryParameters['OperatingCashFlowToTotalDebtTo'] = requestParameters['operatingCashFlowToTotalDebtTo'];
        }

        if (requestParameters['ebitdaMarginFrom'] != null) {
            queryParameters['EbitdaMarginFrom'] = requestParameters['ebitdaMarginFrom'];
        }

        if (requestParameters['ebitdaMarginTo'] != null) {
            queryParameters['EbitdaMarginTo'] = requestParameters['ebitdaMarginTo'];
        }

        if (requestParameters['netProfitMarginFrom'] != null) {
            queryParameters['NetProfitMarginFrom'] = requestParameters['netProfitMarginFrom'];
        }

        if (requestParameters['netProfitMarginTo'] != null) {
            queryParameters['NetProfitMarginTo'] = requestParameters['netProfitMarginTo'];
        }

        if (requestParameters['returnOnAssetsFrom'] != null) {
            queryParameters['ReturnOnAssetsFrom'] = requestParameters['returnOnAssetsFrom'];
        }

        if (requestParameters['returnOnAssetsTo'] != null) {
            queryParameters['ReturnOnAssetsTo'] = requestParameters['returnOnAssetsTo'];
        }

        if (requestParameters['returnOnInvestmentFrom'] != null) {
            queryParameters['ReturnOnInvestmentFrom'] = requestParameters['returnOnInvestmentFrom'];
        }

        if (requestParameters['returnOnInvestmentTo'] != null) {
            queryParameters['ReturnOnInvestmentTo'] = requestParameters['returnOnInvestmentTo'];
        }

        if (requestParameters['currentRatioFrom'] != null) {
            queryParameters['CurrentRatioFrom'] = requestParameters['currentRatioFrom'];
        }

        if (requestParameters['currentRatioTo'] != null) {
            queryParameters['CurrentRatioTo'] = requestParameters['currentRatioTo'];
        }

        if (requestParameters['quickRatioFrom'] != null) {
            queryParameters['QuickRatioFrom'] = requestParameters['quickRatioFrom'];
        }

        if (requestParameters['quickRatioTo'] != null) {
            queryParameters['QuickRatioTo'] = requestParameters['quickRatioTo'];
        }

        if (requestParameters['sorts'] != null) {
            queryParameters['Sorts'] = requestParameters['sorts'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['yieldFrom'] != null) {
            queryParameters['YieldFrom'] = requestParameters['yieldFrom'];
        }

        if (requestParameters['yieldTo'] != null) {
            queryParameters['YieldTo'] = requestParameters['yieldTo'];
        }

        if (requestParameters['durationFrom'] != null) {
            queryParameters['DurationFrom'] = requestParameters['durationFrom'];
        }

        if (requestParameters['durationTo'] != null) {
            queryParameters['DurationTo'] = requestParameters['durationTo'];
        }

        if (requestParameters['currentYieldFrom'] != null) {
            queryParameters['CurrentYieldFrom'] = requestParameters['currentYieldFrom'];
        }

        if (requestParameters['currentYieldTo'] != null) {
            queryParameters['CurrentYieldTo'] = requestParameters['currentYieldTo'];
        }

        if (requestParameters['spreadFrom'] != null) {
            queryParameters['SpreadFrom'] = requestParameters['spreadFrom'];
        }

        if (requestParameters['spreadTo'] != null) {
            queryParameters['SpreadTo'] = requestParameters['spreadTo'];
        }

        if (requestParameters['rateType'] != null) {
            queryParameters['RateType'] = requestParameters['rateType'];
        }

        if (requestParameters['gSpreadFrom'] != null) {
            queryParameters['GSpreadFrom'] = requestParameters['gSpreadFrom'];
        }

        if (requestParameters['gSpreadTo'] != null) {
            queryParameters['GSpreadTo'] = requestParameters['gSpreadTo'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/bonds`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BondListResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1BondsGet(requestParameters: ApiV1BondsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BondListResponse> {
        const response = await this.apiV1BondsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1BondsIdCouponBindingPutRaw(requestParameters: ApiV1BondsIdCouponBindingPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1BondsIdCouponBindingPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/bonds/{id}/coupon-binding`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CouponBindingDtoToJSON(requestParameters['couponBindingDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1BondsIdCouponBindingPut(requestParameters: ApiV1BondsIdCouponBindingPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1BondsIdCouponBindingPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiV1BondsIdCreditRatingPutRaw(requestParameters: ApiV1BondsIdCreditRatingPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1BondsIdCreditRatingPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/bonds/{id}/credit-rating`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCreditRatingRequestToJSON(requestParameters['updateCreditRatingRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1BondsIdCreditRatingPut(requestParameters: ApiV1BondsIdCreditRatingPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1BondsIdCreditRatingPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiV1BondsIdFavoritePostRaw(requestParameters: ApiV1BondsIdFavoritePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1BondsIdFavoritePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/bonds/{id}/favorite`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1BondsIdFavoritePost(requestParameters: ApiV1BondsIdFavoritePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1BondsIdFavoritePostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiV1BondsIdGetRaw(requestParameters: ApiV1BondsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FinalBondResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1BondsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/bonds/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FinalBondResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1BondsIdGet(requestParameters: ApiV1BondsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FinalBondResponse> {
        const response = await this.apiV1BondsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1BondsIsinIsinGetRaw(requestParameters: ApiV1BondsIsinIsinGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FinalBondResponse>> {
        if (requestParameters['isin'] == null) {
            throw new runtime.RequiredError(
                'isin',
                'Required parameter "isin" was null or undefined when calling apiV1BondsIsinIsinGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/bonds/isin/{isin}`.replace(`{${"isin"}}`, encodeURIComponent(String(requestParameters['isin']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FinalBondResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1BondsIsinIsinGet(requestParameters: ApiV1BondsIsinIsinGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FinalBondResponse> {
        const response = await this.apiV1BondsIsinIsinGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1BondsMarketMapGetRaw(requestParameters: ApiV1BondsMarketMapGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MarketMapResponse>> {
        const queryParameters: any = {};

        if (requestParameters['currency'] != null) {
            queryParameters['Currency'] = requestParameters['currency'];
        }

        if (requestParameters['nominalCurrency'] != null) {
            queryParameters['NominalCurrency'] = requestParameters['nominalCurrency'];
        }

        if (requestParameters['nominalStrict'] != null) {
            queryParameters['NominalStrict'] = requestParameters['nominalStrict'];
        }

        if (requestParameters['nominalFrom'] != null) {
            queryParameters['NominalFrom'] = requestParameters['nominalFrom'];
        }

        if (requestParameters['nominalTo'] != null) {
            queryParameters['NominalTo'] = requestParameters['nominalTo'];
        }

        if (requestParameters['priceFrom'] != null) {
            queryParameters['PriceFrom'] = requestParameters['priceFrom'];
        }

        if (requestParameters['priceTo'] != null) {
            queryParameters['PriceTo'] = requestParameters['priceTo'];
        }

        if (requestParameters['couponPrcFrom'] != null) {
            queryParameters['CouponPrcFrom'] = requestParameters['couponPrcFrom'];
        }

        if (requestParameters['couponPrcTo'] != null) {
            queryParameters['CouponPrcTo'] = requestParameters['couponPrcTo'];
        }

        if (requestParameters['couponQuantityPerYear'] != null) {
            queryParameters['CouponQuantityPerYear'] = requestParameters['couponQuantityPerYear'];
        }

        if (requestParameters['amortizationFlag'] != null) {
            queryParameters['AmortizationFlag'] = requestParameters['amortizationFlag'];
        }

        if (requestParameters['floatingCouponFlag'] != null) {
            queryParameters['FloatingCouponFlag'] = requestParameters['floatingCouponFlag'];
        }

        if (requestParameters['marginAbleFlag'] != null) {
            queryParameters['MarginAbleFlag'] = requestParameters['marginAbleFlag'];
        }

        if (requestParameters['forQualInvestorFlag'] != null) {
            queryParameters['ForQualInvestorFlag'] = requestParameters['forQualInvestorFlag'];
        }

        if (requestParameters['hasEventsFlag'] != null) {
            queryParameters['HasEventsFlag'] = requestParameters['hasEventsFlag'];
        }

        if (requestParameters['singleBusinessFlag'] != null) {
            queryParameters['SingleBusinessFlag'] = requestParameters['singleBusinessFlag'];
        }

        if (requestParameters['defaultFlag'] != null) {
            queryParameters['DefaultFlag'] = requestParameters['defaultFlag'];
        }

        if (requestParameters['technicalDefaultFlag'] != null) {
            queryParameters['TechnicalDefaultFlag'] = requestParameters['technicalDefaultFlag'];
        }

        if (requestParameters['availableInTFlag'] != null) {
            queryParameters['AvailableInTFlag'] = requestParameters['availableInTFlag'];
        }

        if (requestParameters['availableInAutofollowFlag'] != null) {
            queryParameters['AvailableInAutofollowFlag'] = requestParameters['availableInAutofollowFlag'];
        }

        if (requestParameters['inPortfolioFlag'] != null) {
            queryParameters['InPortfolioFlag'] = requestParameters['inPortfolioFlag'];
        }

        if (requestParameters['portfolioFigis'] != null) {
            queryParameters['PortfolioFigis'] = requestParameters['portfolioFigis'];
        }

        if (requestParameters['markedEmitentsFlag'] != null) {
            queryParameters['MarkedEmitentsFlag'] = requestParameters['markedEmitentsFlag'];
        }

        if (requestParameters['uniqueEmitentsFlag'] != null) {
            queryParameters['UniqueEmitentsFlag'] = requestParameters['uniqueEmitentsFlag'];
        }

        if (requestParameters['collectionId'] != null) {
            queryParameters['CollectionId'] = requestParameters['collectionId'];
        }

        if (requestParameters['placementDateFrom'] != null) {
            queryParameters['PlacementDateFrom'] = (requestParameters['placementDateFrom'] as any).toISOString();
        }

        if (requestParameters['placementDateTo'] != null) {
            queryParameters['PlacementDateTo'] = (requestParameters['placementDateTo'] as any).toISOString();
        }

        if (requestParameters['matureDateFrom'] != null) {
            queryParameters['MatureDateFrom'] = (requestParameters['matureDateFrom'] as any).toISOString();
        }

        if (requestParameters['matureDateTo'] != null) {
            queryParameters['MatureDateTo'] = (requestParameters['matureDateTo'] as any).toISOString();
        }

        if (requestParameters['firstCallDateFrom'] != null) {
            queryParameters['FirstCallDateFrom'] = (requestParameters['firstCallDateFrom'] as any).toISOString();
        }

        if (requestParameters['firstCallDateTo'] != null) {
            queryParameters['FirstCallDateTo'] = (requestParameters['firstCallDateTo'] as any).toISOString();
        }

        if (requestParameters['firstMtyDateFrom'] != null) {
            queryParameters['FirstMtyDateFrom'] = (requestParameters['firstMtyDateFrom'] as any).toISOString();
        }

        if (requestParameters['firstMtyDateTo'] != null) {
            queryParameters['FirstMtyDateTo'] = (requestParameters['firstMtyDateTo'] as any).toISOString();
        }

        if (requestParameters['nextCouponDateFrom'] != null) {
            queryParameters['NextCouponDateFrom'] = (requestParameters['nextCouponDateFrom'] as any).toISOString();
        }

        if (requestParameters['nextCouponDateTo'] != null) {
            queryParameters['NextCouponDateTo'] = (requestParameters['nextCouponDateTo'] as any).toISOString();
        }

        if (requestParameters['creditRatingFrom'] != null) {
            queryParameters['CreditRatingFrom'] = requestParameters['creditRatingFrom'];
        }

        if (requestParameters['creditRatingTo'] != null) {
            queryParameters['CreditRatingTo'] = requestParameters['creditRatingTo'];
        }

        if (requestParameters['netDebtToEbitdaFrom'] != null) {
            queryParameters['NetDebtToEbitdaFrom'] = requestParameters['netDebtToEbitdaFrom'];
        }

        if (requestParameters['netDebtToEbitdaTo'] != null) {
            queryParameters['NetDebtToEbitdaTo'] = requestParameters['netDebtToEbitdaTo'];
        }

        if (requestParameters['totalDebtToEquityFrom'] != null) {
            queryParameters['TotalDebtToEquityFrom'] = requestParameters['totalDebtToEquityFrom'];
        }

        if (requestParameters['totalDebtToEquityTo'] != null) {
            queryParameters['TotalDebtToEquityTo'] = requestParameters['totalDebtToEquityTo'];
        }

        if (requestParameters['totalDebtToAssetsFrom'] != null) {
            queryParameters['TotalDebtToAssetsFrom'] = requestParameters['totalDebtToAssetsFrom'];
        }

        if (requestParameters['totalDebtToAssetsTo'] != null) {
            queryParameters['TotalDebtToAssetsTo'] = requestParameters['totalDebtToAssetsTo'];
        }

        if (requestParameters['ebitdaToInterestExpenseFrom'] != null) {
            queryParameters['EbitdaToInterestExpenseFrom'] = requestParameters['ebitdaToInterestExpenseFrom'];
        }

        if (requestParameters['ebitdaToInterestExpenseTo'] != null) {
            queryParameters['EbitdaToInterestExpenseTo'] = requestParameters['ebitdaToInterestExpenseTo'];
        }

        if (requestParameters['operatingCashFlowToTotalDebtFrom'] != null) {
            queryParameters['OperatingCashFlowToTotalDebtFrom'] = requestParameters['operatingCashFlowToTotalDebtFrom'];
        }

        if (requestParameters['operatingCashFlowToTotalDebtTo'] != null) {
            queryParameters['OperatingCashFlowToTotalDebtTo'] = requestParameters['operatingCashFlowToTotalDebtTo'];
        }

        if (requestParameters['ebitdaMarginFrom'] != null) {
            queryParameters['EbitdaMarginFrom'] = requestParameters['ebitdaMarginFrom'];
        }

        if (requestParameters['ebitdaMarginTo'] != null) {
            queryParameters['EbitdaMarginTo'] = requestParameters['ebitdaMarginTo'];
        }

        if (requestParameters['netProfitMarginFrom'] != null) {
            queryParameters['NetProfitMarginFrom'] = requestParameters['netProfitMarginFrom'];
        }

        if (requestParameters['netProfitMarginTo'] != null) {
            queryParameters['NetProfitMarginTo'] = requestParameters['netProfitMarginTo'];
        }

        if (requestParameters['returnOnAssetsFrom'] != null) {
            queryParameters['ReturnOnAssetsFrom'] = requestParameters['returnOnAssetsFrom'];
        }

        if (requestParameters['returnOnAssetsTo'] != null) {
            queryParameters['ReturnOnAssetsTo'] = requestParameters['returnOnAssetsTo'];
        }

        if (requestParameters['returnOnInvestmentFrom'] != null) {
            queryParameters['ReturnOnInvestmentFrom'] = requestParameters['returnOnInvestmentFrom'];
        }

        if (requestParameters['returnOnInvestmentTo'] != null) {
            queryParameters['ReturnOnInvestmentTo'] = requestParameters['returnOnInvestmentTo'];
        }

        if (requestParameters['currentRatioFrom'] != null) {
            queryParameters['CurrentRatioFrom'] = requestParameters['currentRatioFrom'];
        }

        if (requestParameters['currentRatioTo'] != null) {
            queryParameters['CurrentRatioTo'] = requestParameters['currentRatioTo'];
        }

        if (requestParameters['quickRatioFrom'] != null) {
            queryParameters['QuickRatioFrom'] = requestParameters['quickRatioFrom'];
        }

        if (requestParameters['quickRatioTo'] != null) {
            queryParameters['QuickRatioTo'] = requestParameters['quickRatioTo'];
        }

        if (requestParameters['sorts'] != null) {
            queryParameters['Sorts'] = requestParameters['sorts'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['yieldFrom'] != null) {
            queryParameters['YieldFrom'] = requestParameters['yieldFrom'];
        }

        if (requestParameters['yieldTo'] != null) {
            queryParameters['YieldTo'] = requestParameters['yieldTo'];
        }

        if (requestParameters['durationFrom'] != null) {
            queryParameters['DurationFrom'] = requestParameters['durationFrom'];
        }

        if (requestParameters['durationTo'] != null) {
            queryParameters['DurationTo'] = requestParameters['durationTo'];
        }

        if (requestParameters['currentYieldFrom'] != null) {
            queryParameters['CurrentYieldFrom'] = requestParameters['currentYieldFrom'];
        }

        if (requestParameters['currentYieldTo'] != null) {
            queryParameters['CurrentYieldTo'] = requestParameters['currentYieldTo'];
        }

        if (requestParameters['spreadFrom'] != null) {
            queryParameters['SpreadFrom'] = requestParameters['spreadFrom'];
        }

        if (requestParameters['spreadTo'] != null) {
            queryParameters['SpreadTo'] = requestParameters['spreadTo'];
        }

        if (requestParameters['rateType'] != null) {
            queryParameters['RateType'] = requestParameters['rateType'];
        }

        if (requestParameters['gSpreadFrom'] != null) {
            queryParameters['GSpreadFrom'] = requestParameters['gSpreadFrom'];
        }

        if (requestParameters['gSpreadTo'] != null) {
            queryParameters['GSpreadTo'] = requestParameters['gSpreadTo'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/bonds/market-map`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MarketMapResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1BondsMarketMapGet(requestParameters: ApiV1BondsMarketMapGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MarketMapResponse> {
        const response = await this.apiV1BondsMarketMapGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1BondsPricesPutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/bonds/prices`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1BondsPricesPut(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1BondsPricesPutRaw(initOverrides);
    }

    /**
     */
    async apiV1BondsPutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/bonds`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1BondsPut(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1BondsPutRaw(initOverrides);
    }

    /**
     */
    async apiV1BondsRatingsPutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/bonds/ratings`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1BondsRatingsPut(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1BondsRatingsPutRaw(initOverrides);
    }

    /**
     */
    async apiV1BondsUpdateIdPutRaw(requestParameters: ApiV1BondsUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1BondsUpdateIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/bonds/update/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AdminBondUpdateRequestToJSON(requestParameters['adminBondUpdateRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1BondsUpdateIdPut(requestParameters: ApiV1BondsUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1BondsUpdateIdPutRaw(requestParameters, initOverrides);
    }

}
