/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BrandBusinessResponse,
  BrandReportLinksDto,
  BrandUpdateRequest,
  MessageResponseDto,
  PagedBrandsResponseDto,
  SimplifiedBrandsListResponse,
  UpdateReportStatusRequest,
} from '../models/index';
import {
    BrandBusinessResponseFromJSON,
    BrandBusinessResponseToJSON,
    BrandReportLinksDtoFromJSON,
    BrandReportLinksDtoToJSON,
    BrandUpdateRequestFromJSON,
    BrandUpdateRequestToJSON,
    MessageResponseDtoFromJSON,
    MessageResponseDtoToJSON,
    PagedBrandsResponseDtoFromJSON,
    PagedBrandsResponseDtoToJSON,
    SimplifiedBrandsListResponseFromJSON,
    SimplifiedBrandsListResponseToJSON,
    UpdateReportStatusRequestFromJSON,
    UpdateReportStatusRequestToJSON,
} from '../models/index';

export interface ApiV1BrandsGetRequest {
    isTracked?: boolean;
}

export interface ApiV1BrandsIdGetRequest {
    id: string;
}

export interface ApiV1BrandsIdPutRequest {
    id: string;
    brandUpdateRequest?: BrandUpdateRequest;
}

export interface ApiV1BrandsIdReportStatusPutRequest {
    id: string;
    updateReportStatusRequest?: UpdateReportStatusRequest;
}

export interface ApiV1BrandsIdSyncReportsPostRequest {
    id: string;
}

export interface ApiV1BrandsListGetRequest {
    page?: number;
    pageSize?: number;
}

/**
 * 
 */
export class BrandApi extends runtime.BaseAPI {

    /**
     */
    async apiV1BrandsGetRaw(requestParameters: ApiV1BrandsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimplifiedBrandsListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['isTracked'] != null) {
            queryParameters['isTracked'] = requestParameters['isTracked'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/brands`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimplifiedBrandsListResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1BrandsGet(requestParameters: ApiV1BrandsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimplifiedBrandsListResponse> {
        const response = await this.apiV1BrandsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1BrandsIdGetRaw(requestParameters: ApiV1BrandsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BrandBusinessResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1BrandsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/brands/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BrandBusinessResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1BrandsIdGet(requestParameters: ApiV1BrandsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BrandBusinessResponse> {
        const response = await this.apiV1BrandsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1BrandsIdPutRaw(requestParameters: ApiV1BrandsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BrandBusinessResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1BrandsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/brands/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BrandUpdateRequestToJSON(requestParameters['brandUpdateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BrandBusinessResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1BrandsIdPut(requestParameters: ApiV1BrandsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BrandBusinessResponse> {
        const response = await this.apiV1BrandsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1BrandsIdReportStatusPutRaw(requestParameters: ApiV1BrandsIdReportStatusPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1BrandsIdReportStatusPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/brands/{id}/report-status`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateReportStatusRequestToJSON(requestParameters['updateReportStatusRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1BrandsIdReportStatusPut(requestParameters: ApiV1BrandsIdReportStatusPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1BrandsIdReportStatusPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiV1BrandsIdSyncReportsPostRaw(requestParameters: ApiV1BrandsIdSyncReportsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponseDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1BrandsIdSyncReportsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/brands/{id}/sync-reports`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiV1BrandsIdSyncReportsPost(requestParameters: ApiV1BrandsIdSyncReportsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponseDto> {
        const response = await this.apiV1BrandsIdSyncReportsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1BrandsListGetRaw(requestParameters: ApiV1BrandsListGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedBrandsResponseDto>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/brands/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedBrandsResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiV1BrandsListGet(requestParameters: ApiV1BrandsListGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedBrandsResponseDto> {
        const response = await this.apiV1BrandsListGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1BrandsReportLinksGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BrandReportLinksDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/brands/report-links`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BrandReportLinksDtoFromJSON));
    }

    /**
     */
    async apiV1BrandsReportLinksGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BrandReportLinksDto>> {
        const response = await this.apiV1BrandsReportLinksGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1BrandsSyncAllReportsDownloadsPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/brands/sync-all-reports-downloads`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiV1BrandsSyncAllReportsDownloadsPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponseDto> {
        const response = await this.apiV1BrandsSyncAllReportsDownloadsPostRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1BrandsUpdateReportLinksPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/brands/update-report-links`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiV1BrandsUpdateReportLinksPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponseDto> {
        const response = await this.apiV1BrandsUpdateReportLinksPostRaw(initOverrides);
        return await response.value();
    }

}
