/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  JobPagedResponse,
  JobReviewResult,
  ReviewJobRequest,
} from '../models/index';
import {
    JobPagedResponseFromJSON,
    JobPagedResponseToJSON,
    JobReviewResultFromJSON,
    JobReviewResultToJSON,
    ReviewJobRequestFromJSON,
    ReviewJobRequestToJSON,
} from '../models/index';

export interface ApiV1JobsGetRequest {
    page?: number;
    pageSize?: number;
}

export interface ApiV1JobsIdReviewPostRequest {
    id: string;
    reviewJobRequest?: ReviewJobRequest;
}

export interface ApiV1JobsMyGetRequest {
    page?: number;
    pageSize?: number;
}

export interface ApiV1JobsUploadPostRequest {
    jobName?: string;
    file?: Blob;
    docType?: string;
    brandId?: string;
}

/**
 * 
 */
export class JobApi extends runtime.BaseAPI {

    /**
     */
    async apiV1JobsGetRaw(requestParameters: ApiV1JobsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobPagedResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/jobs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobPagedResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1JobsGet(requestParameters: ApiV1JobsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobPagedResponse> {
        const response = await this.apiV1JobsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1JobsIdReviewPostRaw(requestParameters: ApiV1JobsIdReviewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobReviewResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1JobsIdReviewPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/jobs/{id}/review`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReviewJobRequestToJSON(requestParameters['reviewJobRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobReviewResultFromJSON(jsonValue));
    }

    /**
     */
    async apiV1JobsIdReviewPost(requestParameters: ApiV1JobsIdReviewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobReviewResult> {
        const response = await this.apiV1JobsIdReviewPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1JobsMyGetRaw(requestParameters: ApiV1JobsMyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobPagedResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/jobs/my`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobPagedResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1JobsMyGet(requestParameters: ApiV1JobsMyGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobPagedResponse> {
        const response = await this.apiV1JobsMyGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1JobsUploadPostRaw(requestParameters: ApiV1JobsUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['jobName'] != null) {
            formParams.append('JobName', requestParameters['jobName'] as any);
        }

        if (requestParameters['file'] != null) {
            formParams.append('File', requestParameters['file'] as any);
        }

        if (requestParameters['docType'] != null) {
            formParams.append('DocType', requestParameters['docType'] as any);
        }

        if (requestParameters['brandId'] != null) {
            formParams.append('BrandId', requestParameters['brandId'] as any);
        }

        const response = await this.request({
            path: `/api/v1/jobs/upload`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1JobsUploadPost(requestParameters: ApiV1JobsUploadPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1JobsUploadPostRaw(requestParameters, initOverrides);
    }

}
