/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreatePaymentRequest,
  PaySavedCardRequest,
  PayWoodenRequest,
  PaymentMethodResponse,
  PaymentResponse,
} from '../models/index';
import {
    CreatePaymentRequestFromJSON,
    CreatePaymentRequestToJSON,
    PaySavedCardRequestFromJSON,
    PaySavedCardRequestToJSON,
    PayWoodenRequestFromJSON,
    PayWoodenRequestToJSON,
    PaymentMethodResponseFromJSON,
    PaymentMethodResponseToJSON,
    PaymentResponseFromJSON,
    PaymentResponseToJSON,
} from '../models/index';

export interface ApiV1PaymentsCreatePostRequest {
    createPaymentRequest?: CreatePaymentRequest;
}

export interface ApiV1PaymentsMethodsIdDeleteRequest {
    id: string;
}

export interface ApiV1PaymentsMethodsIdMainPutRequest {
    id: string;
}

export interface ApiV1PaymentsPayWithSavedCardPostRequest {
    paySavedCardRequest?: PaySavedCardRequest;
}

export interface ApiV1PaymentsPayWithWoodenPostRequest {
    payWoodenRequest?: PayWoodenRequest;
}

/**
 * 
 */
export class PaymentApi extends runtime.BaseAPI {

    /**
     */
    async apiV1PaymentsCancelAutoRenewalPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/payments/cancel-auto-renewal`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1PaymentsCancelAutoRenewalPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1PaymentsCancelAutoRenewalPostRaw(initOverrides);
    }

    /**
     */
    async apiV1PaymentsCreatePostRaw(requestParameters: ApiV1PaymentsCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/payments/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePaymentRequestToJSON(requestParameters['createPaymentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1PaymentsCreatePost(requestParameters: ApiV1PaymentsCreatePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentResponse> {
        const response = await this.apiV1PaymentsCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1PaymentsHistoryGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/payments/history`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1PaymentsHistoryGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1PaymentsHistoryGetRaw(initOverrides);
    }

    /**
     */
    async apiV1PaymentsMethodsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PaymentMethodResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/payments/methods`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PaymentMethodResponseFromJSON));
    }

    /**
     */
    async apiV1PaymentsMethodsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PaymentMethodResponse>> {
        const response = await this.apiV1PaymentsMethodsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1PaymentsMethodsIdDeleteRaw(requestParameters: ApiV1PaymentsMethodsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1PaymentsMethodsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/payments/methods/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1PaymentsMethodsIdDelete(requestParameters: ApiV1PaymentsMethodsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1PaymentsMethodsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiV1PaymentsMethodsIdMainPutRaw(requestParameters: ApiV1PaymentsMethodsIdMainPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1PaymentsMethodsIdMainPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/payments/methods/{id}/main`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1PaymentsMethodsIdMainPut(requestParameters: ApiV1PaymentsMethodsIdMainPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1PaymentsMethodsIdMainPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiV1PaymentsPayWithSavedCardPostRaw(requestParameters: ApiV1PaymentsPayWithSavedCardPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/payments/pay-with-saved-card`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PaySavedCardRequestToJSON(requestParameters['paySavedCardRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1PaymentsPayWithSavedCardPost(requestParameters: ApiV1PaymentsPayWithSavedCardPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentResponse> {
        const response = await this.apiV1PaymentsPayWithSavedCardPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1PaymentsPayWithWoodenPostRaw(requestParameters: ApiV1PaymentsPayWithWoodenPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/payments/pay-with-wooden`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PayWoodenRequestToJSON(requestParameters['payWoodenRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1PaymentsPayWithWoodenPost(requestParameters: ApiV1PaymentsPayWithWoodenPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1PaymentsPayWithWoodenPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiV1PaymentsProcessRenewalsPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/payments/process-renewals`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1PaymentsProcessRenewalsPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1PaymentsProcessRenewalsPostRaw(initOverrides);
    }

    /**
     */
    async apiV1PaymentsResumeAutoRenewalPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/payments/resume-auto-renewal`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1PaymentsResumeAutoRenewalPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1PaymentsResumeAutoRenewalPostRaw(initOverrides);
    }

    /**
     */
    async apiV1PaymentsWebhookPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/payments/webhook`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1PaymentsWebhookPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1PaymentsWebhookPostRaw(initOverrides);
    }

}
