/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConvertRequest,
  MessageResponse,
  ReferralInfoResponse,
  ReferralPriceResponse,
  WithdrawRequest,
} from '../models/index';
import {
    ConvertRequestFromJSON,
    ConvertRequestToJSON,
    MessageResponseFromJSON,
    MessageResponseToJSON,
    ReferralInfoResponseFromJSON,
    ReferralInfoResponseToJSON,
    ReferralPriceResponseFromJSON,
    ReferralPriceResponseToJSON,
    WithdrawRequestFromJSON,
    WithdrawRequestToJSON,
} from '../models/index';

export interface ApiV1ReferralConvertPostRequest {
    convertRequest?: ConvertRequest;
}

export interface ApiV1ReferralWithdrawPostRequest {
    withdrawRequest?: WithdrawRequest;
}

/**
 * 
 */
export class ReferralApi extends runtime.BaseAPI {

    /**
     */
    async apiV1ReferralConvertPostRaw(requestParameters: ApiV1ReferralConvertPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/referral/convert`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConvertRequestToJSON(requestParameters['convertRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1ReferralConvertPost(requestParameters: ApiV1ReferralConvertPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.apiV1ReferralConvertPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1ReferralInfoGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReferralInfoResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/referral/info`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReferralInfoResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1ReferralInfoGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReferralInfoResponse> {
        const response = await this.apiV1ReferralInfoGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1ReferralPricesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ReferralPriceResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/referral/prices`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ReferralPriceResponseFromJSON));
    }

    /**
     */
    async apiV1ReferralPricesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ReferralPriceResponse>> {
        const response = await this.apiV1ReferralPricesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1ReferralWithdrawPostRaw(requestParameters: ApiV1ReferralWithdrawPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/referral/withdraw`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WithdrawRequestToJSON(requestParameters['withdrawRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1ReferralWithdrawPost(requestParameters: ApiV1ReferralWithdrawPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.apiV1ReferralWithdrawPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
