/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PresignedUrlResponse,
  TriggerReportDownloadRequest,
} from '../models/index';
import {
    PresignedUrlResponseFromJSON,
    PresignedUrlResponseToJSON,
    TriggerReportDownloadRequestFromJSON,
    TriggerReportDownloadRequestToJSON,
} from '../models/index';

export interface ApiV1ReportsBrandIdPresignedGetRequest {
    brandId: string;
    type?: string;
    turnstileToken?: string;
}

export interface ApiV1ReportsTriggerDownloadPostRequest {
    triggerReportDownloadRequest?: TriggerReportDownloadRequest;
}

/**
 * 
 */
export class ReportApi extends runtime.BaseAPI {

    /**
     */
    async apiV1ReportsBrandIdPresignedGetRaw(requestParameters: ApiV1ReportsBrandIdPresignedGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PresignedUrlResponse>> {
        if (requestParameters['brandId'] == null) {
            throw new runtime.RequiredError(
                'brandId',
                'Required parameter "brandId" was null or undefined when calling apiV1ReportsBrandIdPresignedGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['turnstileToken'] != null) {
            queryParameters['turnstileToken'] = requestParameters['turnstileToken'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/reports/{brandId}/presigned`.replace(`{${"brandId"}}`, encodeURIComponent(String(requestParameters['brandId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PresignedUrlResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1ReportsBrandIdPresignedGet(requestParameters: ApiV1ReportsBrandIdPresignedGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PresignedUrlResponse> {
        const response = await this.apiV1ReportsBrandIdPresignedGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1ReportsTriggerDownloadPostRaw(requestParameters: ApiV1ReportsTriggerDownloadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/reports/trigger-download`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TriggerReportDownloadRequestToJSON(requestParameters['triggerReportDownloadRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1ReportsTriggerDownloadPost(requestParameters: ApiV1ReportsTriggerDownloadPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1ReportsTriggerDownloadPostRaw(requestParameters, initOverrides);
    }

}
