/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PortfolioIncomeResponse,
  SaveTinkoffApiKeyRequest,
  TinkoffPortfolioResponse,
} from '../models/index';
import {
    PortfolioIncomeResponseFromJSON,
    PortfolioIncomeResponseToJSON,
    SaveTinkoffApiKeyRequestFromJSON,
    SaveTinkoffApiKeyRequestToJSON,
    TinkoffPortfolioResponseFromJSON,
    TinkoffPortfolioResponseToJSON,
} from '../models/index';

export interface ApiV1PortfolioTinkoffApiKeyPutRequest {
    saveTinkoffApiKeyRequest?: SaveTinkoffApiKeyRequest;
}

export interface ApiV1PortfolioTinkoffOperationsIncomeGetRequest {
    from?: Date;
    to?: Date;
}

/**
 * 
 */
export class TinkoffPortfolioApi extends runtime.BaseAPI {

    /**
     */
    async apiV1PortfolioTinkoffApiKeyPutRaw(requestParameters: ApiV1PortfolioTinkoffApiKeyPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/portfolio/tinkoff/api-key`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SaveTinkoffApiKeyRequestToJSON(requestParameters['saveTinkoffApiKeyRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1PortfolioTinkoffApiKeyPut(requestParameters: ApiV1PortfolioTinkoffApiKeyPutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1PortfolioTinkoffApiKeyPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiV1PortfolioTinkoffGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TinkoffPortfolioResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/portfolio/tinkoff`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TinkoffPortfolioResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1PortfolioTinkoffGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TinkoffPortfolioResponse> {
        const response = await this.apiV1PortfolioTinkoffGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1PortfolioTinkoffOperationsIncomeGetRaw(requestParameters: ApiV1PortfolioTinkoffOperationsIncomeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PortfolioIncomeResponse>> {
        const queryParameters: any = {};

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/portfolio/tinkoff/operations/income`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PortfolioIncomeResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1PortfolioTinkoffOperationsIncomeGet(requestParameters: ApiV1PortfolioTinkoffOperationsIncomeGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PortfolioIncomeResponse> {
        const response = await this.apiV1PortfolioTinkoffOperationsIncomeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
