/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MarkedIssuerListResponse,
  MessageResponse,
  SaveUserCollectionRequest,
  ToggleMarkedIssuerRequest,
  UpdateCustomFiltersRequest,
  UpdateUserCollectionRequest,
  UserCollectionListResponse,
  UserCollectionResponse,
} from '../models/index';
import {
    MarkedIssuerListResponseFromJSON,
    MarkedIssuerListResponseToJSON,
    MessageResponseFromJSON,
    MessageResponseToJSON,
    SaveUserCollectionRequestFromJSON,
    SaveUserCollectionRequestToJSON,
    ToggleMarkedIssuerRequestFromJSON,
    ToggleMarkedIssuerRequestToJSON,
    UpdateCustomFiltersRequestFromJSON,
    UpdateCustomFiltersRequestToJSON,
    UpdateUserCollectionRequestFromJSON,
    UpdateUserCollectionRequestToJSON,
    UserCollectionListResponseFromJSON,
    UserCollectionListResponseToJSON,
    UserCollectionResponseFromJSON,
    UserCollectionResponseToJSON,
} from '../models/index';

export interface ApiV1UserPreferencesCollectionsIdDeleteRequest {
    id: string;
}

export interface ApiV1UserPreferencesCollectionsIdPutRequest {
    id: string;
    updateUserCollectionRequest?: UpdateUserCollectionRequest;
}

export interface ApiV1UserPreferencesCollectionsPostRequest {
    saveUserCollectionRequest?: SaveUserCollectionRequest;
}

export interface ApiV1UserPreferencesCustomFiltersPutRequest {
    updateCustomFiltersRequest?: UpdateCustomFiltersRequest;
}

export interface ApiV1UserPreferencesMarkedIssuersTogglePostRequest {
    toggleMarkedIssuerRequest?: ToggleMarkedIssuerRequest;
}

/**
 * 
 */
export class UserPreferencesApi extends runtime.BaseAPI {

    /**
     */
    async apiV1UserPreferencesCollectionsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserCollectionListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/user-preferences/collections`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserCollectionListResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1UserPreferencesCollectionsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserCollectionListResponse> {
        const response = await this.apiV1UserPreferencesCollectionsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1UserPreferencesCollectionsIdDeleteRaw(requestParameters: ApiV1UserPreferencesCollectionsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1UserPreferencesCollectionsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/user-preferences/collections/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1UserPreferencesCollectionsIdDelete(requestParameters: ApiV1UserPreferencesCollectionsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.apiV1UserPreferencesCollectionsIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1UserPreferencesCollectionsIdPutRaw(requestParameters: ApiV1UserPreferencesCollectionsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1UserPreferencesCollectionsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/user-preferences/collections/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateUserCollectionRequestToJSON(requestParameters['updateUserCollectionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1UserPreferencesCollectionsIdPut(requestParameters: ApiV1UserPreferencesCollectionsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.apiV1UserPreferencesCollectionsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1UserPreferencesCollectionsPostRaw(requestParameters: ApiV1UserPreferencesCollectionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserCollectionResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/user-preferences/collections`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SaveUserCollectionRequestToJSON(requestParameters['saveUserCollectionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserCollectionResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1UserPreferencesCollectionsPost(requestParameters: ApiV1UserPreferencesCollectionsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserCollectionResponse> {
        const response = await this.apiV1UserPreferencesCollectionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1UserPreferencesCustomFiltersPutRaw(requestParameters: ApiV1UserPreferencesCustomFiltersPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/user-preferences/custom-filters`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCustomFiltersRequestToJSON(requestParameters['updateCustomFiltersRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1UserPreferencesCustomFiltersPut(requestParameters: ApiV1UserPreferencesCustomFiltersPutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.apiV1UserPreferencesCustomFiltersPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1UserPreferencesMarkedIssuersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MarkedIssuerListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/user-preferences/marked-issuers`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MarkedIssuerListResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1UserPreferencesMarkedIssuersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MarkedIssuerListResponse> {
        const response = await this.apiV1UserPreferencesMarkedIssuersGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1UserPreferencesMarkedIssuersTogglePostRaw(requestParameters: ApiV1UserPreferencesMarkedIssuersTogglePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/user-preferences/marked-issuers/toggle`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ToggleMarkedIssuerRequestToJSON(requestParameters['toggleMarkedIssuerRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiV1UserPreferencesMarkedIssuersTogglePost(requestParameters: ApiV1UserPreferencesMarkedIssuersTogglePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponse> {
        const response = await this.apiV1UserPreferencesMarkedIssuersTogglePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
