/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BondCouponType } from './BondCouponType';
import {
    BondCouponTypeFromJSON,
    BondCouponTypeFromJSONTyped,
    BondCouponTypeToJSON,
} from './BondCouponType';
import type { BondRateType } from './BondRateType';
import {
    BondRateTypeFromJSON,
    BondRateTypeFromJSONTyped,
    BondRateTypeToJSON,
} from './BondRateType';

/**
 * 
 * @export
 * @interface AdminBondUpdateRequest
 */
export interface AdminBondUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof AdminBondUpdateRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminBondUpdateRequest
     */
    shortName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminBondUpdateRequest
     */
    fullName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminBondUpdateRequest
     */
    ticker?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminBondUpdateRequest
     */
    isin?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminBondUpdateRequest
     */
    figi?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AdminBondUpdateRequest
     */
    price?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdminBondUpdateRequest
     */
    aciValue?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AdminBondUpdateRequest
     */
    currency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminBondUpdateRequest
     */
    nominalCurrency?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AdminBondUpdateRequest
     */
    couponQuantityPerYear?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AdminBondUpdateRequest
     */
    sector?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AdminBondUpdateRequest
     */
    initialNominal?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdminBondUpdateRequest
     */
    currentNominal?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof AdminBondUpdateRequest
     */
    maturityDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof AdminBondUpdateRequest
     */
    placementDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof AdminBondUpdateRequest
     */
    type?: string | null;
    /**
     * 
     * @type {BondCouponType}
     * @memberof AdminBondUpdateRequest
     */
    couponType?: BondCouponType;
    /**
     * 
     * @type {number}
     * @memberof AdminBondUpdateRequest
     */
    nextCouponValuePrc?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdminBondUpdateRequest
     */
    nextCouponValue?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof AdminBondUpdateRequest
     */
    nextCouponDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof AdminBondUpdateRequest
     */
    _yield?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdminBondUpdateRequest
     */
    duration?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdminBondUpdateRequest
     */
    currentYield?: number | null;
    /**
     * 
     * @type {BondRateType}
     * @memberof AdminBondUpdateRequest
     */
    rateType?: BondRateType;
    /**
     * 
     * @type {number}
     * @memberof AdminBondUpdateRequest
     */
    spread?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdminBondUpdateRequest
     */
    marginAbleFlag?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdminBondUpdateRequest
     */
    forQualInvestorFlag?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdminBondUpdateRequest
     */
    amortizationFlag?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdminBondUpdateRequest
     */
    floatingCouponFlag?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdminBondUpdateRequest
     */
    buyAvailableFlag?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdminBondUpdateRequest
     */
    availableInT?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdminBondUpdateRequest
     */
    availableInAutofollow?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdminBondUpdateRequest
     */
    defaultFlag?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdminBondUpdateRequest
     */
    technicalDefaultFlag?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof AdminBondUpdateRequest
     */
    volume?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof AdminBondUpdateRequest
     */
    nextMaturityDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof AdminBondUpdateRequest
     */
    nextMaturityValue?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof AdminBondUpdateRequest
     */
    nextCall?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof AdminBondUpdateRequest
     */
    nextCallType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminBondUpdateRequest
     */
    brandId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminBondUpdateRequest
     */
    creditRating?: string | null;
}

/**
 * Check if a given object implements the AdminBondUpdateRequest interface.
 */
export function instanceOfAdminBondUpdateRequest(value: object): value is AdminBondUpdateRequest {
    return true;
}

export function AdminBondUpdateRequestFromJSON(json: any): AdminBondUpdateRequest {
    return AdminBondUpdateRequestFromJSONTyped(json, false);
}

export function AdminBondUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminBondUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'shortName': json['shortName'] == null ? undefined : json['shortName'],
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'ticker': json['ticker'] == null ? undefined : json['ticker'],
        'isin': json['isin'] == null ? undefined : json['isin'],
        'figi': json['figi'] == null ? undefined : json['figi'],
        'price': json['price'] == null ? undefined : json['price'],
        'aciValue': json['aciValue'] == null ? undefined : json['aciValue'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'nominalCurrency': json['nominalCurrency'] == null ? undefined : json['nominalCurrency'],
        'couponQuantityPerYear': json['couponQuantityPerYear'] == null ? undefined : json['couponQuantityPerYear'],
        'sector': json['sector'] == null ? undefined : json['sector'],
        'initialNominal': json['initialNominal'] == null ? undefined : json['initialNominal'],
        'currentNominal': json['currentNominal'] == null ? undefined : json['currentNominal'],
        'maturityDate': json['maturityDate'] == null ? undefined : (new Date(json['maturityDate'])),
        'placementDate': json['placementDate'] == null ? undefined : (new Date(json['placementDate'])),
        'type': json['type'] == null ? undefined : json['type'],
        'couponType': json['couponType'] == null ? undefined : BondCouponTypeFromJSON(json['couponType']),
        'nextCouponValuePrc': json['nextCouponValuePrc'] == null ? undefined : json['nextCouponValuePrc'],
        'nextCouponValue': json['nextCouponValue'] == null ? undefined : json['nextCouponValue'],
        'nextCouponDate': json['nextCouponDate'] == null ? undefined : (new Date(json['nextCouponDate'])),
        '_yield': json['yield'] == null ? undefined : json['yield'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'currentYield': json['currentYield'] == null ? undefined : json['currentYield'],
        'rateType': json['rateType'] == null ? undefined : BondRateTypeFromJSON(json['rateType']),
        'spread': json['spread'] == null ? undefined : json['spread'],
        'marginAbleFlag': json['marginAbleFlag'] == null ? undefined : json['marginAbleFlag'],
        'forQualInvestorFlag': json['forQualInvestorFlag'] == null ? undefined : json['forQualInvestorFlag'],
        'amortizationFlag': json['amortizationFlag'] == null ? undefined : json['amortizationFlag'],
        'floatingCouponFlag': json['floatingCouponFlag'] == null ? undefined : json['floatingCouponFlag'],
        'buyAvailableFlag': json['buyAvailableFlag'] == null ? undefined : json['buyAvailableFlag'],
        'availableInT': json['availableInT'] == null ? undefined : json['availableInT'],
        'availableInAutofollow': json['availableInAutofollow'] == null ? undefined : json['availableInAutofollow'],
        'defaultFlag': json['defaultFlag'] == null ? undefined : json['defaultFlag'],
        'technicalDefaultFlag': json['technicalDefaultFlag'] == null ? undefined : json['technicalDefaultFlag'],
        'volume': json['volume'] == null ? undefined : json['volume'],
        'nextMaturityDate': json['nextMaturityDate'] == null ? undefined : (new Date(json['nextMaturityDate'])),
        'nextMaturityValue': json['nextMaturityValue'] == null ? undefined : json['nextMaturityValue'],
        'nextCall': json['nextCall'] == null ? undefined : (new Date(json['nextCall'])),
        'nextCallType': json['nextCallType'] == null ? undefined : json['nextCallType'],
        'brandId': json['brandId'] == null ? undefined : json['brandId'],
        'creditRating': json['creditRating'] == null ? undefined : json['creditRating'],
    };
}

export function AdminBondUpdateRequestToJSON(value?: AdminBondUpdateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'shortName': value['shortName'],
        'fullName': value['fullName'],
        'ticker': value['ticker'],
        'isin': value['isin'],
        'figi': value['figi'],
        'price': value['price'],
        'aciValue': value['aciValue'],
        'currency': value['currency'],
        'nominalCurrency': value['nominalCurrency'],
        'couponQuantityPerYear': value['couponQuantityPerYear'],
        'sector': value['sector'],
        'initialNominal': value['initialNominal'],
        'currentNominal': value['currentNominal'],
        'maturityDate': value['maturityDate'] == null ? undefined : ((value['maturityDate'] as any).toISOString()),
        'placementDate': value['placementDate'] == null ? undefined : ((value['placementDate'] as any).toISOString()),
        'type': value['type'],
        'couponType': BondCouponTypeToJSON(value['couponType']),
        'nextCouponValuePrc': value['nextCouponValuePrc'],
        'nextCouponValue': value['nextCouponValue'],
        'nextCouponDate': value['nextCouponDate'] == null ? undefined : ((value['nextCouponDate'] as any).toISOString()),
        'yield': value['_yield'],
        'duration': value['duration'],
        'currentYield': value['currentYield'],
        'rateType': BondRateTypeToJSON(value['rateType']),
        'spread': value['spread'],
        'marginAbleFlag': value['marginAbleFlag'],
        'forQualInvestorFlag': value['forQualInvestorFlag'],
        'amortizationFlag': value['amortizationFlag'],
        'floatingCouponFlag': value['floatingCouponFlag'],
        'buyAvailableFlag': value['buyAvailableFlag'],
        'availableInT': value['availableInT'],
        'availableInAutofollow': value['availableInAutofollow'],
        'defaultFlag': value['defaultFlag'],
        'technicalDefaultFlag': value['technicalDefaultFlag'],
        'volume': value['volume'],
        'nextMaturityDate': value['nextMaturityDate'] == null ? undefined : ((value['nextMaturityDate'] as any).toISOString()),
        'nextMaturityValue': value['nextMaturityValue'],
        'nextCall': value['nextCall'] == null ? undefined : ((value['nextCall'] as any).toISOString()),
        'nextCallType': value['nextCallType'],
        'brandId': value['brandId'],
        'creditRating': value['creditRating'],
    };
}

