/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinalBondResponse } from './FinalBondResponse';
import {
    FinalBondResponseFromJSON,
    FinalBondResponseFromJSONTyped,
    FinalBondResponseToJSON,
} from './FinalBondResponse';

/**
 * 
 * @export
 * @interface AlternativeBondsResponse
 */
export interface AlternativeBondsResponse {
    /**
     * 
     * @type {Array<FinalBondResponse>}
     * @memberof AlternativeBondsResponse
     */
    higherRiskYield?: Array<FinalBondResponse> | null;
    /**
     * 
     * @type {Array<FinalBondResponse>}
     * @memberof AlternativeBondsResponse
     */
    lowerRiskYield?: Array<FinalBondResponse> | null;
    /**
     * 
     * @type {number}
     * @memberof AlternativeBondsResponse
     */
    higherRiskYieldCount?: number;
    /**
     * 
     * @type {number}
     * @memberof AlternativeBondsResponse
     */
    lowerRiskYieldCount?: number;
}

/**
 * Check if a given object implements the AlternativeBondsResponse interface.
 */
export function instanceOfAlternativeBondsResponse(value: object): value is AlternativeBondsResponse {
    return true;
}

export function AlternativeBondsResponseFromJSON(json: any): AlternativeBondsResponse {
    return AlternativeBondsResponseFromJSONTyped(json, false);
}

export function AlternativeBondsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlternativeBondsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'higherRiskYield': json['higherRiskYield'] == null ? undefined : ((json['higherRiskYield'] as Array<any>).map(FinalBondResponseFromJSON)),
        'lowerRiskYield': json['lowerRiskYield'] == null ? undefined : ((json['lowerRiskYield'] as Array<any>).map(FinalBondResponseFromJSON)),
        'higherRiskYieldCount': json['higherRiskYieldCount'] == null ? undefined : json['higherRiskYieldCount'],
        'lowerRiskYieldCount': json['lowerRiskYieldCount'] == null ? undefined : json['lowerRiskYieldCount'],
    };
}

export function AlternativeBondsResponseToJSON(value?: AlternativeBondsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'higherRiskYield': value['higherRiskYield'] == null ? undefined : ((value['higherRiskYield'] as Array<any>).map(FinalBondResponseToJSON)),
        'lowerRiskYield': value['lowerRiskYield'] == null ? undefined : ((value['lowerRiskYield'] as Array<any>).map(FinalBondResponseToJSON)),
        'higherRiskYieldCount': value['higherRiskYieldCount'],
        'lowerRiskYieldCount': value['lowerRiskYieldCount'],
    };
}

