/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplyReportRequest
 */
export interface ApplyReportRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof ApplyReportRequest
     */
    brandIds: Array<string>;
}

/**
 * Check if a given object implements the ApplyReportRequest interface.
 */
export function instanceOfApplyReportRequest(value: object): value is ApplyReportRequest {
    if (!('brandIds' in value) || value['brandIds'] === undefined) return false;
    return true;
}

export function ApplyReportRequestFromJSON(json: any): ApplyReportRequest {
    return ApplyReportRequestFromJSONTyped(json, false);
}

export function ApplyReportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplyReportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'brandIds': json['brandIds'],
    };
}

export function ApplyReportRequestToJSON(value?: ApplyReportRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'brandIds': value['brandIds'],
    };
}

