/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BondCoupon
 */
export interface BondCoupon {
    /**
     * 
     * @type {Date}
     * @memberof BondCoupon
     */
    date?: Date;
    /**
     * 
     * @type {number}
     * @memberof BondCoupon
     */
    value?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BondCoupon
     */
    valuePrc?: number | null;
}

/**
 * Check if a given object implements the BondCoupon interface.
 */
export function instanceOfBondCoupon(value: object): value is BondCoupon {
    return true;
}

export function BondCouponFromJSON(json: any): BondCoupon {
    return BondCouponFromJSONTyped(json, false);
}

export function BondCouponFromJSONTyped(json: any, ignoreDiscriminator: boolean): BondCoupon {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'value': json['value'] == null ? undefined : json['value'],
        'valuePrc': json['valuePrc'] == null ? undefined : json['valuePrc'],
    };
}

export function BondCouponToJSON(value?: BondCoupon | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'date': value['date'] == null ? undefined : ((value['date']).toISOString()),
        'value': value['value'],
        'valuePrc': value['valuePrc'],
    };
}

