/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BondType = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type BondType = typeof BondType[keyof typeof BondType];


export function instanceOfBondType(value: any): boolean {
    for (const key in BondType) {
        if (Object.prototype.hasOwnProperty.call(BondType, key)) {
            if ((BondType as Record<string, BondType>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BondTypeFromJSON(json: any): BondType {
    return BondTypeFromJSONTyped(json, false);
}

export function BondTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BondType {
    return json as BondType;
}

export function BondTypeToJSON(value?: BondType | null): any {
    return value as any;
}

