/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BondCouponLadder
 */
export interface BondCouponLadder {
    /**
     * 
     * @type {Date}
     * @memberof BondCouponLadder
     */
    startDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof BondCouponLadder
     */
    newPercent?: number;
    /**
     * 
     * @type {number}
     * @memberof BondCouponLadder
     */
    paymentsCount?: number;
}

/**
 * Check if a given object implements the BondCouponLadder interface.
 */
export function instanceOfBondCouponLadder(value: object): value is BondCouponLadder {
    return true;
}

export function BondCouponLadderFromJSON(json: any): BondCouponLadder {
    return BondCouponLadderFromJSONTyped(json, false);
}

export function BondCouponLadderFromJSONTyped(json: any, ignoreDiscriminator: boolean): BondCouponLadder {
    if (json == null) {
        return json;
    }
    return {
        
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'newPercent': json['newPercent'] == null ? undefined : json['newPercent'],
        'paymentsCount': json['paymentsCount'] == null ? undefined : json['paymentsCount'],
    };
}

export function BondCouponLadderToJSON(value?: BondCouponLadder | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'startDate': value['startDate'] == null ? undefined : ((value['startDate']).toISOString()),
        'newPercent': value['newPercent'],
        'paymentsCount': value['paymentsCount'],
    };
}

