/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BondCouponLadder } from './BondCouponLadder';
import {
    BondCouponLadderFromJSON,
    BondCouponLadderFromJSONTyped,
    BondCouponLadderToJSON,
} from './BondCouponLadder';
import type { BondCouponType } from './BondCouponType';
import {
    BondCouponTypeFromJSON,
    BondCouponTypeFromJSONTyped,
    BondCouponTypeToJSON,
} from './BondCouponType';
import type { BrandBusiness } from './BrandBusiness';
import {
    BrandBusinessFromJSON,
    BrandBusinessFromJSONTyped,
    BrandBusinessToJSON,
} from './BrandBusiness';
import type { FavoriteBond } from './FavoriteBond';
import {
    FavoriteBondFromJSON,
    FavoriteBondFromJSONTyped,
    FavoriteBondToJSON,
} from './FavoriteBond';
import type { BondCoupon } from './BondCoupon';
import {
    BondCouponFromJSON,
    BondCouponFromJSONTyped,
    BondCouponToJSON,
} from './BondCoupon';
import type { BondAmortization } from './BondAmortization';
import {
    BondAmortizationFromJSON,
    BondAmortizationFromJSONTyped,
    BondAmortizationToJSON,
} from './BondAmortization';
import type { BondRateType } from './BondRateType';
import {
    BondRateTypeFromJSON,
    BondRateTypeFromJSONTyped,
    BondRateTypeToJSON,
} from './BondRateType';

/**
 * 
 * @export
 * @interface BondInstrument
 */
export interface BondInstrument {
    /**
     * 
     * @type {string}
     * @memberof BondInstrument
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof BondInstrument
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BondInstrument
     */
    creditRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BondInstrument
     */
    shortName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BondInstrument
     */
    fullName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BondInstrument
     */
    ticker?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BondInstrument
     */
    isin?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BondInstrument
     */
    figi?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BondInstrument
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof BondInstrument
     */
    aciValue?: number | null;
    /**
     * 
     * @type {string}
     * @memberof BondInstrument
     */
    currency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BondInstrument
     */
    nominalCurrency?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BondInstrument
     */
    couponQuantityPerYear?: number;
    /**
     * 
     * @type {string}
     * @memberof BondInstrument
     */
    sector?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BondInstrument
     */
    initialNominal?: number;
    /**
     * 
     * @type {number}
     * @memberof BondInstrument
     */
    currentNominal?: number;
    /**
     * 
     * @type {Date}
     * @memberof BondInstrument
     */
    maturityDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof BondInstrument
     */
    placementDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof BondInstrument
     */
    type?: string | null;
    /**
     * 
     * @type {BondCouponType}
     * @memberof BondInstrument
     */
    couponType?: BondCouponType;
    /**
     * 
     * @type {number}
     * @memberof BondInstrument
     */
    nextCouponValuePrc?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BondInstrument
     */
    nextCouponValue?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof BondInstrument
     */
    nextCouponDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof BondInstrument
     */
    _yield?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BondInstrument
     */
    duration?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BondInstrument
     */
    currentYield?: number | null;
    /**
     * 
     * @type {BondRateType}
     * @memberof BondInstrument
     */
    rateType?: BondRateType;
    /**
     * 
     * @type {number}
     * @memberof BondInstrument
     */
    spread?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BondInstrument
     */
    gSpread?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof BondInstrument
     */
    marginAbleFlag?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BondInstrument
     */
    forQualInvestorFlag?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BondInstrument
     */
    amortizationFlag?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BondInstrument
     */
    floatingCouponFlag?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BondInstrument
     */
    buyAvailableFlag?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BondInstrument
     */
    availableInT?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BondInstrument
     */
    availableInAutofollow?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BondInstrument
     */
    defaultFlag?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BondInstrument
     */
    technicalDefaultFlag?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BondInstrument
     */
    volume?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof BondInstrument
     */
    nextMaturityDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof BondInstrument
     */
    nextMaturityValue?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof BondInstrument
     */
    nextCall?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof BondInstrument
     */
    nextCallType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BondInstrument
     */
    issuerInn?: string | null;
    /**
     * 
     * @type {Array<BondAmortization>}
     * @memberof BondInstrument
     */
    amortizations?: Array<BondAmortization> | null;
    /**
     * 
     * @type {Array<BondCoupon>}
     * @memberof BondInstrument
     */
    coupons7Months?: Array<BondCoupon> | null;
    /**
     * 
     * @type {Array<BondCouponLadder>}
     * @memberof BondInstrument
     */
    couponLadders?: Array<BondCouponLadder> | null;
    /**
     * 
     * @type {string}
     * @memberof BondInstrument
     */
    brandId?: string | null;
    /**
     * 
     * @type {BrandBusiness}
     * @memberof BondInstrument
     */
    brand?: BrandBusiness;
    /**
     * 
     * @type {Array<FavoriteBond>}
     * @memberof BondInstrument
     */
    favorites?: Array<FavoriteBond> | null;
}

/**
 * Check if a given object implements the BondInstrument interface.
 */
export function instanceOfBondInstrument(value: object): value is BondInstrument {
    return true;
}

export function BondInstrumentFromJSON(json: any): BondInstrument {
    return BondInstrumentFromJSONTyped(json, false);
}

export function BondInstrumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): BondInstrument {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'creditRating': json['creditRating'] == null ? undefined : json['creditRating'],
        'shortName': json['shortName'] == null ? undefined : json['shortName'],
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'ticker': json['ticker'] == null ? undefined : json['ticker'],
        'isin': json['isin'] == null ? undefined : json['isin'],
        'figi': json['figi'] == null ? undefined : json['figi'],
        'price': json['price'] == null ? undefined : json['price'],
        'aciValue': json['aciValue'] == null ? undefined : json['aciValue'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'nominalCurrency': json['nominalCurrency'] == null ? undefined : json['nominalCurrency'],
        'couponQuantityPerYear': json['couponQuantityPerYear'] == null ? undefined : json['couponQuantityPerYear'],
        'sector': json['sector'] == null ? undefined : json['sector'],
        'initialNominal': json['initialNominal'] == null ? undefined : json['initialNominal'],
        'currentNominal': json['currentNominal'] == null ? undefined : json['currentNominal'],
        'maturityDate': json['maturityDate'] == null ? undefined : (new Date(json['maturityDate'])),
        'placementDate': json['placementDate'] == null ? undefined : (new Date(json['placementDate'])),
        'type': json['type'] == null ? undefined : json['type'],
        'couponType': json['couponType'] == null ? undefined : BondCouponTypeFromJSON(json['couponType']),
        'nextCouponValuePrc': json['nextCouponValuePrc'] == null ? undefined : json['nextCouponValuePrc'],
        'nextCouponValue': json['nextCouponValue'] == null ? undefined : json['nextCouponValue'],
        'nextCouponDate': json['nextCouponDate'] == null ? undefined : (new Date(json['nextCouponDate'])),
        '_yield': json['yield'] == null ? undefined : json['yield'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'currentYield': json['currentYield'] == null ? undefined : json['currentYield'],
        'rateType': json['rateType'] == null ? undefined : BondRateTypeFromJSON(json['rateType']),
        'spread': json['spread'] == null ? undefined : json['spread'],
        'gSpread': json['gSpread'] == null ? undefined : json['gSpread'],
        'marginAbleFlag': json['marginAbleFlag'] == null ? undefined : json['marginAbleFlag'],
        'forQualInvestorFlag': json['forQualInvestorFlag'] == null ? undefined : json['forQualInvestorFlag'],
        'amortizationFlag': json['amortizationFlag'] == null ? undefined : json['amortizationFlag'],
        'floatingCouponFlag': json['floatingCouponFlag'] == null ? undefined : json['floatingCouponFlag'],
        'buyAvailableFlag': json['buyAvailableFlag'] == null ? undefined : json['buyAvailableFlag'],
        'availableInT': json['availableInT'] == null ? undefined : json['availableInT'],
        'availableInAutofollow': json['availableInAutofollow'] == null ? undefined : json['availableInAutofollow'],
        'defaultFlag': json['defaultFlag'] == null ? undefined : json['defaultFlag'],
        'technicalDefaultFlag': json['technicalDefaultFlag'] == null ? undefined : json['technicalDefaultFlag'],
        'volume': json['volume'] == null ? undefined : json['volume'],
        'nextMaturityDate': json['nextMaturityDate'] == null ? undefined : (new Date(json['nextMaturityDate'])),
        'nextMaturityValue': json['nextMaturityValue'] == null ? undefined : json['nextMaturityValue'],
        'nextCall': json['nextCall'] == null ? undefined : (new Date(json['nextCall'])),
        'nextCallType': json['nextCallType'] == null ? undefined : json['nextCallType'],
        'issuerInn': json['issuerInn'] == null ? undefined : json['issuerInn'],
        'amortizations': json['amortizations'] == null ? undefined : ((json['amortizations'] as Array<any>).map(BondAmortizationFromJSON)),
        'coupons7Months': json['coupons7Months'] == null ? undefined : ((json['coupons7Months'] as Array<any>).map(BondCouponFromJSON)),
        'couponLadders': json['couponLadders'] == null ? undefined : ((json['couponLadders'] as Array<any>).map(BondCouponLadderFromJSON)),
        'brandId': json['brandId'] == null ? undefined : json['brandId'],
        'brand': json['brand'] == null ? undefined : BrandBusinessFromJSON(json['brand']),
        'favorites': json['favorites'] == null ? undefined : ((json['favorites'] as Array<any>).map(FavoriteBondFromJSON)),
    };
}

export function BondInstrumentToJSON(value?: BondInstrument | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'creditRating': value['creditRating'],
        'shortName': value['shortName'],
        'fullName': value['fullName'],
        'ticker': value['ticker'],
        'isin': value['isin'],
        'figi': value['figi'],
        'price': value['price'],
        'aciValue': value['aciValue'],
        'currency': value['currency'],
        'nominalCurrency': value['nominalCurrency'],
        'couponQuantityPerYear': value['couponQuantityPerYear'],
        'sector': value['sector'],
        'initialNominal': value['initialNominal'],
        'currentNominal': value['currentNominal'],
        'maturityDate': value['maturityDate'] == null ? undefined : ((value['maturityDate']).toISOString()),
        'placementDate': value['placementDate'] == null ? undefined : ((value['placementDate'] as any).toISOString()),
        'type': value['type'],
        'couponType': BondCouponTypeToJSON(value['couponType']),
        'nextCouponValuePrc': value['nextCouponValuePrc'],
        'nextCouponValue': value['nextCouponValue'],
        'nextCouponDate': value['nextCouponDate'] == null ? undefined : ((value['nextCouponDate'] as any).toISOString()),
        'yield': value['_yield'],
        'duration': value['duration'],
        'currentYield': value['currentYield'],
        'rateType': BondRateTypeToJSON(value['rateType']),
        'spread': value['spread'],
        'gSpread': value['gSpread'],
        'marginAbleFlag': value['marginAbleFlag'],
        'forQualInvestorFlag': value['forQualInvestorFlag'],
        'amortizationFlag': value['amortizationFlag'],
        'floatingCouponFlag': value['floatingCouponFlag'],
        'buyAvailableFlag': value['buyAvailableFlag'],
        'availableInT': value['availableInT'],
        'availableInAutofollow': value['availableInAutofollow'],
        'defaultFlag': value['defaultFlag'],
        'technicalDefaultFlag': value['technicalDefaultFlag'],
        'volume': value['volume'],
        'nextMaturityDate': value['nextMaturityDate'] == null ? undefined : ((value['nextMaturityDate'] as any).toISOString()),
        'nextMaturityValue': value['nextMaturityValue'],
        'nextCall': value['nextCall'] == null ? undefined : ((value['nextCall'] as any).toISOString()),
        'nextCallType': value['nextCallType'],
        'issuerInn': value['issuerInn'],
        'amortizations': value['amortizations'] == null ? undefined : ((value['amortizations'] as Array<any>).map(BondAmortizationToJSON)),
        'coupons7Months': value['coupons7Months'] == null ? undefined : ((value['coupons7Months'] as Array<any>).map(BondCouponToJSON)),
        'couponLadders': value['couponLadders'] == null ? undefined : ((value['couponLadders'] as Array<any>).map(BondCouponLadderToJSON)),
        'brandId': value['brandId'],
        'brand': BrandBusinessToJSON(value['brand']),
        'favorites': value['favorites'] == null ? undefined : ((value['favorites'] as Array<any>).map(FavoriteBondToJSON)),
    };
}

