/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BondAmortization
 */
export interface BondAmortization {
    /**
     * 
     * @type {Date}
     * @memberof BondAmortization
     */
    date?: Date;
    /**
     * 
     * @type {number}
     * @memberof BondAmortization
     */
    percent?: number;
    /**
     * 
     * @type {number}
     * @memberof BondAmortization
     */
    value?: number;
}

/**
 * Check if a given object implements the BondAmortization interface.
 */
export function instanceOfBondAmortization(value: object): value is BondAmortization {
    return true;
}

export function BondAmortizationFromJSON(json: any): BondAmortization {
    return BondAmortizationFromJSONTyped(json, false);
}

export function BondAmortizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): BondAmortization {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'percent': json['percent'] == null ? undefined : json['percent'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function BondAmortizationToJSON(value?: BondAmortization | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'date': value['date'] == null ? undefined : ((value['date']).toISOString()),
        'percent': value['percent'],
        'value': value['value'],
    };
}

