/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BondCouponType = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type BondCouponType = typeof BondCouponType[keyof typeof BondCouponType];


export function instanceOfBondCouponType(value: any): boolean {
    for (const key in BondCouponType) {
        if (Object.prototype.hasOwnProperty.call(BondCouponType, key)) {
            if ((BondCouponType as Record<string, BondCouponType>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BondCouponTypeFromJSON(json: any): BondCouponType {
    return BondCouponTypeFromJSONTyped(json, false);
}

export function BondCouponTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BondCouponType {
    return json as BondCouponType;
}

export function BondCouponTypeToJSON(value?: BondCouponType | null): any {
    return value as any;
}

