/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BondRateType = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type BondRateType = typeof BondRateType[keyof typeof BondRateType];


export function instanceOfBondRateType(value: any): boolean {
    for (const key in BondRateType) {
        if (Object.prototype.hasOwnProperty.call(BondRateType, key)) {
            if ((BondRateType as Record<string, BondRateType>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BondRateTypeFromJSON(json: any): BondRateType {
    return BondRateTypeFromJSONTyped(json, false);
}

export function BondRateTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BondRateType {
    return json as BondRateType;
}

export function BondRateTypeToJSON(value?: BondRateType | null): any {
    return value as any;
}

