/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BrandReportLinksDto
 */
export interface BrandReportLinksDto {
    /**
     * 
     * @type {string}
     * @memberof BrandReportLinksDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof BrandReportLinksDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandReportLinksDto
     */
    inn?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandReportLinksDto
     */
    consolidatedReportUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandReportLinksDto
     */
    accountingReportUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandReportLinksDto
     */
    logoName?: string | null;
}

/**
 * Check if a given object implements the BrandReportLinksDto interface.
 */
export function instanceOfBrandReportLinksDto(value: object): value is BrandReportLinksDto {
    return true;
}

export function BrandReportLinksDtoFromJSON(json: any): BrandReportLinksDto {
    return BrandReportLinksDtoFromJSONTyped(json, false);
}

export function BrandReportLinksDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrandReportLinksDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'inn': json['inn'] == null ? undefined : json['inn'],
        'consolidatedReportUrl': json['consolidatedReportUrl'] == null ? undefined : json['consolidatedReportUrl'],
        'accountingReportUrl': json['accountingReportUrl'] == null ? undefined : json['accountingReportUrl'],
        'logoName': json['logoName'] == null ? undefined : json['logoName'],
    };
}

export function BrandReportLinksDtoToJSON(value?: BrandReportLinksDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'inn': value['inn'],
        'consolidatedReportUrl': value['consolidatedReportUrl'],
        'accountingReportUrl': value['accountingReportUrl'],
        'logoName': value['logoName'],
    };
}

