/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubSectorType } from './SubSectorType';
import {
    SubSectorTypeFromJSON,
    SubSectorTypeFromJSONTyped,
    SubSectorTypeToJSON,
} from './SubSectorType';
import type { FinancialReport } from './FinancialReport';
import {
    FinancialReportFromJSON,
    FinancialReportFromJSONTyped,
    FinancialReportToJSON,
} from './FinancialReport';
import type { BondInstrument } from './BondInstrument';
import {
    BondInstrumentFromJSON,
    BondInstrumentFromJSONTyped,
    BondInstrumentToJSON,
} from './BondInstrument';
import type { SectorType } from './SectorType';
import {
    SectorTypeFromJSON,
    SectorTypeFromJSONTyped,
    SectorTypeToJSON,
} from './SectorType';

/**
 * 
 * @export
 * @interface BrandBusiness
 */
export interface BrandBusiness {
    /**
     * 
     * @type {string}
     * @memberof BrandBusiness
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof BrandBusiness
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandBusiness
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandBusiness
     */
    logoName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandBusiness
     */
    creditRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandBusiness
     */
    docType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandBusiness
     */
    fileUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandBusiness
     */
    disclosureUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandBusiness
     */
    consolidatedReportUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandBusiness
     */
    accountingReportUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandBusiness
     */
    msfoReportName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandBusiness
     */
    rsbuReportName?: string | null;
    /**
     * 
     * @type {SectorType}
     * @memberof BrandBusiness
     */
    sector?: SectorType;
    /**
     * 
     * @type {SubSectorType}
     * @memberof BrandBusiness
     */
    subSector?: SubSectorType;
    /**
     * 
     * @type {Array<string>}
     * @memberof BrandBusiness
     */
    investmentPros?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof BrandBusiness
     */
    investmentCons?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof BrandBusiness
     */
    keyRisks?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof BrandBusiness
     */
    tracked?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BrandBusiness
     */
    inn?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof BrandBusiness
     */
    isSpv?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof BrandBusiness
     */
    isSfoOrMortgageAgent?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof BrandBusiness
     */
    guarantorNameRaw?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandBusiness
     */
    guarantorInnRaw?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandBusiness
     */
    guarantorId?: string | null;
    /**
     * 
     * @type {BrandBusiness}
     * @memberof BrandBusiness
     */
    guarantor?: BrandBusiness;
    /**
     * 
     * @type {Array<BrandBusiness>}
     * @memberof BrandBusiness
     */
    guaranteedEntities?: Array<BrandBusiness> | null;
    /**
     * 
     * @type {Array<BondInstrument>}
     * @memberof BrandBusiness
     */
    bonds?: Array<BondInstrument> | null;
    /**
     * 
     * @type {Array<FinancialReport>}
     * @memberof BrandBusiness
     */
    financialReports?: Array<FinancialReport> | null;
}

/**
 * Check if a given object implements the BrandBusiness interface.
 */
export function instanceOfBrandBusiness(value: object): value is BrandBusiness {
    return true;
}

export function BrandBusinessFromJSON(json: any): BrandBusiness {
    return BrandBusinessFromJSONTyped(json, false);
}

export function BrandBusinessFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrandBusiness {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'logoName': json['logoName'] == null ? undefined : json['logoName'],
        'creditRating': json['creditRating'] == null ? undefined : json['creditRating'],
        'docType': json['docType'] == null ? undefined : json['docType'],
        'fileUrl': json['fileUrl'] == null ? undefined : json['fileUrl'],
        'disclosureUrl': json['disclosureUrl'] == null ? undefined : json['disclosureUrl'],
        'consolidatedReportUrl': json['consolidatedReportUrl'] == null ? undefined : json['consolidatedReportUrl'],
        'accountingReportUrl': json['accountingReportUrl'] == null ? undefined : json['accountingReportUrl'],
        'msfoReportName': json['msfoReportName'] == null ? undefined : json['msfoReportName'],
        'rsbuReportName': json['rsbuReportName'] == null ? undefined : json['rsbuReportName'],
        'sector': json['sector'] == null ? undefined : SectorTypeFromJSON(json['sector']),
        'subSector': json['subSector'] == null ? undefined : SubSectorTypeFromJSON(json['subSector']),
        'investmentPros': json['investmentPros'] == null ? undefined : json['investmentPros'],
        'investmentCons': json['investmentCons'] == null ? undefined : json['investmentCons'],
        'keyRisks': json['keyRisks'] == null ? undefined : json['keyRisks'],
        'tracked': json['tracked'] == null ? undefined : json['tracked'],
        'inn': json['inn'] == null ? undefined : json['inn'],
        'isSpv': json['isSpv'] == null ? undefined : json['isSpv'],
        'isSfoOrMortgageAgent': json['isSfoOrMortgageAgent'] == null ? undefined : json['isSfoOrMortgageAgent'],
        'guarantorNameRaw': json['guarantorNameRaw'] == null ? undefined : json['guarantorNameRaw'],
        'guarantorInnRaw': json['guarantorInnRaw'] == null ? undefined : json['guarantorInnRaw'],
        'guarantorId': json['guarantorId'] == null ? undefined : json['guarantorId'],
        'guarantor': json['guarantor'] == null ? undefined : BrandBusinessFromJSON(json['guarantor']),
        'guaranteedEntities': json['guaranteedEntities'] == null ? undefined : ((json['guaranteedEntities'] as Array<any>).map(BrandBusinessFromJSON)),
        'bonds': json['bonds'] == null ? undefined : ((json['bonds'] as Array<any>).map(BondInstrumentFromJSON)),
        'financialReports': json['financialReports'] == null ? undefined : ((json['financialReports'] as Array<any>).map(FinancialReportFromJSON)),
    };
}

export function BrandBusinessToJSON(value?: BrandBusiness | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'logoName': value['logoName'],
        'creditRating': value['creditRating'],
        'docType': value['docType'],
        'fileUrl': value['fileUrl'],
        'disclosureUrl': value['disclosureUrl'],
        'consolidatedReportUrl': value['consolidatedReportUrl'],
        'accountingReportUrl': value['accountingReportUrl'],
        'msfoReportName': value['msfoReportName'],
        'rsbuReportName': value['rsbuReportName'],
        'sector': SectorTypeToJSON(value['sector']),
        'subSector': SubSectorTypeToJSON(value['subSector']),
        'investmentPros': value['investmentPros'],
        'investmentCons': value['investmentCons'],
        'keyRisks': value['keyRisks'],
        'tracked': value['tracked'],
        'inn': value['inn'],
        'isSpv': value['isSpv'],
        'isSfoOrMortgageAgent': value['isSfoOrMortgageAgent'],
        'guarantorNameRaw': value['guarantorNameRaw'],
        'guarantorInnRaw': value['guarantorInnRaw'],
        'guarantorId': value['guarantorId'],
        'guarantor': BrandBusinessToJSON(value['guarantor']),
        'guaranteedEntities': value['guaranteedEntities'] == null ? undefined : ((value['guaranteedEntities'] as Array<any>).map(BrandBusinessToJSON)),
        'bonds': value['bonds'] == null ? undefined : ((value['bonds'] as Array<any>).map(BondInstrumentToJSON)),
        'financialReports': value['financialReports'] == null ? undefined : ((value['financialReports'] as Array<any>).map(FinancialReportToJSON)),
    };
}

