/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BrandUpdateRequest
 */
export interface BrandUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof BrandUpdateRequest
     */
    logoName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandUpdateRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandUpdateRequest
     */
    creditRating?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandUpdateRequest
     */
    docType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandUpdateRequest
     */
    consolidatedReportUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandUpdateRequest
     */
    accountingReportUrl?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof BrandUpdateRequest
     */
    isSpv?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof BrandUpdateRequest
     */
    isSfoOrMortgageAgent?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof BrandUpdateRequest
     */
    guarantorId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandUpdateRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandUpdateRequest
     */
    sector?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandUpdateRequest
     */
    subSector?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof BrandUpdateRequest
     */
    investmentPros?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof BrandUpdateRequest
     */
    investmentCons?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof BrandUpdateRequest
     */
    keyRisks?: Array<string> | null;
}

/**
 * Check if a given object implements the BrandUpdateRequest interface.
 */
export function instanceOfBrandUpdateRequest(value: object): value is BrandUpdateRequest {
    return true;
}

export function BrandUpdateRequestFromJSON(json: any): BrandUpdateRequest {
    return BrandUpdateRequestFromJSONTyped(json, false);
}

export function BrandUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrandUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'logoName': json['logoName'] == null ? undefined : json['logoName'],
        'name': json['name'] == null ? undefined : json['name'],
        'creditRating': json['creditRating'] == null ? undefined : json['creditRating'],
        'docType': json['docType'] == null ? undefined : json['docType'],
        'consolidatedReportUrl': json['consolidatedReportUrl'] == null ? undefined : json['consolidatedReportUrl'],
        'accountingReportUrl': json['accountingReportUrl'] == null ? undefined : json['accountingReportUrl'],
        'isSpv': json['isSpv'] == null ? undefined : json['isSpv'],
        'isSfoOrMortgageAgent': json['isSfoOrMortgageAgent'] == null ? undefined : json['isSfoOrMortgageAgent'],
        'guarantorId': json['guarantorId'] == null ? undefined : json['guarantorId'],
        'description': json['description'] == null ? undefined : json['description'],
        'sector': json['sector'] == null ? undefined : json['sector'],
        'subSector': json['subSector'] == null ? undefined : json['subSector'],
        'investmentPros': json['investmentPros'] == null ? undefined : json['investmentPros'],
        'investmentCons': json['investmentCons'] == null ? undefined : json['investmentCons'],
        'keyRisks': json['keyRisks'] == null ? undefined : json['keyRisks'],
    };
}

export function BrandUpdateRequestToJSON(value?: BrandUpdateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'logoName': value['logoName'],
        'name': value['name'],
        'creditRating': value['creditRating'],
        'docType': value['docType'],
        'consolidatedReportUrl': value['consolidatedReportUrl'],
        'accountingReportUrl': value['accountingReportUrl'],
        'isSpv': value['isSpv'],
        'isSfoOrMortgageAgent': value['isSfoOrMortgageAgent'],
        'guarantorId': value['guarantorId'],
        'description': value['description'],
        'sector': value['sector'],
        'subSector': value['subSector'],
        'investmentPros': value['investmentPros'],
        'investmentCons': value['investmentCons'],
        'keyRisks': value['keyRisks'],
    };
}

