/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CheckingState = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type CheckingState = typeof CheckingState[keyof typeof CheckingState];


export function instanceOfCheckingState(value: any): boolean {
    for (const key in CheckingState) {
        if (Object.prototype.hasOwnProperty.call(CheckingState, key)) {
            if ((CheckingState as Record<string, CheckingState>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CheckingStateFromJSON(json: any): CheckingState {
    return CheckingStateFromJSONTyped(json, false);
}

export function CheckingStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckingState {
    return json as CheckingState;
}

export function CheckingStateToJSON(value?: CheckingState | null): any {
    return value as any;
}

