/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConvertRequest
 */
export interface ConvertRequest {
    /**
     * 
     * @type {number}
     * @memberof ConvertRequest
     */
    amountWooden?: number;
}

/**
 * Check if a given object implements the ConvertRequest interface.
 */
export function instanceOfConvertRequest(value: object): value is ConvertRequest {
    return true;
}

export function ConvertRequestFromJSON(json: any): ConvertRequest {
    return ConvertRequestFromJSONTyped(json, false);
}

export function ConvertRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConvertRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amountWooden': json['amountWooden'] == null ? undefined : json['amountWooden'],
    };
}

export function ConvertRequestToJSON(value?: ConvertRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amountWooden': value['amountWooden'],
    };
}

