/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CouponBindingDto
 */
export interface CouponBindingDto {
    /**
     * 
     * @type {string}
     * @memberof CouponBindingDto
     */
    type?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CouponBindingDto
     */
    spread?: number;
}

/**
 * Check if a given object implements the CouponBindingDto interface.
 */
export function instanceOfCouponBindingDto(value: object): value is CouponBindingDto {
    return true;
}

export function CouponBindingDtoFromJSON(json: any): CouponBindingDto {
    return CouponBindingDtoFromJSONTyped(json, false);
}

export function CouponBindingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CouponBindingDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'spread': json['spread'] == null ? undefined : json['spread'],
    };
}

export function CouponBindingDtoToJSON(value?: CouponBindingDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'spread': value['spread'],
    };
}

