/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TariffType } from './TariffType';
import {
    TariffTypeFromJSON,
    TariffTypeFromJSONTyped,
    TariffTypeToJSON,
} from './TariffType';

/**
 * 
 * @export
 * @interface CreatePaymentRequest
 */
export interface CreatePaymentRequest {
    /**
     * 
     * @type {TariffType}
     * @memberof CreatePaymentRequest
     */
    tariffType?: TariffType;
}

/**
 * Check if a given object implements the CreatePaymentRequest interface.
 */
export function instanceOfCreatePaymentRequest(value: object): value is CreatePaymentRequest {
    return true;
}

export function CreatePaymentRequestFromJSON(json: any): CreatePaymentRequest {
    return CreatePaymentRequestFromJSONTyped(json, false);
}

export function CreatePaymentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePaymentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tariffType': json['tariffType'] == null ? undefined : TariffTypeFromJSON(json['tariffType']),
    };
}

export function CreatePaymentRequestToJSON(value?: CreatePaymentRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tariffType': TariffTypeToJSON(value['tariffType']),
    };
}

