/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailVerifyRequest
 */
export interface EmailVerifyRequest {
    /**
     * 
     * @type {string}
     * @memberof EmailVerifyRequest
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmailVerifyRequest
     */
    code?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmailVerifyRequest
     */
    password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmailVerifyRequest
     */
    referralCode?: string | null;
}

/**
 * Check if a given object implements the EmailVerifyRequest interface.
 */
export function instanceOfEmailVerifyRequest(value: object): value is EmailVerifyRequest {
    return true;
}

export function EmailVerifyRequestFromJSON(json: any): EmailVerifyRequest {
    return EmailVerifyRequestFromJSONTyped(json, false);
}

export function EmailVerifyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailVerifyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'code': json['code'] == null ? undefined : json['code'],
        'password': json['password'] == null ? undefined : json['password'],
        'referralCode': json['referralCode'] == null ? undefined : json['referralCode'],
    };
}

export function EmailVerifyRequestToJSON(value?: EmailVerifyRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'code': value['code'],
        'password': value['password'],
        'referralCode': value['referralCode'],
    };
}

