/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailLoginRequest
 */
export interface EmailLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof EmailLoginRequest
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmailLoginRequest
     */
    password?: string | null;
}

/**
 * Check if a given object implements the EmailLoginRequest interface.
 */
export function instanceOfEmailLoginRequest(value: object): value is EmailLoginRequest {
    return true;
}

export function EmailLoginRequestFromJSON(json: any): EmailLoginRequest {
    return EmailLoginRequestFromJSONTyped(json, false);
}

export function EmailLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailLoginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function EmailLoginRequestToJSON(value?: EmailLoginRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

