/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailRegisterRequest
 */
export interface EmailRegisterRequest {
    /**
     * 
     * @type {string}
     * @memberof EmailRegisterRequest
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmailRegisterRequest
     */
    password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmailRegisterRequest
     */
    referralCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmailRegisterRequest
     */
    turnstileToken?: string | null;
}

/**
 * Check if a given object implements the EmailRegisterRequest interface.
 */
export function instanceOfEmailRegisterRequest(value: object): value is EmailRegisterRequest {
    return true;
}

export function EmailRegisterRequestFromJSON(json: any): EmailRegisterRequest {
    return EmailRegisterRequestFromJSONTyped(json, false);
}

export function EmailRegisterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailRegisterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'referralCode': json['referralCode'] == null ? undefined : json['referralCode'],
        'turnstileToken': json['turnstileToken'] == null ? undefined : json['turnstileToken'],
    };
}

export function EmailRegisterRequestToJSON(value?: EmailRegisterRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'password': value['password'],
        'referralCode': value['referralCode'],
        'turnstileToken': value['turnstileToken'],
    };
}

