/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';
import type { BondInstrument } from './BondInstrument';
import {
    BondInstrumentFromJSON,
    BondInstrumentFromJSONTyped,
    BondInstrumentToJSON,
} from './BondInstrument';

/**
 * 
 * @export
 * @interface FavoriteBond
 */
export interface FavoriteBond {
    /**
     * 
     * @type {string}
     * @memberof FavoriteBond
     */
    userId?: string;
    /**
     * 
     * @type {User}
     * @memberof FavoriteBond
     */
    user?: User;
    /**
     * 
     * @type {string}
     * @memberof FavoriteBond
     */
    bondId?: string;
    /**
     * 
     * @type {BondInstrument}
     * @memberof FavoriteBond
     */
    bond?: BondInstrument;
}

/**
 * Check if a given object implements the FavoriteBond interface.
 */
export function instanceOfFavoriteBond(value: object): value is FavoriteBond {
    return true;
}

export function FavoriteBondFromJSON(json: any): FavoriteBond {
    return FavoriteBondFromJSONTyped(json, false);
}

export function FavoriteBondFromJSONTyped(json: any, ignoreDiscriminator: boolean): FavoriteBond {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'user': json['user'] == null ? undefined : UserFromJSON(json['user']),
        'bondId': json['bondId'] == null ? undefined : json['bondId'],
        'bond': json['bond'] == null ? undefined : BondInstrumentFromJSON(json['bond']),
    };
}

export function FavoriteBondToJSON(value?: FavoriteBond | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
        'user': UserToJSON(value['user']),
        'bondId': value['bondId'],
        'bond': BondInstrumentToJSON(value['bond']),
    };
}

