/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialReport } from './FinancialReport';
import {
    FinancialReportFromJSON,
    FinancialReportFromJSONTyped,
    FinancialReportToJSON,
} from './FinancialReport';

/**
 * 
 * @export
 * @interface FinancialReportsDto
 */
export interface FinancialReportsDto {
    /**
     * 
     * @type {Array<FinancialReport>}
     * @memberof FinancialReportsDto
     */
    financialReports?: Array<FinancialReport> | null;
}

/**
 * Check if a given object implements the FinancialReportsDto interface.
 */
export function instanceOfFinancialReportsDto(value: object): value is FinancialReportsDto {
    return true;
}

export function FinancialReportsDtoFromJSON(json: any): FinancialReportsDto {
    return FinancialReportsDtoFromJSONTyped(json, false);
}

export function FinancialReportsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialReportsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'financialReports': json['financialReports'] == null ? undefined : ((json['financialReports'] as Array<any>).map(FinancialReportFromJSON)),
    };
}

export function FinancialReportsDtoToJSON(value?: FinancialReportsDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'financialReports': value['financialReports'] == null ? undefined : ((value['financialReports'] as Array<any>).map(FinancialReportToJSON)),
    };
}

