/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BrandBusiness } from './BrandBusiness';
import {
    BrandBusinessFromJSON,
    BrandBusinessFromJSONTyped,
    BrandBusinessToJSON,
} from './BrandBusiness';
import type { SectorMetricsSet } from './SectorMetricsSet';
import {
    SectorMetricsSetFromJSON,
    SectorMetricsSetFromJSONTyped,
    SectorMetricsSetToJSON,
} from './SectorMetricsSet';
import type { ReportStandard } from './ReportStandard';
import {
    ReportStandardFromJSON,
    ReportStandardFromJSONTyped,
    ReportStandardToJSON,
} from './ReportStandard';
import type { ReportCurrency } from './ReportCurrency';
import {
    ReportCurrencyFromJSON,
    ReportCurrencyFromJSONTyped,
    ReportCurrencyToJSON,
} from './ReportCurrency';

/**
 * 
 * @export
 * @interface FinancialReport
 */
export interface FinancialReport {
    /**
     * 
     * @type {string}
     * @memberof FinancialReport
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof FinancialReport
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FinancialReport
     */
    docType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FinancialReport
     */
    fileUrl?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof FinancialReport
     */
    createdAt?: Date;
    /**
     * 
     * @type {ReportStandard}
     * @memberof FinancialReport
     */
    standard?: ReportStandard;
    /**
     * 
     * @type {Date}
     * @memberof FinancialReport
     */
    reportDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof FinancialReport
     */
    reportPeriodMonths?: number;
    /**
     * 
     * @type {number}
     * @memberof FinancialReport
     */
    units?: number;
    /**
     * 
     * @type {ReportCurrency}
     * @memberof FinancialReport
     */
    currency?: ReportCurrency;
    /**
     * 
     * @type {string}
     * @memberof FinancialReport
     */
    issuerInn?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FinancialReport
     */
    brandBusinessId?: string | null;
    /**
     * 
     * @type {BrandBusiness}
     * @memberof FinancialReport
     */
    brandBusiness?: BrandBusiness;
    /**
     * 
     * @type {number}
     * @memberof FinancialReport
     */
    netProfit?: number | null;
    /**
     * 
     * @type {number}
     * @memberof FinancialReport
     */
    netProfitPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof FinancialReport
     */
    totalAssets?: number | null;
    /**
     * 
     * @type {number}
     * @memberof FinancialReport
     */
    totalAssetsPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof FinancialReport
     */
    totalEquity?: number | null;
    /**
     * 
     * @type {number}
     * @memberof FinancialReport
     */
    totalEquityPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof FinancialReport
     */
    cashAndEquivalents?: number | null;
    /**
     * 
     * @type {number}
     * @memberof FinancialReport
     */
    cashAndEquivalentsPrev?: number | null;
    /**
     * 
     * @type {SectorMetricsSet}
     * @memberof FinancialReport
     */
    sectorMetrics?: SectorMetricsSet;
}

/**
 * Check if a given object implements the FinancialReport interface.
 */
export function instanceOfFinancialReport(value: object): value is FinancialReport {
    return true;
}

export function FinancialReportFromJSON(json: any): FinancialReport {
    return FinancialReportFromJSONTyped(json, false);
}

export function FinancialReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialReport {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'docType': json['docType'] == null ? undefined : json['docType'],
        'fileUrl': json['fileUrl'] == null ? undefined : json['fileUrl'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'standard': json['standard'] == null ? undefined : ReportStandardFromJSON(json['standard']),
        'reportDate': json['reportDate'] == null ? undefined : (new Date(json['reportDate'])),
        'reportPeriodMonths': json['reportPeriodMonths'] == null ? undefined : json['reportPeriodMonths'],
        'units': json['units'] == null ? undefined : json['units'],
        'currency': json['currency'] == null ? undefined : ReportCurrencyFromJSON(json['currency']),
        'issuerInn': json['issuerInn'] == null ? undefined : json['issuerInn'],
        'brandBusinessId': json['brandBusinessId'] == null ? undefined : json['brandBusinessId'],
        'brandBusiness': json['brandBusiness'] == null ? undefined : BrandBusinessFromJSON(json['brandBusiness']),
        'netProfit': json['netProfit'] == null ? undefined : json['netProfit'],
        'netProfitPrev': json['netProfitPrev'] == null ? undefined : json['netProfitPrev'],
        'totalAssets': json['totalAssets'] == null ? undefined : json['totalAssets'],
        'totalAssetsPrev': json['totalAssetsPrev'] == null ? undefined : json['totalAssetsPrev'],
        'totalEquity': json['totalEquity'] == null ? undefined : json['totalEquity'],
        'totalEquityPrev': json['totalEquityPrev'] == null ? undefined : json['totalEquityPrev'],
        'cashAndEquivalents': json['cashAndEquivalents'] == null ? undefined : json['cashAndEquivalents'],
        'cashAndEquivalentsPrev': json['cashAndEquivalentsPrev'] == null ? undefined : json['cashAndEquivalentsPrev'],
        'sectorMetrics': json['sectorMetrics'] == null ? undefined : SectorMetricsSetFromJSON(json['sectorMetrics']),
    };
}

export function FinancialReportToJSON(value?: FinancialReport | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'title': value['title'],
        'docType': value['docType'],
        'fileUrl': value['fileUrl'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'standard': ReportStandardToJSON(value['standard']),
        'reportDate': value['reportDate'] == null ? undefined : ((value['reportDate']).toISOString()),
        'reportPeriodMonths': value['reportPeriodMonths'],
        'units': value['units'],
        'currency': ReportCurrencyToJSON(value['currency']),
        'issuerInn': value['issuerInn'],
        'brandBusinessId': value['brandBusinessId'],
        'brandBusiness': BrandBusinessToJSON(value['brandBusiness']),
        'netProfit': value['netProfit'],
        'netProfitPrev': value['netProfitPrev'],
        'totalAssets': value['totalAssets'],
        'totalAssetsPrev': value['totalAssetsPrev'],
        'totalEquity': value['totalEquity'],
        'totalEquityPrev': value['totalEquityPrev'],
        'cashAndEquivalents': value['cashAndEquivalents'],
        'cashAndEquivalentsPrev': value['cashAndEquivalentsPrev'],
        'sectorMetrics': SectorMetricsSetToJSON(value['sectorMetrics']),
    };
}

