/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FinancialMetricResponse
 */
export interface FinancialMetricResponse {
    /**
     * 
     * @type {string}
     * @memberof FinancialMetricResponse
     */
    key?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FinancialMetricResponse
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FinancialMetricResponse
     */
    value?: number | null;
    /**
     * 
     * @type {number}
     * @memberof FinancialMetricResponse
     */
    previousValue?: number | null;
    /**
     * 
     * @type {string}
     * @memberof FinancialMetricResponse
     */
    zone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FinancialMetricResponse
     */
    priority?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof FinancialMetricResponse
     */
    isRelative?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FinancialMetricResponse
     */
    isPercentage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FinancialMetricResponse
     */
    isLtm?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FinancialMetricResponse
     */
    isReversed?: boolean;
}

/**
 * Check if a given object implements the FinancialMetricResponse interface.
 */
export function instanceOfFinancialMetricResponse(value: object): value is FinancialMetricResponse {
    return true;
}

export function FinancialMetricResponseFromJSON(json: any): FinancialMetricResponse {
    return FinancialMetricResponseFromJSONTyped(json, false);
}

export function FinancialMetricResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinancialMetricResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'name': json['name'] == null ? undefined : json['name'],
        'value': json['value'] == null ? undefined : json['value'],
        'previousValue': json['previousValue'] == null ? undefined : json['previousValue'],
        'zone': json['zone'] == null ? undefined : json['zone'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'isRelative': json['isRelative'] == null ? undefined : json['isRelative'],
        'isPercentage': json['isPercentage'] == null ? undefined : json['isPercentage'],
        'isLtm': json['isLtm'] == null ? undefined : json['isLtm'],
        'isReversed': json['isReversed'] == null ? undefined : json['isReversed'],
    };
}

export function FinancialMetricResponseToJSON(value?: FinancialMetricResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'key': value['key'],
        'name': value['name'],
        'value': value['value'],
        'previousValue': value['previousValue'],
        'zone': value['zone'],
        'priority': value['priority'],
        'isRelative': value['isRelative'],
        'isPercentage': value['isPercentage'],
        'isLtm': value['isLtm'],
        'isReversed': value['isReversed'],
    };
}

