/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Flags = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type Flags = typeof Flags[keyof typeof Flags];


export function instanceOfFlags(value: any): boolean {
    for (const key in Flags) {
        if (Object.prototype.hasOwnProperty.call(Flags, key)) {
            if ((Flags as Record<string, Flags>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FlagsFromJSON(json: any): Flags {
    return FlagsFromJSONTyped(json, false);
}

export function FlagsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Flags {
    return json as Flags;
}

export function FlagsToJSON(value?: Flags | null): any {
    return value as any;
}

