/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LlmReportResponseDto } from './LlmReportResponseDto';
import {
    LlmReportResponseDtoFromJSON,
    LlmReportResponseDtoFromJSONTyped,
    LlmReportResponseDtoToJSON,
} from './LlmReportResponseDto';

/**
 * 
 * @export
 * @interface IngestLlmReportRequest
 */
export interface IngestLlmReportRequest {
    /**
     * 
     * @type {LlmReportResponseDto}
     * @memberof IngestLlmReportRequest
     */
    metrics?: LlmReportResponseDto;
    /**
     * 
     * @type {string}
     * @memberof IngestLlmReportRequest
     */
    manualIssuerInn?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IngestLlmReportRequest
     */
    targetBrandId?: string | null;
}

/**
 * Check if a given object implements the IngestLlmReportRequest interface.
 */
export function instanceOfIngestLlmReportRequest(value: object): value is IngestLlmReportRequest {
    return true;
}

export function IngestLlmReportRequestFromJSON(json: any): IngestLlmReportRequest {
    return IngestLlmReportRequestFromJSONTyped(json, false);
}

export function IngestLlmReportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngestLlmReportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'metrics': json['metrics'] == null ? undefined : LlmReportResponseDtoFromJSON(json['metrics']),
        'manualIssuerInn': json['manualIssuerInn'] == null ? undefined : json['manualIssuerInn'],
        'targetBrandId': json['targetBrandId'] == null ? undefined : json['targetBrandId'],
    };
}

export function IngestLlmReportRequestToJSON(value?: IngestLlmReportRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'metrics': LlmReportResponseDtoToJSON(value['metrics']),
        'manualIssuerInn': value['manualIssuerInn'],
        'targetBrandId': value['targetBrandId'],
    };
}

