/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckingState } from './CheckingState';
import {
    CheckingStateFromJSON,
    CheckingStateFromJSONTyped,
    CheckingStateToJSON,
} from './CheckingState';
import type { BrandBusiness } from './BrandBusiness';
import {
    BrandBusinessFromJSON,
    BrandBusinessFromJSONTyped,
    BrandBusinessToJSON,
} from './BrandBusiness';
import type { ProcessingState } from './ProcessingState';
import {
    ProcessingStateFromJSON,
    ProcessingStateFromJSONTyped,
    ProcessingStateToJSON,
} from './ProcessingState';

/**
 * 
 * @export
 * @interface Job
 */
export interface Job {
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    userId?: string | null;
    /**
     * 
     * @type {ProcessingState}
     * @memberof Job
     */
    processingState?: ProcessingState;
    /**
     * 
     * @type {CheckingState}
     * @memberof Job
     */
    checkingState?: CheckingState;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    brandBusinessId?: string | null;
    /**
     * 
     * @type {BrandBusiness}
     * @memberof Job
     */
    brandBusiness?: BrandBusiness;
    /**
     * 
     * @type {Date}
     * @memberof Job
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Job
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    fileName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    fileUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    jobName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    operatingProfit?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    amortization?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    longTermDebt?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    shortTermDebt?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    totalCurrentLiabilities?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    cashAndEquivalents?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    operationCashFlow?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    totalEquity?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    totalAssets?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    interestExpense?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    revenue?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    netProfit?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    currentAssets?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    inventory?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    operatingProfitPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    amortizationPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    operationCashFlowPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    interestExpensePrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    revenuePrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    netProfitPrev?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    ltmCalculationLog?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    detectedDocType?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Job
     */
    readonly ebitdaLtmMultiplier?: number;
}

/**
 * Check if a given object implements the Job interface.
 */
export function instanceOfJob(value: object): value is Job {
    return true;
}

export function JobFromJSON(json: any): Job {
    return JobFromJSONTyped(json, false);
}

export function JobFromJSONTyped(json: any, ignoreDiscriminator: boolean): Job {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'processingState': json['processingState'] == null ? undefined : ProcessingStateFromJSON(json['processingState']),
        'checkingState': json['checkingState'] == null ? undefined : CheckingStateFromJSON(json['checkingState']),
        'brandBusinessId': json['brandBusinessId'] == null ? undefined : json['brandBusinessId'],
        'brandBusiness': json['brandBusiness'] == null ? undefined : BrandBusinessFromJSON(json['brandBusiness']),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'fileUrl': json['fileUrl'] == null ? undefined : json['fileUrl'],
        'jobName': json['jobName'] == null ? undefined : json['jobName'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
        'operatingProfit': json['operatingProfit'] == null ? undefined : json['operatingProfit'],
        'amortization': json['amortization'] == null ? undefined : json['amortization'],
        'longTermDebt': json['longTermDebt'] == null ? undefined : json['longTermDebt'],
        'shortTermDebt': json['shortTermDebt'] == null ? undefined : json['shortTermDebt'],
        'totalCurrentLiabilities': json['totalCurrentLiabilities'] == null ? undefined : json['totalCurrentLiabilities'],
        'cashAndEquivalents': json['cashAndEquivalents'] == null ? undefined : json['cashAndEquivalents'],
        'operationCashFlow': json['operationCashFlow'] == null ? undefined : json['operationCashFlow'],
        'totalEquity': json['totalEquity'] == null ? undefined : json['totalEquity'],
        'totalAssets': json['totalAssets'] == null ? undefined : json['totalAssets'],
        'interestExpense': json['interestExpense'] == null ? undefined : json['interestExpense'],
        'revenue': json['revenue'] == null ? undefined : json['revenue'],
        'netProfit': json['netProfit'] == null ? undefined : json['netProfit'],
        'currentAssets': json['currentAssets'] == null ? undefined : json['currentAssets'],
        'inventory': json['inventory'] == null ? undefined : json['inventory'],
        'operatingProfitPrev': json['operatingProfitPrev'] == null ? undefined : json['operatingProfitPrev'],
        'amortizationPrev': json['amortizationPrev'] == null ? undefined : json['amortizationPrev'],
        'operationCashFlowPrev': json['operationCashFlowPrev'] == null ? undefined : json['operationCashFlowPrev'],
        'interestExpensePrev': json['interestExpensePrev'] == null ? undefined : json['interestExpensePrev'],
        'revenuePrev': json['revenuePrev'] == null ? undefined : json['revenuePrev'],
        'netProfitPrev': json['netProfitPrev'] == null ? undefined : json['netProfitPrev'],
        'ltmCalculationLog': json['ltmCalculationLog'] == null ? undefined : json['ltmCalculationLog'],
        'detectedDocType': json['detectedDocType'] == null ? undefined : json['detectedDocType'],
        'ebitdaLtmMultiplier': json['ebitdaLtmMultiplier'] == null ? undefined : json['ebitdaLtmMultiplier'],
    };
}

export function JobToJSON(value?: Omit<Job, 'ebitdaLtmMultiplier'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'processingState': ProcessingStateToJSON(value['processingState']),
        'checkingState': CheckingStateToJSON(value['checkingState']),
        'brandBusinessId': value['brandBusinessId'],
        'brandBusiness': BrandBusinessToJSON(value['brandBusiness']),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt'] as any).toISOString()),
        'fileName': value['fileName'],
        'fileUrl': value['fileUrl'],
        'jobName': value['jobName'],
        'errorMessage': value['errorMessage'],
        'operatingProfit': value['operatingProfit'],
        'amortization': value['amortization'],
        'longTermDebt': value['longTermDebt'],
        'shortTermDebt': value['shortTermDebt'],
        'totalCurrentLiabilities': value['totalCurrentLiabilities'],
        'cashAndEquivalents': value['cashAndEquivalents'],
        'operationCashFlow': value['operationCashFlow'],
        'totalEquity': value['totalEquity'],
        'totalAssets': value['totalAssets'],
        'interestExpense': value['interestExpense'],
        'revenue': value['revenue'],
        'netProfit': value['netProfit'],
        'currentAssets': value['currentAssets'],
        'inventory': value['inventory'],
        'operatingProfitPrev': value['operatingProfitPrev'],
        'amortizationPrev': value['amortizationPrev'],
        'operationCashFlowPrev': value['operationCashFlowPrev'],
        'interestExpensePrev': value['interestExpensePrev'],
        'revenuePrev': value['revenuePrev'],
        'netProfitPrev': value['netProfitPrev'],
        'ltmCalculationLog': value['ltmCalculationLog'],
        'detectedDocType': value['detectedDocType'],
    };
}

