/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Job } from './Job';
import {
    JobFromJSON,
    JobFromJSONTyped,
    JobToJSON,
} from './Job';

/**
 * 
 * @export
 * @interface JobPagedResponse
 */
export interface JobPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof JobPagedResponse
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof JobPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof JobPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {Array<Job>}
     * @memberof JobPagedResponse
     */
    jobs?: Array<Job> | null;
}

/**
 * Check if a given object implements the JobPagedResponse interface.
 */
export function instanceOfJobPagedResponse(value: object): value is JobPagedResponse {
    return true;
}

export function JobPagedResponseFromJSON(json: any): JobPagedResponse {
    return JobPagedResponseFromJSONTyped(json, false);
}

export function JobPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'jobs': json['jobs'] == null ? undefined : ((json['jobs'] as Array<any>).map(JobFromJSON)),
    };
}

export function JobPagedResponseToJSON(value?: JobPagedResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'jobs': value['jobs'] == null ? undefined : ((value['jobs'] as Array<any>).map(JobToJSON)),
    };
}

