/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobReviewResult
 */
export interface JobReviewResult {
    /**
     * 
     * @type {string}
     * @memberof JobReviewResult
     */
    status?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobReviewResult
     */
    brandId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof JobReviewResult
     */
    appliedToBrand?: boolean;
}

/**
 * Check if a given object implements the JobReviewResult interface.
 */
export function instanceOfJobReviewResult(value: object): value is JobReviewResult {
    return true;
}

export function JobReviewResultFromJSON(json: any): JobReviewResult {
    return JobReviewResultFromJSONTyped(json, false);
}

export function JobReviewResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobReviewResult {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'brandId': json['brandId'] == null ? undefined : json['brandId'],
        'appliedToBrand': json['appliedToBrand'] == null ? undefined : json['appliedToBrand'],
    };
}

export function JobReviewResultToJSON(value?: JobReviewResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'brandId': value['brandId'],
        'appliedToBrand': value['appliedToBrand'],
    };
}

