/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobUploadResponse
 */
export interface JobUploadResponse {
    /**
     * 
     * @type {string}
     * @memberof JobUploadResponse
     */
    jobId?: string;
}

/**
 * Check if a given object implements the JobUploadResponse interface.
 */
export function instanceOfJobUploadResponse(value: object): value is JobUploadResponse {
    return true;
}

export function JobUploadResponseFromJSON(json: any): JobUploadResponse {
    return JobUploadResponseFromJSONTyped(json, false);
}

export function JobUploadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobUploadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['jobId'] == null ? undefined : json['jobId'],
    };
}

export function JobUploadResponseToJSON(value?: JobUploadResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jobId': value['jobId'],
    };
}

