/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LlmBankingMetricsDto
 */
export interface LlmBankingMetricsDto {
    /**
     * 
     * @type {number}
     * @memberof LlmBankingMetricsDto
     */
    netInterestIncome?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBankingMetricsDto
     */
    netInterestIncomePrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBankingMetricsDto
     */
    netFeeAndCommissionIncome?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBankingMetricsDto
     */
    netFeeAndCommissionIncomePrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBankingMetricsDto
     */
    customerAccounts?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBankingMetricsDto
     */
    customerAccountsPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBankingMetricsDto
     */
    loanPortfolio?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBankingMetricsDto
     */
    loanPortfolioPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBankingMetricsDto
     */
    netInterestMargin?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBankingMetricsDto
     */
    netInterestMarginPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBankingMetricsDto
     */
    returnOnEquity?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBankingMetricsDto
     */
    returnOnEquityPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBankingMetricsDto
     */
    tier1CapitalRatio?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBankingMetricsDto
     */
    tier1CapitalRatioPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBankingMetricsDto
     */
    costOfRisk?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBankingMetricsDto
     */
    costOfRiskPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBankingMetricsDto
     */
    nonPerformingLoans?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBankingMetricsDto
     */
    nonPerformingLoansPrev?: number | null;
}

/**
 * Check if a given object implements the LlmBankingMetricsDto interface.
 */
export function instanceOfLlmBankingMetricsDto(value: object): value is LlmBankingMetricsDto {
    return true;
}

export function LlmBankingMetricsDtoFromJSON(json: any): LlmBankingMetricsDto {
    return LlmBankingMetricsDtoFromJSONTyped(json, false);
}

export function LlmBankingMetricsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LlmBankingMetricsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'netInterestIncome': json['netInterestIncome'] == null ? undefined : json['netInterestIncome'],
        'netInterestIncomePrev': json['netInterestIncomePrev'] == null ? undefined : json['netInterestIncomePrev'],
        'netFeeAndCommissionIncome': json['netFeeAndCommissionIncome'] == null ? undefined : json['netFeeAndCommissionIncome'],
        'netFeeAndCommissionIncomePrev': json['netFeeAndCommissionIncomePrev'] == null ? undefined : json['netFeeAndCommissionIncomePrev'],
        'customerAccounts': json['customerAccounts'] == null ? undefined : json['customerAccounts'],
        'customerAccountsPrev': json['customerAccountsPrev'] == null ? undefined : json['customerAccountsPrev'],
        'loanPortfolio': json['loanPortfolio'] == null ? undefined : json['loanPortfolio'],
        'loanPortfolioPrev': json['loanPortfolioPrev'] == null ? undefined : json['loanPortfolioPrev'],
        'netInterestMargin': json['netInterestMargin'] == null ? undefined : json['netInterestMargin'],
        'netInterestMarginPrev': json['netInterestMarginPrev'] == null ? undefined : json['netInterestMarginPrev'],
        'returnOnEquity': json['returnOnEquity'] == null ? undefined : json['returnOnEquity'],
        'returnOnEquityPrev': json['returnOnEquityPrev'] == null ? undefined : json['returnOnEquityPrev'],
        'tier1CapitalRatio': json['tier1CapitalRatio'] == null ? undefined : json['tier1CapitalRatio'],
        'tier1CapitalRatioPrev': json['tier1CapitalRatioPrev'] == null ? undefined : json['tier1CapitalRatioPrev'],
        'costOfRisk': json['costOfRisk'] == null ? undefined : json['costOfRisk'],
        'costOfRiskPrev': json['costOfRiskPrev'] == null ? undefined : json['costOfRiskPrev'],
        'nonPerformingLoans': json['nonPerformingLoans'] == null ? undefined : json['nonPerformingLoans'],
        'nonPerformingLoansPrev': json['nonPerformingLoansPrev'] == null ? undefined : json['nonPerformingLoansPrev'],
    };
}

export function LlmBankingMetricsDtoToJSON(value?: LlmBankingMetricsDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'netInterestIncome': value['netInterestIncome'],
        'netInterestIncomePrev': value['netInterestIncomePrev'],
        'netFeeAndCommissionIncome': value['netFeeAndCommissionIncome'],
        'netFeeAndCommissionIncomePrev': value['netFeeAndCommissionIncomePrev'],
        'customerAccounts': value['customerAccounts'],
        'customerAccountsPrev': value['customerAccountsPrev'],
        'loanPortfolio': value['loanPortfolio'],
        'loanPortfolioPrev': value['loanPortfolioPrev'],
        'netInterestMargin': value['netInterestMargin'],
        'netInterestMarginPrev': value['netInterestMarginPrev'],
        'returnOnEquity': value['returnOnEquity'],
        'returnOnEquityPrev': value['returnOnEquityPrev'],
        'tier1CapitalRatio': value['tier1CapitalRatio'],
        'tier1CapitalRatioPrev': value['tier1CapitalRatioPrev'],
        'costOfRisk': value['costOfRisk'],
        'costOfRiskPrev': value['costOfRiskPrev'],
        'nonPerformingLoans': value['nonPerformingLoans'],
        'nonPerformingLoansPrev': value['nonPerformingLoansPrev'],
    };
}

