/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LlmBaseMetricsDto
 */
export interface LlmBaseMetricsDto {
    /**
     * 
     * @type {number}
     * @memberof LlmBaseMetricsDto
     */
    netProfit?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBaseMetricsDto
     */
    netProfitPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBaseMetricsDto
     */
    totalAssets?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBaseMetricsDto
     */
    totalAssetsPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBaseMetricsDto
     */
    totalEquity?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBaseMetricsDto
     */
    totalEquityPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBaseMetricsDto
     */
    cashAndEquivalents?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmBaseMetricsDto
     */
    cashAndEquivalentsPrev?: number | null;
}

/**
 * Check if a given object implements the LlmBaseMetricsDto interface.
 */
export function instanceOfLlmBaseMetricsDto(value: object): value is LlmBaseMetricsDto {
    return true;
}

export function LlmBaseMetricsDtoFromJSON(json: any): LlmBaseMetricsDto {
    return LlmBaseMetricsDtoFromJSONTyped(json, false);
}

export function LlmBaseMetricsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LlmBaseMetricsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'netProfit': json['netProfit'] == null ? undefined : json['netProfit'],
        'netProfitPrev': json['netProfitPrev'] == null ? undefined : json['netProfitPrev'],
        'totalAssets': json['totalAssets'] == null ? undefined : json['totalAssets'],
        'totalAssetsPrev': json['totalAssetsPrev'] == null ? undefined : json['totalAssetsPrev'],
        'totalEquity': json['totalEquity'] == null ? undefined : json['totalEquity'],
        'totalEquityPrev': json['totalEquityPrev'] == null ? undefined : json['totalEquityPrev'],
        'cashAndEquivalents': json['cashAndEquivalents'] == null ? undefined : json['cashAndEquivalents'],
        'cashAndEquivalentsPrev': json['cashAndEquivalentsPrev'] == null ? undefined : json['cashAndEquivalentsPrev'],
    };
}

export function LlmBaseMetricsDtoToJSON(value?: LlmBaseMetricsDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'netProfit': value['netProfit'],
        'netProfitPrev': value['netProfitPrev'],
        'totalAssets': value['totalAssets'],
        'totalAssetsPrev': value['totalAssetsPrev'],
        'totalEquity': value['totalEquity'],
        'totalEquityPrev': value['totalEquityPrev'],
        'cashAndEquivalents': value['cashAndEquivalents'],
        'cashAndEquivalentsPrev': value['cashAndEquivalentsPrev'],
    };
}

