/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LlmCorporateMetricsDto
 */
export interface LlmCorporateMetricsDto {
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    revenue?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    revenuePrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    ebitda?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    ebitdaPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    operatingProfit?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    operatingProfitPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    interestExpense?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    interestExpensePrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    totalDebt?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    totalDebtPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    shortTermDebt?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    shortTermDebtPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    operationCashFlow?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    operationCashFlowPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    freeCashFlow?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    freeCashFlowPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    netDebtToEbitda?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    netDebtToEbitdaPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    totalDebtToEquity?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    totalDebtToEquityPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    currentLiquidity?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    currentLiquidityPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    interestCoverageRatio?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    interestCoverageRatioPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    operatingCashFlowToTotalDebt?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    operatingCashFlowToTotalDebtPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    ebitdaMargin?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    ebitdaMarginPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    netProfitMargin?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmCorporateMetricsDto
     */
    netProfitMarginPrev?: number | null;
}

/**
 * Check if a given object implements the LlmCorporateMetricsDto interface.
 */
export function instanceOfLlmCorporateMetricsDto(value: object): value is LlmCorporateMetricsDto {
    return true;
}

export function LlmCorporateMetricsDtoFromJSON(json: any): LlmCorporateMetricsDto {
    return LlmCorporateMetricsDtoFromJSONTyped(json, false);
}

export function LlmCorporateMetricsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LlmCorporateMetricsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'revenue': json['revenue'] == null ? undefined : json['revenue'],
        'revenuePrev': json['revenuePrev'] == null ? undefined : json['revenuePrev'],
        'ebitda': json['ebitda'] == null ? undefined : json['ebitda'],
        'ebitdaPrev': json['ebitdaPrev'] == null ? undefined : json['ebitdaPrev'],
        'operatingProfit': json['operatingProfit'] == null ? undefined : json['operatingProfit'],
        'operatingProfitPrev': json['operatingProfitPrev'] == null ? undefined : json['operatingProfitPrev'],
        'interestExpense': json['interestExpense'] == null ? undefined : json['interestExpense'],
        'interestExpensePrev': json['interestExpensePrev'] == null ? undefined : json['interestExpensePrev'],
        'totalDebt': json['totalDebt'] == null ? undefined : json['totalDebt'],
        'totalDebtPrev': json['totalDebtPrev'] == null ? undefined : json['totalDebtPrev'],
        'shortTermDebt': json['shortTermDebt'] == null ? undefined : json['shortTermDebt'],
        'shortTermDebtPrev': json['shortTermDebtPrev'] == null ? undefined : json['shortTermDebtPrev'],
        'operationCashFlow': json['operationCashFlow'] == null ? undefined : json['operationCashFlow'],
        'operationCashFlowPrev': json['operationCashFlowPrev'] == null ? undefined : json['operationCashFlowPrev'],
        'freeCashFlow': json['freeCashFlow'] == null ? undefined : json['freeCashFlow'],
        'freeCashFlowPrev': json['freeCashFlowPrev'] == null ? undefined : json['freeCashFlowPrev'],
        'netDebtToEbitda': json['netDebtToEbitda'] == null ? undefined : json['netDebtToEbitda'],
        'netDebtToEbitdaPrev': json['netDebtToEbitdaPrev'] == null ? undefined : json['netDebtToEbitdaPrev'],
        'totalDebtToEquity': json['totalDebtToEquity'] == null ? undefined : json['totalDebtToEquity'],
        'totalDebtToEquityPrev': json['totalDebtToEquityPrev'] == null ? undefined : json['totalDebtToEquityPrev'],
        'currentLiquidity': json['currentLiquidity'] == null ? undefined : json['currentLiquidity'],
        'currentLiquidityPrev': json['currentLiquidityPrev'] == null ? undefined : json['currentLiquidityPrev'],
        'interestCoverageRatio': json['interestCoverageRatio'] == null ? undefined : json['interestCoverageRatio'],
        'interestCoverageRatioPrev': json['interestCoverageRatioPrev'] == null ? undefined : json['interestCoverageRatioPrev'],
        'operatingCashFlowToTotalDebt': json['operatingCashFlowToTotalDebt'] == null ? undefined : json['operatingCashFlowToTotalDebt'],
        'operatingCashFlowToTotalDebtPrev': json['operatingCashFlowToTotalDebtPrev'] == null ? undefined : json['operatingCashFlowToTotalDebtPrev'],
        'ebitdaMargin': json['ebitdaMargin'] == null ? undefined : json['ebitdaMargin'],
        'ebitdaMarginPrev': json['ebitdaMarginPrev'] == null ? undefined : json['ebitdaMarginPrev'],
        'netProfitMargin': json['netProfitMargin'] == null ? undefined : json['netProfitMargin'],
        'netProfitMarginPrev': json['netProfitMarginPrev'] == null ? undefined : json['netProfitMarginPrev'],
    };
}

export function LlmCorporateMetricsDtoToJSON(value?: LlmCorporateMetricsDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'revenue': value['revenue'],
        'revenuePrev': value['revenuePrev'],
        'ebitda': value['ebitda'],
        'ebitdaPrev': value['ebitdaPrev'],
        'operatingProfit': value['operatingProfit'],
        'operatingProfitPrev': value['operatingProfitPrev'],
        'interestExpense': value['interestExpense'],
        'interestExpensePrev': value['interestExpensePrev'],
        'totalDebt': value['totalDebt'],
        'totalDebtPrev': value['totalDebtPrev'],
        'shortTermDebt': value['shortTermDebt'],
        'shortTermDebtPrev': value['shortTermDebtPrev'],
        'operationCashFlow': value['operationCashFlow'],
        'operationCashFlowPrev': value['operationCashFlowPrev'],
        'freeCashFlow': value['freeCashFlow'],
        'freeCashFlowPrev': value['freeCashFlowPrev'],
        'netDebtToEbitda': value['netDebtToEbitda'],
        'netDebtToEbitdaPrev': value['netDebtToEbitdaPrev'],
        'totalDebtToEquity': value['totalDebtToEquity'],
        'totalDebtToEquityPrev': value['totalDebtToEquityPrev'],
        'currentLiquidity': value['currentLiquidity'],
        'currentLiquidityPrev': value['currentLiquidityPrev'],
        'interestCoverageRatio': value['interestCoverageRatio'],
        'interestCoverageRatioPrev': value['interestCoverageRatioPrev'],
        'operatingCashFlowToTotalDebt': value['operatingCashFlowToTotalDebt'],
        'operatingCashFlowToTotalDebtPrev': value['operatingCashFlowToTotalDebtPrev'],
        'ebitdaMargin': value['ebitdaMargin'],
        'ebitdaMarginPrev': value['ebitdaMarginPrev'],
        'netProfitMargin': value['netProfitMargin'],
        'netProfitMarginPrev': value['netProfitMarginPrev'],
    };
}

