/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LlmLeasingMetricsDto
 */
export interface LlmLeasingMetricsDto {
    /**
     * 
     * @type {number}
     * @memberof LlmLeasingMetricsDto
     */
    netInterestIncome?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmLeasingMetricsDto
     */
    netInterestIncomePrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmLeasingMetricsDto
     */
    netInvestmentInLease?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmLeasingMetricsDto
     */
    netInvestmentInLeasePrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmLeasingMetricsDto
     */
    clientAdvances?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmLeasingMetricsDto
     */
    clientAdvancesPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmLeasingMetricsDto
     */
    debtToEquity?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmLeasingMetricsDto
     */
    debtToEquityPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmLeasingMetricsDto
     */
    interestCoverageRatio?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LlmLeasingMetricsDto
     */
    interestCoverageRatioPrev?: number | null;
}

/**
 * Check if a given object implements the LlmLeasingMetricsDto interface.
 */
export function instanceOfLlmLeasingMetricsDto(value: object): value is LlmLeasingMetricsDto {
    return true;
}

export function LlmLeasingMetricsDtoFromJSON(json: any): LlmLeasingMetricsDto {
    return LlmLeasingMetricsDtoFromJSONTyped(json, false);
}

export function LlmLeasingMetricsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LlmLeasingMetricsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'netInterestIncome': json['netInterestIncome'] == null ? undefined : json['netInterestIncome'],
        'netInterestIncomePrev': json['netInterestIncomePrev'] == null ? undefined : json['netInterestIncomePrev'],
        'netInvestmentInLease': json['netInvestmentInLease'] == null ? undefined : json['netInvestmentInLease'],
        'netInvestmentInLeasePrev': json['netInvestmentInLeasePrev'] == null ? undefined : json['netInvestmentInLeasePrev'],
        'clientAdvances': json['clientAdvances'] == null ? undefined : json['clientAdvances'],
        'clientAdvancesPrev': json['clientAdvancesPrev'] == null ? undefined : json['clientAdvancesPrev'],
        'debtToEquity': json['debtToEquity'] == null ? undefined : json['debtToEquity'],
        'debtToEquityPrev': json['debtToEquityPrev'] == null ? undefined : json['debtToEquityPrev'],
        'interestCoverageRatio': json['interestCoverageRatio'] == null ? undefined : json['interestCoverageRatio'],
        'interestCoverageRatioPrev': json['interestCoverageRatioPrev'] == null ? undefined : json['interestCoverageRatioPrev'],
    };
}

export function LlmLeasingMetricsDtoToJSON(value?: LlmLeasingMetricsDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'netInterestIncome': value['netInterestIncome'],
        'netInterestIncomePrev': value['netInterestIncomePrev'],
        'netInvestmentInLease': value['netInvestmentInLease'],
        'netInvestmentInLeasePrev': value['netInvestmentInLeasePrev'],
        'clientAdvances': value['clientAdvances'],
        'clientAdvancesPrev': value['clientAdvancesPrev'],
        'debtToEquity': value['debtToEquity'],
        'debtToEquityPrev': value['debtToEquityPrev'],
        'interestCoverageRatio': value['interestCoverageRatio'],
        'interestCoverageRatioPrev': value['interestCoverageRatioPrev'],
    };
}

