/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LlmBankingMetricsDto } from './LlmBankingMetricsDto';
import {
    LlmBankingMetricsDtoFromJSON,
    LlmBankingMetricsDtoFromJSONTyped,
    LlmBankingMetricsDtoToJSON,
} from './LlmBankingMetricsDto';
import type { LlmBaseMetricsDto } from './LlmBaseMetricsDto';
import {
    LlmBaseMetricsDtoFromJSON,
    LlmBaseMetricsDtoFromJSONTyped,
    LlmBaseMetricsDtoToJSON,
} from './LlmBaseMetricsDto';
import type { LlmCorporateMetricsDto } from './LlmCorporateMetricsDto';
import {
    LlmCorporateMetricsDtoFromJSON,
    LlmCorporateMetricsDtoFromJSONTyped,
    LlmCorporateMetricsDtoToJSON,
} from './LlmCorporateMetricsDto';
import type { LlmLeasingMetricsDto } from './LlmLeasingMetricsDto';
import {
    LlmLeasingMetricsDtoFromJSON,
    LlmLeasingMetricsDtoFromJSONTyped,
    LlmLeasingMetricsDtoToJSON,
} from './LlmLeasingMetricsDto';
import type { LlmMicrofinanceMetricsDto } from './LlmMicrofinanceMetricsDto';
import {
    LlmMicrofinanceMetricsDtoFromJSON,
    LlmMicrofinanceMetricsDtoFromJSONTyped,
    LlmMicrofinanceMetricsDtoToJSON,
} from './LlmMicrofinanceMetricsDto';
import type { LlmRealEstateMetricsDto } from './LlmRealEstateMetricsDto';
import {
    LlmRealEstateMetricsDtoFromJSON,
    LlmRealEstateMetricsDtoFromJSONTyped,
    LlmRealEstateMetricsDtoToJSON,
} from './LlmRealEstateMetricsDto';

/**
 * 
 * @export
 * @interface LlmReportResponseDto
 */
export interface LlmReportResponseDto {
    /**
     * 
     * @type {string}
     * @memberof LlmReportResponseDto
     */
    reportStandard?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LlmReportResponseDto
     */
    reportDate?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LlmReportResponseDto
     */
    units?: number;
    /**
     * 
     * @type {string}
     * @memberof LlmReportResponseDto
     */
    currency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LlmReportResponseDto
     */
    sector?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LlmReportResponseDto
     */
    subSector?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof LlmReportResponseDto
     */
    isSpv?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LlmReportResponseDto
     */
    guarantorName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LlmReportResponseDto
     */
    guarantorInn?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof LlmReportResponseDto
     */
    isStructuredEntity?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof LlmReportResponseDto
     */
    investmentPros?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof LlmReportResponseDto
     */
    investmentCons?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof LlmReportResponseDto
     */
    keyRisks?: Array<string> | null;
    /**
     * 
     * @type {LlmBaseMetricsDto}
     * @memberof LlmReportResponseDto
     */
    baseMetrics?: LlmBaseMetricsDto;
    /**
     * 
     * @type {LlmCorporateMetricsDto}
     * @memberof LlmReportResponseDto
     */
    corporateMetrics?: LlmCorporateMetricsDto;
    /**
     * 
     * @type {LlmRealEstateMetricsDto}
     * @memberof LlmReportResponseDto
     */
    realEstateMetrics?: LlmRealEstateMetricsDto;
    /**
     * 
     * @type {LlmBankingMetricsDto}
     * @memberof LlmReportResponseDto
     */
    bankingMetrics?: LlmBankingMetricsDto;
    /**
     * 
     * @type {LlmMicrofinanceMetricsDto}
     * @memberof LlmReportResponseDto
     */
    microfinanceMetrics?: LlmMicrofinanceMetricsDto;
    /**
     * 
     * @type {LlmLeasingMetricsDto}
     * @memberof LlmReportResponseDto
     */
    leasingMetrics?: LlmLeasingMetricsDto;
}

/**
 * Check if a given object implements the LlmReportResponseDto interface.
 */
export function instanceOfLlmReportResponseDto(value: object): value is LlmReportResponseDto {
    return true;
}

export function LlmReportResponseDtoFromJSON(json: any): LlmReportResponseDto {
    return LlmReportResponseDtoFromJSONTyped(json, false);
}

export function LlmReportResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LlmReportResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'reportStandard': json['reportStandard'] == null ? undefined : json['reportStandard'],
        'reportDate': json['reportDate'] == null ? undefined : json['reportDate'],
        'units': json['units'] == null ? undefined : json['units'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'sector': json['sector'] == null ? undefined : json['sector'],
        'subSector': json['subSector'] == null ? undefined : json['subSector'],
        'isSpv': json['isSpv'] == null ? undefined : json['isSpv'],
        'guarantorName': json['guarantorName'] == null ? undefined : json['guarantorName'],
        'guarantorInn': json['guarantorInn'] == null ? undefined : json['guarantorInn'],
        'isStructuredEntity': json['isStructuredEntity'] == null ? undefined : json['isStructuredEntity'],
        'investmentPros': json['investmentPros'] == null ? undefined : json['investmentPros'],
        'investmentCons': json['investmentCons'] == null ? undefined : json['investmentCons'],
        'keyRisks': json['keyRisks'] == null ? undefined : json['keyRisks'],
        'baseMetrics': json['baseMetrics'] == null ? undefined : LlmBaseMetricsDtoFromJSON(json['baseMetrics']),
        'corporateMetrics': json['corporateMetrics'] == null ? undefined : LlmCorporateMetricsDtoFromJSON(json['corporateMetrics']),
        'realEstateMetrics': json['realEstateMetrics'] == null ? undefined : LlmRealEstateMetricsDtoFromJSON(json['realEstateMetrics']),
        'bankingMetrics': json['bankingMetrics'] == null ? undefined : LlmBankingMetricsDtoFromJSON(json['bankingMetrics']),
        'microfinanceMetrics': json['microfinanceMetrics'] == null ? undefined : LlmMicrofinanceMetricsDtoFromJSON(json['microfinanceMetrics']),
        'leasingMetrics': json['leasingMetrics'] == null ? undefined : LlmLeasingMetricsDtoFromJSON(json['leasingMetrics']),
    };
}

export function LlmReportResponseDtoToJSON(value?: LlmReportResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'reportStandard': value['reportStandard'],
        'reportDate': value['reportDate'],
        'units': value['units'],
        'currency': value['currency'],
        'sector': value['sector'],
        'subSector': value['subSector'],
        'isSpv': value['isSpv'],
        'guarantorName': value['guarantorName'],
        'guarantorInn': value['guarantorInn'],
        'isStructuredEntity': value['isStructuredEntity'],
        'investmentPros': value['investmentPros'],
        'investmentCons': value['investmentCons'],
        'keyRisks': value['keyRisks'],
        'baseMetrics': LlmBaseMetricsDtoToJSON(value['baseMetrics']),
        'corporateMetrics': LlmCorporateMetricsDtoToJSON(value['corporateMetrics']),
        'realEstateMetrics': LlmRealEstateMetricsDtoToJSON(value['realEstateMetrics']),
        'bankingMetrics': LlmBankingMetricsDtoToJSON(value['bankingMetrics']),
        'microfinanceMetrics': LlmMicrofinanceMetricsDtoToJSON(value['microfinanceMetrics']),
        'leasingMetrics': LlmLeasingMetricsDtoToJSON(value['leasingMetrics']),
    };
}

