/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginProviderRequest
 */
export interface LoginProviderRequest {
    /**
     * 
     * @type {string}
     * @memberof LoginProviderRequest
     */
    provider?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoginProviderRequest
     */
    providerId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoginProviderRequest
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoginProviderRequest
     */
    token?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoginProviderRequest
     */
    referralCode?: string | null;
}

/**
 * Check if a given object implements the LoginProviderRequest interface.
 */
export function instanceOfLoginProviderRequest(value: object): value is LoginProviderRequest {
    return true;
}

export function LoginProviderRequestFromJSON(json: any): LoginProviderRequest {
    return LoginProviderRequestFromJSONTyped(json, false);
}

export function LoginProviderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginProviderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': json['provider'] == null ? undefined : json['provider'],
        'providerId': json['providerId'] == null ? undefined : json['providerId'],
        'email': json['email'] == null ? undefined : json['email'],
        'token': json['token'] == null ? undefined : json['token'],
        'referralCode': json['referralCode'] == null ? undefined : json['referralCode'],
    };
}

export function LoginProviderRequestToJSON(value?: LoginProviderRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'provider': value['provider'],
        'providerId': value['providerId'],
        'email': value['email'],
        'token': value['token'],
        'referralCode': value['referralCode'],
    };
}

