/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MarketMapBondDto
 */
export interface MarketMapBondDto {
    /**
     * 
     * @type {string}
     * @memberof MarketMapBondDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof MarketMapBondDto
     */
    ticker?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MarketMapBondDto
     */
    creditRating?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MarketMapBondDto
     */
    durationYears?: number;
    /**
     * 
     * @type {number}
     * @memberof MarketMapBondDto
     */
    _yield?: number;
    /**
     * 
     * @type {number}
     * @memberof MarketMapBondDto
     */
    gSpread?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof MarketMapBondDto
     */
    isToEvent?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MarketMapBondDto
     */
    eventType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MarketMapBondDto
     */
    issuerName?: string | null;
}

/**
 * Check if a given object implements the MarketMapBondDto interface.
 */
export function instanceOfMarketMapBondDto(value: object): value is MarketMapBondDto {
    return true;
}

export function MarketMapBondDtoFromJSON(json: any): MarketMapBondDto {
    return MarketMapBondDtoFromJSONTyped(json, false);
}

export function MarketMapBondDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketMapBondDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'ticker': json['ticker'] == null ? undefined : json['ticker'],
        'creditRating': json['creditRating'] == null ? undefined : json['creditRating'],
        'durationYears': json['durationYears'] == null ? undefined : json['durationYears'],
        '_yield': json['yield'] == null ? undefined : json['yield'],
        'gSpread': json['gSpread'] == null ? undefined : json['gSpread'],
        'isToEvent': json['isToEvent'] == null ? undefined : json['isToEvent'],
        'eventType': json['eventType'] == null ? undefined : json['eventType'],
        'issuerName': json['issuerName'] == null ? undefined : json['issuerName'],
    };
}

export function MarketMapBondDtoToJSON(value?: MarketMapBondDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'ticker': value['ticker'],
        'creditRating': value['creditRating'],
        'durationYears': value['durationYears'],
        'yield': value['_yield'],
        'gSpread': value['gSpread'],
        'isToEvent': value['isToEvent'],
        'eventType': value['eventType'],
        'issuerName': value['issuerName'],
    };
}

