/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface MarkedIssuer
 */
export interface MarkedIssuer {
    /**
     * 
     * @type {string}
     * @memberof MarkedIssuer
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof MarkedIssuer
     */
    userId?: string;
    /**
     * 
     * @type {User}
     * @memberof MarkedIssuer
     */
    user?: User;
    /**
     * 
     * @type {string}
     * @memberof MarkedIssuer
     */
    inn?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof MarkedIssuer
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the MarkedIssuer interface.
 */
export function instanceOfMarkedIssuer(value: object): value is MarkedIssuer {
    return true;
}

export function MarkedIssuerFromJSON(json: any): MarkedIssuer {
    return MarkedIssuerFromJSONTyped(json, false);
}

export function MarkedIssuerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarkedIssuer {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'user': json['user'] == null ? undefined : UserFromJSON(json['user']),
        'inn': json['inn'] == null ? undefined : json['inn'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function MarkedIssuerToJSON(value?: MarkedIssuer | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'user': UserToJSON(value['user']),
        'inn': value['inn'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

