/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MarkedIssuerListResponse
 */
export interface MarkedIssuerListResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof MarkedIssuerListResponse
     */
    issuers?: Array<string> | null;
}

/**
 * Check if a given object implements the MarkedIssuerListResponse interface.
 */
export function instanceOfMarkedIssuerListResponse(value: object): value is MarkedIssuerListResponse {
    return true;
}

export function MarkedIssuerListResponseFromJSON(json: any): MarkedIssuerListResponse {
    return MarkedIssuerListResponseFromJSONTyped(json, false);
}

export function MarkedIssuerListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarkedIssuerListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'issuers': json['issuers'] == null ? undefined : json['issuers'],
    };
}

export function MarkedIssuerListResponseToJSON(value?: MarkedIssuerListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'issuers': value['issuers'],
    };
}

