/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarketMapBondDto } from './MarketMapBondDto';
import {
    MarketMapBondDtoFromJSON,
    MarketMapBondDtoFromJSONTyped,
    MarketMapBondDtoToJSON,
} from './MarketMapBondDto';
import type { OfzYieldPointDto } from './OfzYieldPointDto';
import {
    OfzYieldPointDtoFromJSON,
    OfzYieldPointDtoFromJSONTyped,
    OfzYieldPointDtoToJSON,
} from './OfzYieldPointDto';

/**
 * 
 * @export
 * @interface MarketMapResponse
 */
export interface MarketMapResponse {
    /**
     * 
     * @type {Array<OfzYieldPointDto>}
     * @memberof MarketMapResponse
     */
    ofzYieldCurve?: Array<OfzYieldPointDto> | null;
    /**
     * 
     * @type {Array<MarketMapBondDto>}
     * @memberof MarketMapResponse
     */
    bonds?: Array<MarketMapBondDto> | null;
}

/**
 * Check if a given object implements the MarketMapResponse interface.
 */
export function instanceOfMarketMapResponse(value: object): value is MarketMapResponse {
    return true;
}

export function MarketMapResponseFromJSON(json: any): MarketMapResponse {
    return MarketMapResponseFromJSONTyped(json, false);
}

export function MarketMapResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketMapResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ofzYieldCurve': json['ofzYieldCurve'] == null ? undefined : ((json['ofzYieldCurve'] as Array<any>).map(OfzYieldPointDtoFromJSON)),
        'bonds': json['bonds'] == null ? undefined : ((json['bonds'] as Array<any>).map(MarketMapBondDtoFromJSON)),
    };
}

export function MarketMapResponseToJSON(value?: MarketMapResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ofzYieldCurve': value['ofzYieldCurve'] == null ? undefined : ((value['ofzYieldCurve'] as Array<any>).map(OfzYieldPointDtoToJSON)),
        'bonds': value['bonds'] == null ? undefined : ((value['bonds'] as Array<any>).map(MarketMapBondDtoToJSON)),
    };
}

