/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MicrofinanceDomainMetrics
 */
export interface MicrofinanceDomainMetrics {
    /**
     * 
     * @type {number}
     * @memberof MicrofinanceDomainMetrics
     */
    netInterestIncome?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MicrofinanceDomainMetrics
     */
    netInterestIncomePrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MicrofinanceDomainMetrics
     */
    loanPortfolio?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MicrofinanceDomainMetrics
     */
    loanPortfolioPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MicrofinanceDomainMetrics
     */
    returnOnEquity?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MicrofinanceDomainMetrics
     */
    returnOnEquityPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MicrofinanceDomainMetrics
     */
    equityToTotalAssets?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MicrofinanceDomainMetrics
     */
    equityToTotalAssetsPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MicrofinanceDomainMetrics
     */
    costOfRisk?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MicrofinanceDomainMetrics
     */
    costOfRiskPrev?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MicrofinanceDomainMetrics
     */
    nonPerformingLoans90Days?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MicrofinanceDomainMetrics
     */
    nonPerformingLoans90DaysPrev?: number | null;
}

/**
 * Check if a given object implements the MicrofinanceDomainMetrics interface.
 */
export function instanceOfMicrofinanceDomainMetrics(value: object): value is MicrofinanceDomainMetrics {
    return true;
}

export function MicrofinanceDomainMetricsFromJSON(json: any): MicrofinanceDomainMetrics {
    return MicrofinanceDomainMetricsFromJSONTyped(json, false);
}

export function MicrofinanceDomainMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MicrofinanceDomainMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'netInterestIncome': json['netInterestIncome'] == null ? undefined : json['netInterestIncome'],
        'netInterestIncomePrev': json['netInterestIncomePrev'] == null ? undefined : json['netInterestIncomePrev'],
        'loanPortfolio': json['loanPortfolio'] == null ? undefined : json['loanPortfolio'],
        'loanPortfolioPrev': json['loanPortfolioPrev'] == null ? undefined : json['loanPortfolioPrev'],
        'returnOnEquity': json['returnOnEquity'] == null ? undefined : json['returnOnEquity'],
        'returnOnEquityPrev': json['returnOnEquityPrev'] == null ? undefined : json['returnOnEquityPrev'],
        'equityToTotalAssets': json['equityToTotalAssets'] == null ? undefined : json['equityToTotalAssets'],
        'equityToTotalAssetsPrev': json['equityToTotalAssetsPrev'] == null ? undefined : json['equityToTotalAssetsPrev'],
        'costOfRisk': json['costOfRisk'] == null ? undefined : json['costOfRisk'],
        'costOfRiskPrev': json['costOfRiskPrev'] == null ? undefined : json['costOfRiskPrev'],
        'nonPerformingLoans90Days': json['nonPerformingLoans90Days'] == null ? undefined : json['nonPerformingLoans90Days'],
        'nonPerformingLoans90DaysPrev': json['nonPerformingLoans90DaysPrev'] == null ? undefined : json['nonPerformingLoans90DaysPrev'],
    };
}

export function MicrofinanceDomainMetricsToJSON(value?: MicrofinanceDomainMetrics | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'netInterestIncome': value['netInterestIncome'],
        'netInterestIncomePrev': value['netInterestIncomePrev'],
        'loanPortfolio': value['loanPortfolio'],
        'loanPortfolioPrev': value['loanPortfolioPrev'],
        'returnOnEquity': value['returnOnEquity'],
        'returnOnEquityPrev': value['returnOnEquityPrev'],
        'equityToTotalAssets': value['equityToTotalAssets'],
        'equityToTotalAssetsPrev': value['equityToTotalAssetsPrev'],
        'costOfRisk': value['costOfRisk'],
        'costOfRiskPrev': value['costOfRiskPrev'],
        'nonPerformingLoans90Days': value['nonPerformingLoans90Days'],
        'nonPerformingLoans90DaysPrev': value['nonPerformingLoans90DaysPrev'],
    };
}

