/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BrandBasicInfoDto } from './BrandBasicInfoDto';
import {
    BrandBasicInfoDtoFromJSON,
    BrandBasicInfoDtoFromJSONTyped,
    BrandBasicInfoDtoToJSON,
} from './BrandBasicInfoDto';

/**
 * 
 * @export
 * @interface PagedBrandsResponseDto
 */
export interface PagedBrandsResponseDto {
    /**
     * 
     * @type {number}
     * @memberof PagedBrandsResponseDto
     */
    total?: number;
    /**
     * 
     * @type {Array<BrandBasicInfoDto>}
     * @memberof PagedBrandsResponseDto
     */
    data?: Array<BrandBasicInfoDto> | null;
}

/**
 * Check if a given object implements the PagedBrandsResponseDto interface.
 */
export function instanceOfPagedBrandsResponseDto(value: object): value is PagedBrandsResponseDto {
    return true;
}

export function PagedBrandsResponseDtoFromJSON(json: any): PagedBrandsResponseDto {
    return PagedBrandsResponseDtoFromJSONTyped(json, false);
}

export function PagedBrandsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedBrandsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(BrandBasicInfoDtoFromJSON)),
    };
}

export function PagedBrandsResponseDtoToJSON(value?: PagedBrandsResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'total': value['total'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(BrandBasicInfoDtoToJSON)),
    };
}

