/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentMethodResponse
 */
export interface PaymentMethodResponse {
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodResponse
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodResponse
     */
    cardType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodResponse
     */
    last4?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodResponse
     */
    expiryMonth?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodResponse
     */
    expiryYear?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentMethodResponse
     */
    isMain?: boolean;
}

/**
 * Check if a given object implements the PaymentMethodResponse interface.
 */
export function instanceOfPaymentMethodResponse(value: object): value is PaymentMethodResponse {
    return true;
}

export function PaymentMethodResponseFromJSON(json: any): PaymentMethodResponse {
    return PaymentMethodResponseFromJSONTyped(json, false);
}

export function PaymentMethodResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentMethodResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'cardType': json['cardType'] == null ? undefined : json['cardType'],
        'last4': json['last4'] == null ? undefined : json['last4'],
        'expiryMonth': json['expiryMonth'] == null ? undefined : json['expiryMonth'],
        'expiryYear': json['expiryYear'] == null ? undefined : json['expiryYear'],
        'isMain': json['isMain'] == null ? undefined : json['isMain'],
    };
}

export function PaymentMethodResponseToJSON(value?: PaymentMethodResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'title': value['title'],
        'cardType': value['cardType'],
        'last4': value['last4'],
        'expiryMonth': value['expiryMonth'],
        'expiryYear': value['expiryYear'],
        'isMain': value['isMain'],
    };
}

