/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TariffType } from './TariffType';
import {
    TariffTypeFromJSON,
    TariffTypeFromJSONTyped,
    TariffTypeToJSON,
} from './TariffType';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface Payment
 */
export interface Payment {
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    userId?: string;
    /**
     * 
     * @type {User}
     * @memberof Payment
     */
    user?: User;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    externalId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Payment
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    currency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    status?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Payment
     */
    isProcessed?: boolean;
    /**
     * 
     * @type {TariffType}
     * @memberof Payment
     */
    tier?: TariffType;
    /**
     * 
     * @type {boolean}
     * @memberof Payment
     */
    paidWithWoodenBalance?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Payment
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Payment
     */
    updatedAt?: Date | null;
}

/**
 * Check if a given object implements the Payment interface.
 */
export function instanceOfPayment(value: object): value is Payment {
    return true;
}

export function PaymentFromJSON(json: any): Payment {
    return PaymentFromJSONTyped(json, false);
}

export function PaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Payment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'user': json['user'] == null ? undefined : UserFromJSON(json['user']),
        'externalId': json['externalId'] == null ? undefined : json['externalId'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'status': json['status'] == null ? undefined : json['status'],
        'description': json['description'] == null ? undefined : json['description'],
        'isProcessed': json['isProcessed'] == null ? undefined : json['isProcessed'],
        'tier': json['tier'] == null ? undefined : TariffTypeFromJSON(json['tier']),
        'paidWithWoodenBalance': json['paidWithWoodenBalance'] == null ? undefined : json['paidWithWoodenBalance'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function PaymentToJSON(value?: Payment | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'user': UserToJSON(value['user']),
        'externalId': value['externalId'],
        'amount': value['amount'],
        'currency': value['currency'],
        'status': value['status'],
        'description': value['description'],
        'isProcessed': value['isProcessed'],
        'tier': TariffTypeToJSON(value['tier']),
        'paidWithWoodenBalance': value['paidWithWoodenBalance'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt'] as any).toISOString()),
    };
}

