/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RiskLevel } from './RiskLevel';
import {
    RiskLevelFromJSON,
    RiskLevelFromJSONTyped,
    RiskLevelToJSON,
} from './RiskLevel';

/**
 * 
 * @export
 * @interface PortfolioRequest
 */
export interface PortfolioRequest {
    /**
     * 
     * @type {number}
     * @memberof PortfolioRequest
     */
    targetAmount?: number;
    /**
     * 
     * @type {RiskLevel}
     * @memberof PortfolioRequest
     */
    riskLevel?: RiskLevel;
    /**
     * 
     * @type {number}
     * @memberof PortfolioRequest
     */
    diversificationPercent?: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioRequest
     */
    desiredYield?: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioRequest
     */
    targetTermYears?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PortfolioRequest
     */
    excludeSpecialIssuers?: boolean;
}

/**
 * Check if a given object implements the PortfolioRequest interface.
 */
export function instanceOfPortfolioRequest(value: object): value is PortfolioRequest {
    return true;
}

export function PortfolioRequestFromJSON(json: any): PortfolioRequest {
    return PortfolioRequestFromJSONTyped(json, false);
}

export function PortfolioRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'targetAmount': json['targetAmount'] == null ? undefined : json['targetAmount'],
        'riskLevel': json['riskLevel'] == null ? undefined : RiskLevelFromJSON(json['riskLevel']),
        'diversificationPercent': json['diversificationPercent'] == null ? undefined : json['diversificationPercent'],
        'desiredYield': json['desiredYield'] == null ? undefined : json['desiredYield'],
        'targetTermYears': json['targetTermYears'] == null ? undefined : json['targetTermYears'],
        'excludeSpecialIssuers': json['excludeSpecialIssuers'] == null ? undefined : json['excludeSpecialIssuers'],
    };
}

export function PortfolioRequestToJSON(value?: PortfolioRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'targetAmount': value['targetAmount'],
        'riskLevel': RiskLevelToJSON(value['riskLevel']),
        'diversificationPercent': value['diversificationPercent'],
        'desiredYield': value['desiredYield'],
        'targetTermYears': value['targetTermYears'],
        'excludeSpecialIssuers': value['excludeSpecialIssuers'],
    };
}

