/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BondPortionDto } from './BondPortionDto';
import {
    BondPortionDtoFromJSON,
    BondPortionDtoFromJSONTyped,
    BondPortionDtoToJSON,
} from './BondPortionDto';

/**
 * 
 * @export
 * @interface PortfolioResponse
 */
export interface PortfolioResponse {
    /**
     * 
     * @type {number}
     * @memberof PortfolioResponse
     */
    averageYield?: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioResponse
     */
    totalCost?: number;
    /**
     * 
     * @type {Array<BondPortionDto>}
     * @memberof PortfolioResponse
     */
    bonds?: Array<BondPortionDto> | null;
}

/**
 * Check if a given object implements the PortfolioResponse interface.
 */
export function instanceOfPortfolioResponse(value: object): value is PortfolioResponse {
    return true;
}

export function PortfolioResponseFromJSON(json: any): PortfolioResponse {
    return PortfolioResponseFromJSONTyped(json, false);
}

export function PortfolioResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'averageYield': json['averageYield'] == null ? undefined : json['averageYield'],
        'totalCost': json['totalCost'] == null ? undefined : json['totalCost'],
        'bonds': json['bonds'] == null ? undefined : ((json['bonds'] as Array<any>).map(BondPortionDtoFromJSON)),
    };
}

export function PortfolioResponseToJSON(value?: PortfolioResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'averageYield': value['averageYield'],
        'totalCost': value['totalCost'],
        'bonds': value['bonds'] == null ? undefined : ((value['bonds'] as Array<any>).map(BondPortionDtoToJSON)),
    };
}

