/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PortfolioMonthlyIncome
 */
export interface PortfolioMonthlyIncome {
    /**
     * 
     * @type {number}
     * @memberof PortfolioMonthlyIncome
     */
    year?: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioMonthlyIncome
     */
    month?: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioMonthlyIncome
     */
    totalAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioMonthlyIncome
     */
    fixedCouponAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioMonthlyIncome
     */
    floaterCouponAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioMonthlyIncome
     */
    amortizationAmount?: number;
}

/**
 * Check if a given object implements the PortfolioMonthlyIncome interface.
 */
export function instanceOfPortfolioMonthlyIncome(value: object): value is PortfolioMonthlyIncome {
    return true;
}

export function PortfolioMonthlyIncomeFromJSON(json: any): PortfolioMonthlyIncome {
    return PortfolioMonthlyIncomeFromJSONTyped(json, false);
}

export function PortfolioMonthlyIncomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioMonthlyIncome {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'] == null ? undefined : json['year'],
        'month': json['month'] == null ? undefined : json['month'],
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'fixedCouponAmount': json['fixedCouponAmount'] == null ? undefined : json['fixedCouponAmount'],
        'floaterCouponAmount': json['floaterCouponAmount'] == null ? undefined : json['floaterCouponAmount'],
        'amortizationAmount': json['amortizationAmount'] == null ? undefined : json['amortizationAmount'],
    };
}

export function PortfolioMonthlyIncomeToJSON(value?: PortfolioMonthlyIncome | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'year': value['year'],
        'month': value['month'],
        'totalAmount': value['totalAmount'],
        'fixedCouponAmount': value['fixedCouponAmount'],
        'floaterCouponAmount': value['floaterCouponAmount'],
        'amortizationAmount': value['amortizationAmount'],
    };
}

