/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PortfolioIncomeResponse
 */
export interface PortfolioIncomeResponse {
    /**
     * 
     * @type {number}
     * @memberof PortfolioIncomeResponse
     */
    totalCouponIncome?: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioIncomeResponse
     */
    totalDividendIncome?: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioIncomeResponse
     */
    totalRepaymentIncome?: number;
    /**
     * 
     * @type {number}
     * @memberof PortfolioIncomeResponse
     */
    totalIncome?: number;
}

/**
 * Check if a given object implements the PortfolioIncomeResponse interface.
 */
export function instanceOfPortfolioIncomeResponse(value: object): value is PortfolioIncomeResponse {
    return true;
}

export function PortfolioIncomeResponseFromJSON(json: any): PortfolioIncomeResponse {
    return PortfolioIncomeResponseFromJSONTyped(json, false);
}

export function PortfolioIncomeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortfolioIncomeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCouponIncome': json['totalCouponIncome'] == null ? undefined : json['totalCouponIncome'],
        'totalDividendIncome': json['totalDividendIncome'] == null ? undefined : json['totalDividendIncome'],
        'totalRepaymentIncome': json['totalRepaymentIncome'] == null ? undefined : json['totalRepaymentIncome'],
        'totalIncome': json['totalIncome'] == null ? undefined : json['totalIncome'],
    };
}

export function PortfolioIncomeResponseToJSON(value?: PortfolioIncomeResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalCouponIncome': value['totalCouponIncome'],
        'totalDividendIncome': value['totalDividendIncome'],
        'totalRepaymentIncome': value['totalRepaymentIncome'],
        'totalIncome': value['totalIncome'],
    };
}

