/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PresignedUrlResponse
 */
export interface PresignedUrlResponse {
    /**
     * 
     * @type {string}
     * @memberof PresignedUrlResponse
     */
    url?: string | null;
}

/**
 * Check if a given object implements the PresignedUrlResponse interface.
 */
export function instanceOfPresignedUrlResponse(value: object): value is PresignedUrlResponse {
    return true;
}

export function PresignedUrlResponseFromJSON(json: any): PresignedUrlResponse {
    return PresignedUrlResponseFromJSONTyped(json, false);
}

export function PresignedUrlResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PresignedUrlResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function PresignedUrlResponseToJSON(value?: PresignedUrlResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

