/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ProcessingState = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type ProcessingState = typeof ProcessingState[keyof typeof ProcessingState];


export function instanceOfProcessingState(value: any): boolean {
    for (const key in ProcessingState) {
        if (Object.prototype.hasOwnProperty.call(ProcessingState, key)) {
            if ((ProcessingState as Record<string, ProcessingState>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProcessingStateFromJSON(json: any): ProcessingState {
    return ProcessingStateFromJSONTyped(json, false);
}

export function ProcessingStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessingState {
    return json as ProcessingState;
}

export function ProcessingStateToJSON(value?: ProcessingState | null): any {
    return value as any;
}

