/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BrandBusinessResponse } from './BrandBusinessResponse';
import {
    BrandBusinessResponseFromJSON,
    BrandBusinessResponseFromJSONTyped,
    BrandBusinessResponseToJSON,
} from './BrandBusinessResponse';
import type { PublicOfferingRatingDto } from './PublicOfferingRatingDto';
import {
    PublicOfferingRatingDtoFromJSON,
    PublicOfferingRatingDtoFromJSONTyped,
    PublicOfferingRatingDtoToJSON,
} from './PublicOfferingRatingDto';

/**
 * 
 * @export
 * @interface PublicOfferingResponseDto
 */
export interface PublicOfferingResponseDto {
    /**
     * 
     * @type {string}
     * @memberof PublicOfferingResponseDto
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof PublicOfferingResponseDto
     */
    orderDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof PublicOfferingResponseDto
     */
    placementDateLabel?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicOfferingResponseDto
     */
    name?: string | null;
    /**
     * 
     * @type {Array<PublicOfferingRatingDto>}
     * @memberof PublicOfferingResponseDto
     */
    ratings?: Array<PublicOfferingRatingDto> | null;
    /**
     * 
     * @type {string}
     * @memberof PublicOfferingResponseDto
     */
    couponRate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicOfferingResponseDto
     */
    couponPeriod?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicOfferingResponseDto
     */
    duration?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicOfferingResponseDto
     */
    maturityDateLabel?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicOfferingResponseDto
     */
    volume?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicOfferingResponseDto
     */
    comment?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicOfferingResponseDto
     */
    issuerInn?: string | null;
    /**
     * 
     * @type {BrandBusinessResponse}
     * @memberof PublicOfferingResponseDto
     */
    brand?: BrandBusinessResponse;
}

/**
 * Check if a given object implements the PublicOfferingResponseDto interface.
 */
export function instanceOfPublicOfferingResponseDto(value: object): value is PublicOfferingResponseDto {
    return true;
}

export function PublicOfferingResponseDtoFromJSON(json: any): PublicOfferingResponseDto {
    return PublicOfferingResponseDtoFromJSONTyped(json, false);
}

export function PublicOfferingResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicOfferingResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'orderDate': json['orderDate'] == null ? undefined : (new Date(json['orderDate'])),
        'placementDateLabel': json['placementDateLabel'] == null ? undefined : json['placementDateLabel'],
        'name': json['name'] == null ? undefined : json['name'],
        'ratings': json['ratings'] == null ? undefined : ((json['ratings'] as Array<any>).map(PublicOfferingRatingDtoFromJSON)),
        'couponRate': json['couponRate'] == null ? undefined : json['couponRate'],
        'couponPeriod': json['couponPeriod'] == null ? undefined : json['couponPeriod'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'maturityDateLabel': json['maturityDateLabel'] == null ? undefined : json['maturityDateLabel'],
        'volume': json['volume'] == null ? undefined : json['volume'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'issuerInn': json['issuerInn'] == null ? undefined : json['issuerInn'],
        'brand': json['brand'] == null ? undefined : BrandBusinessResponseFromJSON(json['brand']),
    };
}

export function PublicOfferingResponseDtoToJSON(value?: PublicOfferingResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'orderDate': value['orderDate'] == null ? undefined : ((value['orderDate']).toISOString()),
        'placementDateLabel': value['placementDateLabel'],
        'name': value['name'],
        'ratings': value['ratings'] == null ? undefined : ((value['ratings'] as Array<any>).map(PublicOfferingRatingDtoToJSON)),
        'couponRate': value['couponRate'],
        'couponPeriod': value['couponPeriod'],
        'duration': value['duration'],
        'maturityDateLabel': value['maturityDateLabel'],
        'volume': value['volume'],
        'comment': value['comment'],
        'issuerInn': value['issuerInn'],
        'brand': BrandBusinessResponseToJSON(value['brand']),
    };
}

