/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicOfferingRatingDto
 */
export interface PublicOfferingRatingDto {
    /**
     * 
     * @type {string}
     * @memberof PublicOfferingRatingDto
     */
    value?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PublicOfferingRatingDto
     */
    agency?: string | null;
}

/**
 * Check if a given object implements the PublicOfferingRatingDto interface.
 */
export function instanceOfPublicOfferingRatingDto(value: object): value is PublicOfferingRatingDto {
    return true;
}

export function PublicOfferingRatingDtoFromJSON(json: any): PublicOfferingRatingDto {
    return PublicOfferingRatingDtoFromJSONTyped(json, false);
}

export function PublicOfferingRatingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicOfferingRatingDto {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
        'agency': json['agency'] == null ? undefined : json['agency'],
    };
}

export function PublicOfferingRatingDtoToJSON(value?: PublicOfferingRatingDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'value': value['value'],
        'agency': value['agency'],
    };
}

