/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReferralInfoResponse
 */
export interface ReferralInfoResponse {
    /**
     * 
     * @type {string}
     * @memberof ReferralInfoResponse
     */
    referralLink?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReferralInfoResponse
     */
    referralCode?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ReferralInfoResponse
     */
    woodenBalance?: number;
    /**
     * 
     * @type {number}
     * @memberof ReferralInfoResponse
     */
    realBalance?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ReferralInfoResponse
     */
    isActivePartner?: boolean;
}

/**
 * Check if a given object implements the ReferralInfoResponse interface.
 */
export function instanceOfReferralInfoResponse(value: object): value is ReferralInfoResponse {
    return true;
}

export function ReferralInfoResponseFromJSON(json: any): ReferralInfoResponse {
    return ReferralInfoResponseFromJSONTyped(json, false);
}

export function ReferralInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferralInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'referralLink': json['referralLink'] == null ? undefined : json['referralLink'],
        'referralCode': json['referralCode'] == null ? undefined : json['referralCode'],
        'woodenBalance': json['woodenBalance'] == null ? undefined : json['woodenBalance'],
        'realBalance': json['realBalance'] == null ? undefined : json['realBalance'],
        'isActivePartner': json['isActivePartner'] == null ? undefined : json['isActivePartner'],
    };
}

export function ReferralInfoResponseToJSON(value?: ReferralInfoResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'referralLink': value['referralLink'],
        'referralCode': value['referralCode'],
        'woodenBalance': value['woodenBalance'],
        'realBalance': value['realBalance'],
        'isActivePartner': value['isActivePartner'],
    };
}

