/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionType } from './TransactionType';
import {
    TransactionTypeFromJSON,
    TransactionTypeFromJSONTyped,
    TransactionTypeToJSON,
} from './TransactionType';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface ReferralTransaction
 */
export interface ReferralTransaction {
    /**
     * 
     * @type {string}
     * @memberof ReferralTransaction
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ReferralTransaction
     */
    userId?: string;
    /**
     * 
     * @type {User}
     * @memberof ReferralTransaction
     */
    user?: User;
    /**
     * 
     * @type {TransactionType}
     * @memberof ReferralTransaction
     */
    type?: TransactionType;
    /**
     * 
     * @type {number}
     * @memberof ReferralTransaction
     */
    amountWooden?: number;
    /**
     * 
     * @type {number}
     * @memberof ReferralTransaction
     */
    amountReal?: number;
    /**
     * 
     * @type {string}
     * @memberof ReferralTransaction
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReferralTransaction
     */
    sourceUserId?: string | null;
    /**
     * 
     * @type {User}
     * @memberof ReferralTransaction
     */
    sourceUser?: User;
    /**
     * 
     * @type {Date}
     * @memberof ReferralTransaction
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the ReferralTransaction interface.
 */
export function instanceOfReferralTransaction(value: object): value is ReferralTransaction {
    return true;
}

export function ReferralTransactionFromJSON(json: any): ReferralTransaction {
    return ReferralTransactionFromJSONTyped(json, false);
}

export function ReferralTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferralTransaction {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'user': json['user'] == null ? undefined : UserFromJSON(json['user']),
        'type': json['type'] == null ? undefined : TransactionTypeFromJSON(json['type']),
        'amountWooden': json['amountWooden'] == null ? undefined : json['amountWooden'],
        'amountReal': json['amountReal'] == null ? undefined : json['amountReal'],
        'description': json['description'] == null ? undefined : json['description'],
        'sourceUserId': json['sourceUserId'] == null ? undefined : json['sourceUserId'],
        'sourceUser': json['sourceUser'] == null ? undefined : UserFromJSON(json['sourceUser']),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function ReferralTransactionToJSON(value?: ReferralTransaction | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'user': UserToJSON(value['user']),
        'type': TransactionTypeToJSON(value['type']),
        'amountWooden': value['amountWooden'],
        'amountReal': value['amountReal'],
        'description': value['description'],
        'sourceUserId': value['sourceUserId'],
        'sourceUser': UserToJSON(value['sourceUser']),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

