/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ReportStandard = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type ReportStandard = typeof ReportStandard[keyof typeof ReportStandard];


export function instanceOfReportStandard(value: any): boolean {
    for (const key in ReportStandard) {
        if (Object.prototype.hasOwnProperty.call(ReportStandard, key)) {
            if ((ReportStandard as Record<string, ReportStandard>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ReportStandardFromJSON(json: any): ReportStandard {
    return ReportStandardFromJSONTyped(json, false);
}

export function ReportStandardFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportStandard {
    return json as ReportStandard;
}

export function ReportStandardToJSON(value?: ReportStandard | null): any {
    return value as any;
}

