/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ReportCurrency = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type ReportCurrency = typeof ReportCurrency[keyof typeof ReportCurrency];


export function instanceOfReportCurrency(value: any): boolean {
    for (const key in ReportCurrency) {
        if (Object.prototype.hasOwnProperty.call(ReportCurrency, key)) {
            if ((ReportCurrency as Record<string, ReportCurrency>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ReportCurrencyFromJSON(json: any): ReportCurrency {
    return ReportCurrencyFromJSONTyped(json, false);
}

export function ReportCurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportCurrency {
    return json as ReportCurrency;
}

export function ReportCurrencyToJSON(value?: ReportCurrency | null): any {
    return value as any;
}

