/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewJobRequest
 */
export interface ReviewJobRequest {
    /**
     * 
     * @type {boolean}
     * @memberof ReviewJobRequest
     */
    approved?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ReviewJobRequest
     */
    brandId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ReviewJobRequest
     */
    applyToBrand?: boolean;
}

/**
 * Check if a given object implements the ReviewJobRequest interface.
 */
export function instanceOfReviewJobRequest(value: object): value is ReviewJobRequest {
    return true;
}

export function ReviewJobRequestFromJSON(json: any): ReviewJobRequest {
    return ReviewJobRequestFromJSONTyped(json, false);
}

export function ReviewJobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewJobRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'approved': json['approved'] == null ? undefined : json['approved'],
        'brandId': json['brandId'] == null ? undefined : json['brandId'],
        'applyToBrand': json['applyToBrand'] == null ? undefined : json['applyToBrand'],
    };
}

export function ReviewJobRequestToJSON(value?: ReviewJobRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'approved': value['approved'],
        'brandId': value['brandId'],
        'applyToBrand': value['applyToBrand'],
    };
}

