/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RiskLevel = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type RiskLevel = typeof RiskLevel[keyof typeof RiskLevel];


export function instanceOfRiskLevel(value: any): boolean {
    for (const key in RiskLevel) {
        if (Object.prototype.hasOwnProperty.call(RiskLevel, key)) {
            if ((RiskLevel as Record<string, RiskLevel>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RiskLevelFromJSON(json: any): RiskLevel {
    return RiskLevelFromJSONTyped(json, false);
}

export function RiskLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskLevel {
    return json as RiskLevel;
}

export function RiskLevelToJSON(value?: RiskLevel | null): any {
    return value as any;
}

