/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveUserCollectionRequest
 */
export interface SaveUserCollectionRequest {
    /**
     * 
     * @type {string}
     * @memberof SaveUserCollectionRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SaveUserCollectionRequest
     */
    queryUrl: string;
}

/**
 * Check if a given object implements the SaveUserCollectionRequest interface.
 */
export function instanceOfSaveUserCollectionRequest(value: object): value is SaveUserCollectionRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('queryUrl' in value) || value['queryUrl'] === undefined) return false;
    return true;
}

export function SaveUserCollectionRequestFromJSON(json: any): SaveUserCollectionRequest {
    return SaveUserCollectionRequestFromJSONTyped(json, false);
}

export function SaveUserCollectionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveUserCollectionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'queryUrl': json['queryUrl'],
    };
}

export function SaveUserCollectionRequestToJSON(value?: SaveUserCollectionRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'queryUrl': value['queryUrl'],
    };
}

