/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BankingDomainMetrics } from './BankingDomainMetrics';
import {
    BankingDomainMetricsFromJSON,
    BankingDomainMetricsFromJSONTyped,
    BankingDomainMetricsToJSON,
} from './BankingDomainMetrics';
import type { LeasingDomainMetrics } from './LeasingDomainMetrics';
import {
    LeasingDomainMetricsFromJSON,
    LeasingDomainMetricsFromJSONTyped,
    LeasingDomainMetricsToJSON,
} from './LeasingDomainMetrics';
import type { CorporateDomainMetrics } from './CorporateDomainMetrics';
import {
    CorporateDomainMetricsFromJSON,
    CorporateDomainMetricsFromJSONTyped,
    CorporateDomainMetricsToJSON,
} from './CorporateDomainMetrics';
import type { RealEstateDomainMetrics } from './RealEstateDomainMetrics';
import {
    RealEstateDomainMetricsFromJSON,
    RealEstateDomainMetricsFromJSONTyped,
    RealEstateDomainMetricsToJSON,
} from './RealEstateDomainMetrics';
import type { MicrofinanceDomainMetrics } from './MicrofinanceDomainMetrics';
import {
    MicrofinanceDomainMetricsFromJSON,
    MicrofinanceDomainMetricsFromJSONTyped,
    MicrofinanceDomainMetricsToJSON,
} from './MicrofinanceDomainMetrics';

/**
 * 
 * @export
 * @interface SectorMetricsSet
 */
export interface SectorMetricsSet {
    /**
     * 
     * @type {CorporateDomainMetrics}
     * @memberof SectorMetricsSet
     */
    corporate?: CorporateDomainMetrics;
    /**
     * 
     * @type {RealEstateDomainMetrics}
     * @memberof SectorMetricsSet
     */
    realEstate?: RealEstateDomainMetrics;
    /**
     * 
     * @type {BankingDomainMetrics}
     * @memberof SectorMetricsSet
     */
    banking?: BankingDomainMetrics;
    /**
     * 
     * @type {MicrofinanceDomainMetrics}
     * @memberof SectorMetricsSet
     */
    microfinance?: MicrofinanceDomainMetrics;
    /**
     * 
     * @type {LeasingDomainMetrics}
     * @memberof SectorMetricsSet
     */
    leasing?: LeasingDomainMetrics;
}

/**
 * Check if a given object implements the SectorMetricsSet interface.
 */
export function instanceOfSectorMetricsSet(value: object): value is SectorMetricsSet {
    return true;
}

export function SectorMetricsSetFromJSON(json: any): SectorMetricsSet {
    return SectorMetricsSetFromJSONTyped(json, false);
}

export function SectorMetricsSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): SectorMetricsSet {
    if (json == null) {
        return json;
    }
    return {
        
        'corporate': json['corporate'] == null ? undefined : CorporateDomainMetricsFromJSON(json['corporate']),
        'realEstate': json['realEstate'] == null ? undefined : RealEstateDomainMetricsFromJSON(json['realEstate']),
        'banking': json['banking'] == null ? undefined : BankingDomainMetricsFromJSON(json['banking']),
        'microfinance': json['microfinance'] == null ? undefined : MicrofinanceDomainMetricsFromJSON(json['microfinance']),
        'leasing': json['leasing'] == null ? undefined : LeasingDomainMetricsFromJSON(json['leasing']),
    };
}

export function SectorMetricsSetToJSON(value?: SectorMetricsSet | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'corporate': CorporateDomainMetricsToJSON(value['corporate']),
        'realEstate': RealEstateDomainMetricsToJSON(value['realEstate']),
        'banking': BankingDomainMetricsToJSON(value['banking']),
        'microfinance': MicrofinanceDomainMetricsToJSON(value['microfinance']),
        'leasing': LeasingDomainMetricsToJSON(value['leasing']),
    };
}

