/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SectorType = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type SectorType = typeof SectorType[keyof typeof SectorType];


export function instanceOfSectorType(value: any): boolean {
    for (const key in SectorType) {
        if (Object.prototype.hasOwnProperty.call(SectorType, key)) {
            if ((SectorType as Record<string, SectorType>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SectorTypeFromJSON(json: any): SectorType {
    return SectorTypeFromJSONTyped(json, false);
}

export function SectorTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SectorType {
    return json as SectorType;
}

export function SectorTypeToJSON(value?: SectorType | null): any {
    return value as any;
}

