/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimplifiedBrandResponse
 */
export interface SimplifiedBrandResponse {
    /**
     * 
     * @type {string}
     * @memberof SimplifiedBrandResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SimplifiedBrandResponse
     */
    logoName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SimplifiedBrandResponse
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SimplifiedBrandResponse
     */
    bondName?: string | null;
}

/**
 * Check if a given object implements the SimplifiedBrandResponse interface.
 */
export function instanceOfSimplifiedBrandResponse(value: object): value is SimplifiedBrandResponse {
    return true;
}

export function SimplifiedBrandResponseFromJSON(json: any): SimplifiedBrandResponse {
    return SimplifiedBrandResponseFromJSONTyped(json, false);
}

export function SimplifiedBrandResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimplifiedBrandResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'logoName': json['logoName'] == null ? undefined : json['logoName'],
        'name': json['name'] == null ? undefined : json['name'],
        'bondName': json['bondName'] == null ? undefined : json['bondName'],
    };
}

export function SimplifiedBrandResponseToJSON(value?: SimplifiedBrandResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'logoName': value['logoName'],
        'name': value['name'],
        'bondName': value['bondName'],
    };
}

