/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SimplifiedBrandResponse } from './SimplifiedBrandResponse';
import {
    SimplifiedBrandResponseFromJSON,
    SimplifiedBrandResponseFromJSONTyped,
    SimplifiedBrandResponseToJSON,
} from './SimplifiedBrandResponse';

/**
 * 
 * @export
 * @interface SimplifiedBrandsListResponse
 */
export interface SimplifiedBrandsListResponse {
    /**
     * 
     * @type {Array<SimplifiedBrandResponse>}
     * @memberof SimplifiedBrandsListResponse
     */
    brands?: Array<SimplifiedBrandResponse> | null;
}

/**
 * Check if a given object implements the SimplifiedBrandsListResponse interface.
 */
export function instanceOfSimplifiedBrandsListResponse(value: object): value is SimplifiedBrandsListResponse {
    return true;
}

export function SimplifiedBrandsListResponseFromJSON(json: any): SimplifiedBrandsListResponse {
    return SimplifiedBrandsListResponseFromJSONTyped(json, false);
}

export function SimplifiedBrandsListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimplifiedBrandsListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'brands': json['brands'] == null ? undefined : ((json['brands'] as Array<any>).map(SimplifiedBrandResponseFromJSON)),
    };
}

export function SimplifiedBrandsListResponseToJSON(value?: SimplifiedBrandsListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'brands': value['brands'] == null ? undefined : ((value['brands'] as Array<any>).map(SimplifiedBrandResponseToJSON)),
    };
}

