/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SortDirection } from './SortDirection';
import {
    SortDirectionFromJSON,
    SortDirectionFromJSONTyped,
    SortDirectionToJSON,
} from './SortDirection';

/**
 * 
 * @export
 * @interface SortOption
 */
export interface SortOption {
    /**
     * 
     * @type {string}
     * @memberof SortOption
     */
    field?: string | null;
    /**
     * 
     * @type {SortDirection}
     * @memberof SortOption
     */
    direction?: SortDirection;
}

/**
 * Check if a given object implements the SortOption interface.
 */
export function instanceOfSortOption(value: object): value is SortOption {
    return true;
}

export function SortOptionFromJSON(json: any): SortOption {
    return SortOptionFromJSONTyped(json, false);
}

export function SortOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortOption {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'] == null ? undefined : json['field'],
        'direction': json['direction'] == null ? undefined : SortDirectionFromJSON(json['direction']),
    };
}

export function SortOptionToJSON(value?: SortOption | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'field': value['field'],
        'direction': SortDirectionToJSON(value['direction']),
    };
}

