/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SubscriptionTier = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5
} as const;
export type SubscriptionTier = typeof SubscriptionTier[keyof typeof SubscriptionTier];


export function instanceOfSubscriptionTier(value: any): boolean {
    for (const key in SubscriptionTier) {
        if (Object.prototype.hasOwnProperty.call(SubscriptionTier, key)) {
            if ((SubscriptionTier as Record<string, SubscriptionTier>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SubscriptionTierFromJSON(json: any): SubscriptionTier {
    return SubscriptionTierFromJSONTyped(json, false);
}

export function SubscriptionTierFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionTier {
    return json as SubscriptionTier;
}

export function SubscriptionTierToJSON(value?: SubscriptionTier | null): any {
    return value as any;
}

