/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SubSectorType = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type SubSectorType = typeof SubSectorType[keyof typeof SubSectorType];


export function instanceOfSubSectorType(value: any): boolean {
    for (const key in SubSectorType) {
        if (Object.prototype.hasOwnProperty.call(SubSectorType, key)) {
            if ((SubSectorType as Record<string, SubSectorType>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SubSectorTypeFromJSON(json: any): SubSectorType {
    return SubSectorTypeFromJSONTyped(json, false);
}

export function SubSectorTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubSectorType {
    return json as SubSectorType;
}

export function SubSectorTypeToJSON(value?: SubSectorType | null): any {
    return value as any;
}

