/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TinkoffPortfolioPosition
 */
export interface TinkoffPortfolioPosition {
    /**
     * 
     * @type {string}
     * @memberof TinkoffPortfolioPosition
     */
    bondId?: string;
    /**
     * 
     * @type {string}
     * @memberof TinkoffPortfolioPosition
     */
    figi?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TinkoffPortfolioPosition
     */
    isin?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TinkoffPortfolioPosition
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioPosition
     */
    nominal?: number;
    /**
     * 
     * @type {string}
     * @memberof TinkoffPortfolioPosition
     */
    nominalCurrency?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioPosition
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioPosition
     */
    averagePositionPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioPosition
     */
    investedValue?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioPosition
     */
    currentValue?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioPosition
     */
    baseYield?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioPosition
     */
    personalYield?: number;
    /**
     * 
     * @type {string}
     * @memberof TinkoffPortfolioPosition
     */
    couponType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TinkoffPortfolioPosition
     */
    couponRateOrFormula?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TinkoffPortfolioPosition
     */
    nextCouponDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioPosition
     */
    nextCouponValue?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioPosition
     */
    couponQuantityPerYear?: number;
    /**
     * 
     * @type {string}
     * @memberof TinkoffPortfolioPosition
     */
    creditRating?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioPosition
     */
    issuerSharePercent?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TinkoffPortfolioPosition
     */
    defaultFlag?: boolean;
}

/**
 * Check if a given object implements the TinkoffPortfolioPosition interface.
 */
export function instanceOfTinkoffPortfolioPosition(value: object): value is TinkoffPortfolioPosition {
    return true;
}

export function TinkoffPortfolioPositionFromJSON(json: any): TinkoffPortfolioPosition {
    return TinkoffPortfolioPositionFromJSONTyped(json, false);
}

export function TinkoffPortfolioPositionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TinkoffPortfolioPosition {
    if (json == null) {
        return json;
    }
    return {
        
        'bondId': json['bondId'] == null ? undefined : json['bondId'],
        'figi': json['figi'] == null ? undefined : json['figi'],
        'isin': json['isin'] == null ? undefined : json['isin'],
        'name': json['name'] == null ? undefined : json['name'],
        'nominal': json['nominal'] == null ? undefined : json['nominal'],
        'nominalCurrency': json['nominalCurrency'] == null ? undefined : json['nominalCurrency'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'averagePositionPrice': json['averagePositionPrice'] == null ? undefined : json['averagePositionPrice'],
        'investedValue': json['investedValue'] == null ? undefined : json['investedValue'],
        'currentValue': json['currentValue'] == null ? undefined : json['currentValue'],
        'baseYield': json['baseYield'] == null ? undefined : json['baseYield'],
        'personalYield': json['personalYield'] == null ? undefined : json['personalYield'],
        'couponType': json['couponType'] == null ? undefined : json['couponType'],
        'couponRateOrFormula': json['couponRateOrFormula'] == null ? undefined : json['couponRateOrFormula'],
        'nextCouponDate': json['nextCouponDate'] == null ? undefined : (new Date(json['nextCouponDate'])),
        'nextCouponValue': json['nextCouponValue'] == null ? undefined : json['nextCouponValue'],
        'couponQuantityPerYear': json['couponQuantityPerYear'] == null ? undefined : json['couponQuantityPerYear'],
        'creditRating': json['creditRating'] == null ? undefined : json['creditRating'],
        'issuerSharePercent': json['issuerSharePercent'] == null ? undefined : json['issuerSharePercent'],
        'defaultFlag': json['defaultFlag'] == null ? undefined : json['defaultFlag'],
    };
}

export function TinkoffPortfolioPositionToJSON(value?: TinkoffPortfolioPosition | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'bondId': value['bondId'],
        'figi': value['figi'],
        'isin': value['isin'],
        'name': value['name'],
        'nominal': value['nominal'],
        'nominalCurrency': value['nominalCurrency'],
        'quantity': value['quantity'],
        'averagePositionPrice': value['averagePositionPrice'],
        'investedValue': value['investedValue'],
        'currentValue': value['currentValue'],
        'baseYield': value['baseYield'],
        'personalYield': value['personalYield'],
        'couponType': value['couponType'],
        'couponRateOrFormula': value['couponRateOrFormula'],
        'nextCouponDate': value['nextCouponDate'] == null ? undefined : ((value['nextCouponDate'] as any).toISOString()),
        'nextCouponValue': value['nextCouponValue'],
        'couponQuantityPerYear': value['couponQuantityPerYear'],
        'creditRating': value['creditRating'],
        'issuerSharePercent': value['issuerSharePercent'],
        'defaultFlag': value['defaultFlag'],
    };
}

