/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TinkoffPortfolioPosition } from './TinkoffPortfolioPosition';
import {
    TinkoffPortfolioPositionFromJSON,
    TinkoffPortfolioPositionFromJSONTyped,
    TinkoffPortfolioPositionToJSON,
} from './TinkoffPortfolioPosition';
import type { PortfolioMonthlyIncome } from './PortfolioMonthlyIncome';
import {
    PortfolioMonthlyIncomeFromJSON,
    PortfolioMonthlyIncomeFromJSONTyped,
    PortfolioMonthlyIncomeToJSON,
} from './PortfolioMonthlyIncome';
import type { PortfolioBenchmark } from './PortfolioBenchmark';
import {
    PortfolioBenchmarkFromJSON,
    PortfolioBenchmarkFromJSONTyped,
    PortfolioBenchmarkToJSON,
} from './PortfolioBenchmark';

/**
 * 
 * @export
 * @interface TinkoffPortfolioResponse
 */
export interface TinkoffPortfolioResponse {
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    currentTotalValue?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    cleanTotalValue?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    investedTotalValue?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    nominalTotalValue?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    estimatedAnnualIncome?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    estimatedMonthlyIncome?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    estimatedDailyIncome?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    estimatedFixedCouponIncome?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    estimatedFloaterCouponIncome?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    estimatedAmortizationIncome?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    totalExpectedYield?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    weightedAverageYield?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    fixedWeightedAverageYield?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    corporateFixedWeightedAverageYield?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    weightedAverageDuration?: number;
    /**
     * 
     * @type {Date}
     * @memberof TinkoffPortfolioResponse
     */
    nextPayoutDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    nextPayoutAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    lifetimeXirr?: number;
    /**
     * 
     * @type {Date}
     * @memberof TinkoffPortfolioResponse
     */
    portfolioStartDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof TinkoffPortfolioResponse
     */
    xirrDebugMessage?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    totalProfit?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    totalProfitPercent?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    profitFromPriceAppreciation?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    receivedAccruals?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    receivedCouponsLastMonth?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    receivedCouponsLastYear?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    paidCommissions?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    profitFromSales?: number;
    /**
     * 
     * @type {number}
     * @memberof TinkoffPortfolioResponse
     */
    totalAci?: number;
    /**
     * 
     * @type {Array<PortfolioMonthlyIncome>}
     * @memberof TinkoffPortfolioResponse
     */
    monthlyIncome?: Array<PortfolioMonthlyIncome> | null;
    /**
     * 
     * @type {Array<PortfolioBenchmark>}
     * @memberof TinkoffPortfolioResponse
     */
    benchmarks?: Array<PortfolioBenchmark> | null;
    /**
     * 
     * @type {Array<TinkoffPortfolioPosition>}
     * @memberof TinkoffPortfolioResponse
     */
    positions?: Array<TinkoffPortfolioPosition> | null;
}

/**
 * Check if a given object implements the TinkoffPortfolioResponse interface.
 */
export function instanceOfTinkoffPortfolioResponse(value: object): value is TinkoffPortfolioResponse {
    return true;
}

export function TinkoffPortfolioResponseFromJSON(json: any): TinkoffPortfolioResponse {
    return TinkoffPortfolioResponseFromJSONTyped(json, false);
}

export function TinkoffPortfolioResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TinkoffPortfolioResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'currentTotalValue': json['currentTotalValue'] == null ? undefined : json['currentTotalValue'],
        'cleanTotalValue': json['cleanTotalValue'] == null ? undefined : json['cleanTotalValue'],
        'investedTotalValue': json['investedTotalValue'] == null ? undefined : json['investedTotalValue'],
        'nominalTotalValue': json['nominalTotalValue'] == null ? undefined : json['nominalTotalValue'],
        'estimatedAnnualIncome': json['estimatedAnnualIncome'] == null ? undefined : json['estimatedAnnualIncome'],
        'estimatedMonthlyIncome': json['estimatedMonthlyIncome'] == null ? undefined : json['estimatedMonthlyIncome'],
        'estimatedDailyIncome': json['estimatedDailyIncome'] == null ? undefined : json['estimatedDailyIncome'],
        'estimatedFixedCouponIncome': json['estimatedFixedCouponIncome'] == null ? undefined : json['estimatedFixedCouponIncome'],
        'estimatedFloaterCouponIncome': json['estimatedFloaterCouponIncome'] == null ? undefined : json['estimatedFloaterCouponIncome'],
        'estimatedAmortizationIncome': json['estimatedAmortizationIncome'] == null ? undefined : json['estimatedAmortizationIncome'],
        'totalExpectedYield': json['totalExpectedYield'] == null ? undefined : json['totalExpectedYield'],
        'weightedAverageYield': json['weightedAverageYield'] == null ? undefined : json['weightedAverageYield'],
        'fixedWeightedAverageYield': json['fixedWeightedAverageYield'] == null ? undefined : json['fixedWeightedAverageYield'],
        'corporateFixedWeightedAverageYield': json['corporateFixedWeightedAverageYield'] == null ? undefined : json['corporateFixedWeightedAverageYield'],
        'weightedAverageDuration': json['weightedAverageDuration'] == null ? undefined : json['weightedAverageDuration'],
        'nextPayoutDate': json['nextPayoutDate'] == null ? undefined : (new Date(json['nextPayoutDate'])),
        'nextPayoutAmount': json['nextPayoutAmount'] == null ? undefined : json['nextPayoutAmount'],
        'lifetimeXirr': json['lifetimeXirr'] == null ? undefined : json['lifetimeXirr'],
        'portfolioStartDate': json['portfolioStartDate'] == null ? undefined : (new Date(json['portfolioStartDate'])),
        'xirrDebugMessage': json['xirrDebugMessage'] == null ? undefined : json['xirrDebugMessage'],
        'totalProfit': json['totalProfit'] == null ? undefined : json['totalProfit'],
        'totalProfitPercent': json['totalProfitPercent'] == null ? undefined : json['totalProfitPercent'],
        'profitFromPriceAppreciation': json['profitFromPriceAppreciation'] == null ? undefined : json['profitFromPriceAppreciation'],
        'receivedAccruals': json['receivedAccruals'] == null ? undefined : json['receivedAccruals'],
        'receivedCouponsLastMonth': json['receivedCouponsLastMonth'] == null ? undefined : json['receivedCouponsLastMonth'],
        'receivedCouponsLastYear': json['receivedCouponsLastYear'] == null ? undefined : json['receivedCouponsLastYear'],
        'paidCommissions': json['paidCommissions'] == null ? undefined : json['paidCommissions'],
        'profitFromSales': json['profitFromSales'] == null ? undefined : json['profitFromSales'],
        'totalAci': json['totalAci'] == null ? undefined : json['totalAci'],
        'monthlyIncome': json['monthlyIncome'] == null ? undefined : ((json['monthlyIncome'] as Array<any>).map(PortfolioMonthlyIncomeFromJSON)),
        'benchmarks': json['benchmarks'] == null ? undefined : ((json['benchmarks'] as Array<any>).map(PortfolioBenchmarkFromJSON)),
        'positions': json['positions'] == null ? undefined : ((json['positions'] as Array<any>).map(TinkoffPortfolioPositionFromJSON)),
    };
}

export function TinkoffPortfolioResponseToJSON(value?: TinkoffPortfolioResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'currentTotalValue': value['currentTotalValue'],
        'cleanTotalValue': value['cleanTotalValue'],
        'investedTotalValue': value['investedTotalValue'],
        'nominalTotalValue': value['nominalTotalValue'],
        'estimatedAnnualIncome': value['estimatedAnnualIncome'],
        'estimatedMonthlyIncome': value['estimatedMonthlyIncome'],
        'estimatedDailyIncome': value['estimatedDailyIncome'],
        'estimatedFixedCouponIncome': value['estimatedFixedCouponIncome'],
        'estimatedFloaterCouponIncome': value['estimatedFloaterCouponIncome'],
        'estimatedAmortizationIncome': value['estimatedAmortizationIncome'],
        'totalExpectedYield': value['totalExpectedYield'],
        'weightedAverageYield': value['weightedAverageYield'],
        'fixedWeightedAverageYield': value['fixedWeightedAverageYield'],
        'corporateFixedWeightedAverageYield': value['corporateFixedWeightedAverageYield'],
        'weightedAverageDuration': value['weightedAverageDuration'],
        'nextPayoutDate': value['nextPayoutDate'] == null ? undefined : ((value['nextPayoutDate'] as any).toISOString()),
        'nextPayoutAmount': value['nextPayoutAmount'],
        'lifetimeXirr': value['lifetimeXirr'],
        'portfolioStartDate': value['portfolioStartDate'] == null ? undefined : ((value['portfolioStartDate'] as any).toISOString()),
        'xirrDebugMessage': value['xirrDebugMessage'],
        'totalProfit': value['totalProfit'],
        'totalProfitPercent': value['totalProfitPercent'],
        'profitFromPriceAppreciation': value['profitFromPriceAppreciation'],
        'receivedAccruals': value['receivedAccruals'],
        'receivedCouponsLastMonth': value['receivedCouponsLastMonth'],
        'receivedCouponsLastYear': value['receivedCouponsLastYear'],
        'paidCommissions': value['paidCommissions'],
        'profitFromSales': value['profitFromSales'],
        'totalAci': value['totalAci'],
        'monthlyIncome': value['monthlyIncome'] == null ? undefined : ((value['monthlyIncome'] as Array<any>).map(PortfolioMonthlyIncomeToJSON)),
        'benchmarks': value['benchmarks'] == null ? undefined : ((value['benchmarks'] as Array<any>).map(PortfolioBenchmarkToJSON)),
        'positions': value['positions'] == null ? undefined : ((value['positions'] as Array<any>).map(TinkoffPortfolioPositionToJSON)),
    };
}

