/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToggleMarkedIssuerRequest
 */
export interface ToggleMarkedIssuerRequest {
    /**
     * 
     * @type {string}
     * @memberof ToggleMarkedIssuerRequest
     */
    inn: string;
}

/**
 * Check if a given object implements the ToggleMarkedIssuerRequest interface.
 */
export function instanceOfToggleMarkedIssuerRequest(value: object): value is ToggleMarkedIssuerRequest {
    if (!('inn' in value) || value['inn'] === undefined) return false;
    return true;
}

export function ToggleMarkedIssuerRequestFromJSON(json: any): ToggleMarkedIssuerRequest {
    return ToggleMarkedIssuerRequestFromJSONTyped(json, false);
}

export function ToggleMarkedIssuerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToggleMarkedIssuerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'inn': json['inn'],
    };
}

export function ToggleMarkedIssuerRequestToJSON(value?: ToggleMarkedIssuerRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'inn': value['inn'],
    };
}

