/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrialActivationRequest
 */
export interface TrialActivationRequest {
    /**
     * 
     * @type {string}
     * @memberof TrialActivationRequest
     */
    fingerprint?: string | null;
}

/**
 * Check if a given object implements the TrialActivationRequest interface.
 */
export function instanceOfTrialActivationRequest(value: object): value is TrialActivationRequest {
    return true;
}

export function TrialActivationRequestFromJSON(json: any): TrialActivationRequest {
    return TrialActivationRequestFromJSONTyped(json, false);
}

export function TrialActivationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrialActivationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'fingerprint': json['fingerprint'] == null ? undefined : json['fingerprint'],
    };
}

export function TrialActivationRequestToJSON(value?: TrialActivationRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'fingerprint': value['fingerprint'],
    };
}

