/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TriggerReportDownloadRequest
 */
export interface TriggerReportDownloadRequest {
    /**
     * 
     * @type {string}
     * @memberof TriggerReportDownloadRequest
     */
    brandId?: string;
    /**
     * 
     * @type {string}
     * @memberof TriggerReportDownloadRequest
     */
    reportUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TriggerReportDownloadRequest
     */
    reportType?: string | null;
}

/**
 * Check if a given object implements the TriggerReportDownloadRequest interface.
 */
export function instanceOfTriggerReportDownloadRequest(value: object): value is TriggerReportDownloadRequest {
    return true;
}

export function TriggerReportDownloadRequestFromJSON(json: any): TriggerReportDownloadRequest {
    return TriggerReportDownloadRequestFromJSONTyped(json, false);
}

export function TriggerReportDownloadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriggerReportDownloadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'brandId': json['brandId'] == null ? undefined : json['brandId'],
        'reportUrl': json['reportUrl'] == null ? undefined : json['reportUrl'],
        'reportType': json['reportType'] == null ? undefined : json['reportType'],
    };
}

export function TriggerReportDownloadRequestToJSON(value?: TriggerReportDownloadRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'brandId': value['brandId'],
        'reportUrl': value['reportUrl'],
        'reportType': value['reportType'],
    };
}

