/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateReportStatusRequest
 */
export interface UpdateReportStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateReportStatusRequest
     */
    reportType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateReportStatusRequest
     */
    docType?: string | null;
}

/**
 * Check if a given object implements the UpdateReportStatusRequest interface.
 */
export function instanceOfUpdateReportStatusRequest(value: object): value is UpdateReportStatusRequest {
    return true;
}

export function UpdateReportStatusRequestFromJSON(json: any): UpdateReportStatusRequest {
    return UpdateReportStatusRequestFromJSONTyped(json, false);
}

export function UpdateReportStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateReportStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reportType': json['reportType'] == null ? undefined : json['reportType'],
        'docType': json['docType'] == null ? undefined : json['docType'],
    };
}

export function UpdateReportStatusRequestToJSON(value?: UpdateReportStatusRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'reportType': value['reportType'],
        'docType': value['docType'],
    };
}

