/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCustomFiltersRequest
 */
export interface UpdateCustomFiltersRequest {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateCustomFiltersRequest
     */
    customFiltersOn?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof UpdateCustomFiltersRequest
     */
    customFilters?: Array<number> | null;
}

/**
 * Check if a given object implements the UpdateCustomFiltersRequest interface.
 */
export function instanceOfUpdateCustomFiltersRequest(value: object): value is UpdateCustomFiltersRequest {
    return true;
}

export function UpdateCustomFiltersRequestFromJSON(json: any): UpdateCustomFiltersRequest {
    return UpdateCustomFiltersRequestFromJSONTyped(json, false);
}

export function UpdateCustomFiltersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCustomFiltersRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'customFiltersOn': json['customFiltersOn'] == null ? undefined : json['customFiltersOn'],
        'customFilters': json['customFilters'] == null ? undefined : json['customFilters'],
    };
}

export function UpdateCustomFiltersRequestToJSON(value?: UpdateCustomFiltersRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'customFiltersOn': value['customFiltersOn'],
        'customFilters': value['customFilters'],
    };
}

