/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCreditRatingRequest
 */
export interface UpdateCreditRatingRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateCreditRatingRequest
     */
    rating?: string | null;
}

/**
 * Check if a given object implements the UpdateCreditRatingRequest interface.
 */
export function instanceOfUpdateCreditRatingRequest(value: object): value is UpdateCreditRatingRequest {
    return true;
}

export function UpdateCreditRatingRequestFromJSON(json: any): UpdateCreditRatingRequest {
    return UpdateCreditRatingRequestFromJSONTyped(json, false);
}

export function UpdateCreditRatingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCreditRatingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'rating': json['rating'] == null ? undefined : json['rating'],
    };
}

export function UpdateCreditRatingRequestToJSON(value?: UpdateCreditRatingRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'rating': value['rating'],
    };
}

