/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserCollectionRequest
 */
export interface UpdateUserCollectionRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserCollectionRequest
     */
    queryUrl: string;
}

/**
 * Check if a given object implements the UpdateUserCollectionRequest interface.
 */
export function instanceOfUpdateUserCollectionRequest(value: object): value is UpdateUserCollectionRequest {
    if (!('queryUrl' in value) || value['queryUrl'] === undefined) return false;
    return true;
}

export function UpdateUserCollectionRequestFromJSON(json: any): UpdateUserCollectionRequest {
    return UpdateUserCollectionRequestFromJSONTyped(json, false);
}

export function UpdateUserCollectionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserCollectionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'queryUrl': json['queryUrl'],
    };
}

export function UpdateUserCollectionRequestToJSON(value?: UpdateUserCollectionRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'queryUrl': value['queryUrl'],
    };
}

