/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserCollectionResponse
 */
export interface UserCollectionResponse {
    /**
     * 
     * @type {string}
     * @memberof UserCollectionResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserCollectionResponse
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserCollectionResponse
     */
    queryUrl?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserCollectionResponse
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the UserCollectionResponse interface.
 */
export function instanceOfUserCollectionResponse(value: object): value is UserCollectionResponse {
    return true;
}

export function UserCollectionResponseFromJSON(json: any): UserCollectionResponse {
    return UserCollectionResponseFromJSONTyped(json, false);
}

export function UserCollectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCollectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'queryUrl': json['queryUrl'] == null ? undefined : json['queryUrl'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function UserCollectionResponseToJSON(value?: UserCollectionResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'queryUrl': value['queryUrl'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

