/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface UserCollection
 */
export interface UserCollection {
    /**
     * 
     * @type {string}
     * @memberof UserCollection
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserCollection
     */
    userId?: string;
    /**
     * 
     * @type {User}
     * @memberof UserCollection
     */
    user?: User;
    /**
     * 
     * @type {string}
     * @memberof UserCollection
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserCollection
     */
    queryUrl?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserCollection
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the UserCollection interface.
 */
export function instanceOfUserCollection(value: object): value is UserCollection {
    return true;
}

export function UserCollectionFromJSON(json: any): UserCollection {
    return UserCollectionFromJSONTyped(json, false);
}

export function UserCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'user': json['user'] == null ? undefined : UserFromJSON(json['user']),
        'name': json['name'] == null ? undefined : json['name'],
        'queryUrl': json['queryUrl'] == null ? undefined : json['queryUrl'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function UserCollectionToJSON(value?: UserCollection | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'user': UserToJSON(value['user']),
        'name': value['name'],
        'queryUrl': value['queryUrl'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

