/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserPortfolio } from './UserPortfolio';
import {
    UserPortfolioFromJSON,
    UserPortfolioFromJSONTyped,
    UserPortfolioToJSON,
} from './UserPortfolio';
import type { MarkedIssuer } from './MarkedIssuer';
import {
    MarkedIssuerFromJSON,
    MarkedIssuerFromJSONTyped,
    MarkedIssuerToJSON,
} from './MarkedIssuer';
import type { Payment } from './Payment';
import {
    PaymentFromJSON,
    PaymentFromJSONTyped,
    PaymentToJSON,
} from './Payment';
import type { WithdrawalRequest } from './WithdrawalRequest';
import {
    WithdrawalRequestFromJSON,
    WithdrawalRequestFromJSONTyped,
    WithdrawalRequestToJSON,
} from './WithdrawalRequest';
import type { ReferralTransaction } from './ReferralTransaction';
import {
    ReferralTransactionFromJSON,
    ReferralTransactionFromJSONTyped,
    ReferralTransactionToJSON,
} from './ReferralTransaction';
import type { FavoriteBond } from './FavoriteBond';
import {
    FavoriteBondFromJSON,
    FavoriteBondFromJSONTyped,
    FavoriteBondToJSON,
} from './FavoriteBond';
import type { PaymentMethod } from './PaymentMethod';
import {
    PaymentMethodFromJSON,
    PaymentMethodFromJSONTyped,
    PaymentMethodToJSON,
} from './PaymentMethod';
import type { UserCollection } from './UserCollection';
import {
    UserCollectionFromJSON,
    UserCollectionFromJSONTyped,
    UserCollectionToJSON,
} from './UserCollection';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    provider?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    providerId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    passwordHash?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    emailConfirmed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    role?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    usedAutoSub?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    trialUsed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isTrialNow?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    nextPaymentDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    paymentSum?: number;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isForeverSubscriber?: boolean;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    mainPaymentMethodId?: string | null;
    /**
     * 
     * @type {PaymentMethod}
     * @memberof User
     */
    mainPaymentMethod?: PaymentMethod;
    /**
     * 
     * @type {Array<PaymentMethod>}
     * @memberof User
     */
    paymentMethods?: Array<PaymentMethod> | null;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    freeFilteredRequestsBalance?: number;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    freeAlternativeSearchesBalance?: number;
    /**
     * 
     * @type {Array<FavoriteBond>}
     * @memberof User
     */
    favorites?: Array<FavoriteBond> | null;
    /**
     * 
     * @type {Array<Payment>}
     * @memberof User
     */
    payments?: Array<Payment> | null;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    referralCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    referredById?: string | null;
    /**
     * 
     * @type {User}
     * @memberof User
     */
    referredBy?: User;
    /**
     * 
     * @type {Array<User>}
     * @memberof User
     */
    referrals?: Array<User> | null;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    woodenBalance?: number;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    realBalance?: number;
    /**
     * 
     * @type {Array<ReferralTransaction>}
     * @memberof User
     */
    referralTransactions?: Array<ReferralTransaction> | null;
    /**
     * 
     * @type {Array<WithdrawalRequest>}
     * @memberof User
     */
    withdrawalRequests?: Array<WithdrawalRequest> | null;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    customFiltersOn?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof User
     */
    customFilters?: Array<number> | null;
    /**
     * 
     * @type {Array<MarkedIssuer>}
     * @memberof User
     */
    markedIssuers?: Array<MarkedIssuer> | null;
    /**
     * 
     * @type {Array<UserCollection>}
     * @memberof User
     */
    collections?: Array<UserCollection> | null;
    /**
     * 
     * @type {UserPortfolio}
     * @memberof User
     */
    portfolio?: UserPortfolio;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    encryptedTinkoffApiKey?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isTinkoffKeyValid?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    readonly hasActiveSubscription?: boolean;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'providerId': json['providerId'] == null ? undefined : json['providerId'],
        'email': json['email'] == null ? undefined : json['email'],
        'passwordHash': json['passwordHash'] == null ? undefined : json['passwordHash'],
        'emailConfirmed': json['emailConfirmed'] == null ? undefined : json['emailConfirmed'],
        'role': json['role'] == null ? undefined : json['role'],
        'usedAutoSub': json['usedAutoSub'] == null ? undefined : json['usedAutoSub'],
        'trialUsed': json['trialUsed'] == null ? undefined : json['trialUsed'],
        'isTrialNow': json['isTrialNow'] == null ? undefined : json['isTrialNow'],
        'nextPaymentDate': json['nextPaymentDate'] == null ? undefined : (new Date(json['nextPaymentDate'])),
        'paymentSum': json['paymentSum'] == null ? undefined : json['paymentSum'],
        'isForeverSubscriber': json['isForeverSubscriber'] == null ? undefined : json['isForeverSubscriber'],
        'mainPaymentMethodId': json['mainPaymentMethodId'] == null ? undefined : json['mainPaymentMethodId'],
        'mainPaymentMethod': json['mainPaymentMethod'] == null ? undefined : PaymentMethodFromJSON(json['mainPaymentMethod']),
        'paymentMethods': json['paymentMethods'] == null ? undefined : ((json['paymentMethods'] as Array<any>).map(PaymentMethodFromJSON)),
        'freeFilteredRequestsBalance': json['freeFilteredRequestsBalance'] == null ? undefined : json['freeFilteredRequestsBalance'],
        'freeAlternativeSearchesBalance': json['freeAlternativeSearchesBalance'] == null ? undefined : json['freeAlternativeSearchesBalance'],
        'favorites': json['favorites'] == null ? undefined : ((json['favorites'] as Array<any>).map(FavoriteBondFromJSON)),
        'payments': json['payments'] == null ? undefined : ((json['payments'] as Array<any>).map(PaymentFromJSON)),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'referralCode': json['referralCode'] == null ? undefined : json['referralCode'],
        'referredById': json['referredById'] == null ? undefined : json['referredById'],
        'referredBy': json['referredBy'] == null ? undefined : UserFromJSON(json['referredBy']),
        'referrals': json['referrals'] == null ? undefined : ((json['referrals'] as Array<any>).map(UserFromJSON)),
        'woodenBalance': json['woodenBalance'] == null ? undefined : json['woodenBalance'],
        'realBalance': json['realBalance'] == null ? undefined : json['realBalance'],
        'referralTransactions': json['referralTransactions'] == null ? undefined : ((json['referralTransactions'] as Array<any>).map(ReferralTransactionFromJSON)),
        'withdrawalRequests': json['withdrawalRequests'] == null ? undefined : ((json['withdrawalRequests'] as Array<any>).map(WithdrawalRequestFromJSON)),
        'customFiltersOn': json['customFiltersOn'] == null ? undefined : json['customFiltersOn'],
        'customFilters': json['customFilters'] == null ? undefined : json['customFilters'],
        'markedIssuers': json['markedIssuers'] == null ? undefined : ((json['markedIssuers'] as Array<any>).map(MarkedIssuerFromJSON)),
        'collections': json['collections'] == null ? undefined : ((json['collections'] as Array<any>).map(UserCollectionFromJSON)),
        'portfolio': json['portfolio'] == null ? undefined : UserPortfolioFromJSON(json['portfolio']),
        'encryptedTinkoffApiKey': json['encryptedTinkoffApiKey'] == null ? undefined : json['encryptedTinkoffApiKey'],
        'isTinkoffKeyValid': json['isTinkoffKeyValid'] == null ? undefined : json['isTinkoffKeyValid'],
        'hasActiveSubscription': json['hasActiveSubscription'] == null ? undefined : json['hasActiveSubscription'],
    };
}

export function UserToJSON(value?: Omit<User, 'hasActiveSubscription'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'provider': value['provider'],
        'providerId': value['providerId'],
        'email': value['email'],
        'passwordHash': value['passwordHash'],
        'emailConfirmed': value['emailConfirmed'],
        'role': value['role'],
        'usedAutoSub': value['usedAutoSub'],
        'trialUsed': value['trialUsed'],
        'isTrialNow': value['isTrialNow'],
        'nextPaymentDate': value['nextPaymentDate'] == null ? undefined : ((value['nextPaymentDate'] as any).toISOString()),
        'paymentSum': value['paymentSum'],
        'isForeverSubscriber': value['isForeverSubscriber'],
        'mainPaymentMethodId': value['mainPaymentMethodId'],
        'mainPaymentMethod': PaymentMethodToJSON(value['mainPaymentMethod']),
        'paymentMethods': value['paymentMethods'] == null ? undefined : ((value['paymentMethods'] as Array<any>).map(PaymentMethodToJSON)),
        'freeFilteredRequestsBalance': value['freeFilteredRequestsBalance'],
        'freeAlternativeSearchesBalance': value['freeAlternativeSearchesBalance'],
        'favorites': value['favorites'] == null ? undefined : ((value['favorites'] as Array<any>).map(FavoriteBondToJSON)),
        'payments': value['payments'] == null ? undefined : ((value['payments'] as Array<any>).map(PaymentToJSON)),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'referralCode': value['referralCode'],
        'referredById': value['referredById'],
        'referredBy': UserToJSON(value['referredBy']),
        'referrals': value['referrals'] == null ? undefined : ((value['referrals'] as Array<any>).map(UserToJSON)),
        'woodenBalance': value['woodenBalance'],
        'realBalance': value['realBalance'],
        'referralTransactions': value['referralTransactions'] == null ? undefined : ((value['referralTransactions'] as Array<any>).map(ReferralTransactionToJSON)),
        'withdrawalRequests': value['withdrawalRequests'] == null ? undefined : ((value['withdrawalRequests'] as Array<any>).map(WithdrawalRequestToJSON)),
        'customFiltersOn': value['customFiltersOn'],
        'customFilters': value['customFilters'],
        'markedIssuers': value['markedIssuers'] == null ? undefined : ((value['markedIssuers'] as Array<any>).map(MarkedIssuerToJSON)),
        'collections': value['collections'] == null ? undefined : ((value['collections'] as Array<any>).map(UserCollectionToJSON)),
        'portfolio': UserPortfolioToJSON(value['portfolio']),
        'encryptedTinkoffApiKey': value['encryptedTinkoffApiKey'],
        'isTinkoffKeyValid': value['isTinkoffKeyValid'],
    };
}

