/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserCollectionResponse } from './UserCollectionResponse';
import {
    UserCollectionResponseFromJSON,
    UserCollectionResponseFromJSONTyped,
    UserCollectionResponseToJSON,
} from './UserCollectionResponse';

/**
 * 
 * @export
 * @interface UserCollectionListResponse
 */
export interface UserCollectionListResponse {
    /**
     * 
     * @type {Array<UserCollectionResponse>}
     * @memberof UserCollectionListResponse
     */
    collections?: Array<UserCollectionResponse> | null;
}

/**
 * Check if a given object implements the UserCollectionListResponse interface.
 */
export function instanceOfUserCollectionListResponse(value: object): value is UserCollectionListResponse {
    return true;
}

export function UserCollectionListResponseFromJSON(json: any): UserCollectionListResponse {
    return UserCollectionListResponseFromJSONTyped(json, false);
}

export function UserCollectionListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCollectionListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'collections': json['collections'] == null ? undefined : ((json['collections'] as Array<any>).map(UserCollectionResponseFromJSON)),
    };
}

export function UserCollectionListResponseToJSON(value?: UserCollectionListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'collections': value['collections'] == null ? undefined : ((value['collections'] as Array<any>).map(UserCollectionResponseToJSON)),
    };
}

