/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSimpleIfoResponse
 */
export interface UserSimpleIfoResponse {
    /**
     * 
     * @type {string}
     * @memberof UserSimpleIfoResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserSimpleIfoResponse
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserSimpleIfoResponse
     */
    role?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserSimpleIfoResponse
     */
    subscribed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserSimpleIfoResponse
     */
    authenticated?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserSimpleIfoResponse
     */
    trialUsed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserSimpleIfoResponse
     */
    usedAutoSub?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof UserSimpleIfoResponse
     */
    nextPaymentDate?: Date | null;
}

/**
 * Check if a given object implements the UserSimpleIfoResponse interface.
 */
export function instanceOfUserSimpleIfoResponse(value: object): value is UserSimpleIfoResponse {
    return true;
}

export function UserSimpleIfoResponseFromJSON(json: any): UserSimpleIfoResponse {
    return UserSimpleIfoResponseFromJSONTyped(json, false);
}

export function UserSimpleIfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSimpleIfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'] == null ? undefined : json['email'],
        'role': json['role'] == null ? undefined : json['role'],
        'subscribed': json['subscribed'] == null ? undefined : json['subscribed'],
        'authenticated': json['authenticated'] == null ? undefined : json['authenticated'],
        'trialUsed': json['trialUsed'] == null ? undefined : json['trialUsed'],
        'usedAutoSub': json['usedAutoSub'] == null ? undefined : json['usedAutoSub'],
        'nextPaymentDate': json['nextPaymentDate'] == null ? undefined : (new Date(json['nextPaymentDate'])),
    };
}

export function UserSimpleIfoResponseToJSON(value?: UserSimpleIfoResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'email': value['email'],
        'role': value['role'],
        'subscribed': value['subscribed'],
        'authenticated': value['authenticated'],
        'trialUsed': value['trialUsed'],
        'usedAutoSub': value['usedAutoSub'],
        'nextPaymentDate': value['nextPaymentDate'] == null ? undefined : ((value['nextPaymentDate'] as any).toISOString()),
    };
}

