/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WithdrawRequest
 */
export interface WithdrawRequest {
    /**
     * 
     * @type {number}
     * @memberof WithdrawRequest
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof WithdrawRequest
     */
    requisites?: string | null;
}

/**
 * Check if a given object implements the WithdrawRequest interface.
 */
export function instanceOfWithdrawRequest(value: object): value is WithdrawRequest {
    return true;
}

export function WithdrawRequestFromJSON(json: any): WithdrawRequest {
    return WithdrawRequestFromJSONTyped(json, false);
}

export function WithdrawRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WithdrawRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'requisites': json['requisites'] == null ? undefined : json['requisites'],
    };
}

export function WithdrawRequestToJSON(value?: WithdrawRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amount': value['amount'],
        'requisites': value['requisites'],
    };
}

