/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface WithdrawalRequest
 */
export interface WithdrawalRequest {
    /**
     * 
     * @type {string}
     * @memberof WithdrawalRequest
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof WithdrawalRequest
     */
    userId?: string;
    /**
     * 
     * @type {User}
     * @memberof WithdrawalRequest
     */
    user?: User;
    /**
     * 
     * @type {number}
     * @memberof WithdrawalRequest
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof WithdrawalRequest
     */
    requisites?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WithdrawalRequest
     */
    status?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof WithdrawalRequest
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof WithdrawalRequest
     */
    processedAt?: Date | null;
}

/**
 * Check if a given object implements the WithdrawalRequest interface.
 */
export function instanceOfWithdrawalRequest(value: object): value is WithdrawalRequest {
    return true;
}

export function WithdrawalRequestFromJSON(json: any): WithdrawalRequest {
    return WithdrawalRequestFromJSONTyped(json, false);
}

export function WithdrawalRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WithdrawalRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'user': json['user'] == null ? undefined : UserFromJSON(json['user']),
        'amount': json['amount'] == null ? undefined : json['amount'],
        'requisites': json['requisites'] == null ? undefined : json['requisites'],
        'status': json['status'] == null ? undefined : json['status'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'processedAt': json['processedAt'] == null ? undefined : (new Date(json['processedAt'])),
    };
}

export function WithdrawalRequestToJSON(value?: WithdrawalRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'user': UserToJSON(value['user']),
        'amount': value['amount'],
        'requisites': value['requisites'],
        'status': value['status'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'processedAt': value['processedAt'] == null ? undefined : ((value['processedAt'] as any).toISOString()),
    };
}

