/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { YookassaPaymentObject } from './YookassaPaymentObject';
import {
    YookassaPaymentObjectFromJSON,
    YookassaPaymentObjectFromJSONTyped,
    YookassaPaymentObjectToJSON,
} from './YookassaPaymentObject';

/**
 * 
 * @export
 * @interface YookassaWebhookDto
 */
export interface YookassaWebhookDto {
    /**
     * 
     * @type {string}
     * @memberof YookassaWebhookDto
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof YookassaWebhookDto
     */
    event?: string | null;
    /**
     * 
     * @type {YookassaPaymentObject}
     * @memberof YookassaWebhookDto
     */
    object?: YookassaPaymentObject;
}

/**
 * Check if a given object implements the YookassaWebhookDto interface.
 */
export function instanceOfYookassaWebhookDto(value: object): value is YookassaWebhookDto {
    return true;
}

export function YookassaWebhookDtoFromJSON(json: any): YookassaWebhookDto {
    return YookassaWebhookDtoFromJSONTyped(json, false);
}

export function YookassaWebhookDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): YookassaWebhookDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'event': json['event'] == null ? undefined : json['event'],
        'object': json['object'] == null ? undefined : YookassaPaymentObjectFromJSON(json['object']),
    };
}

export function YookassaWebhookDtoToJSON(value?: YookassaWebhookDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'event': value['event'],
        'object': YookassaPaymentObjectToJSON(value['object']),
    };
}

