/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface YookassaPaymentMethod
 */
export interface YookassaPaymentMethod {
    /**
     * 
     * @type {string}
     * @memberof YookassaPaymentMethod
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof YookassaPaymentMethod
     */
    id?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof YookassaPaymentMethod
     */
    saved?: boolean;
}

/**
 * Check if a given object implements the YookassaPaymentMethod interface.
 */
export function instanceOfYookassaPaymentMethod(value: object): value is YookassaPaymentMethod {
    return true;
}

export function YookassaPaymentMethodFromJSON(json: any): YookassaPaymentMethod {
    return YookassaPaymentMethodFromJSONTyped(json, false);
}

export function YookassaPaymentMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): YookassaPaymentMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'] == null ? undefined : json['id'],
        'saved': json['saved'] == null ? undefined : json['saved'],
    };
}

export function YookassaPaymentMethodToJSON(value?: YookassaPaymentMethod | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'id': value['id'],
        'saved': value['saved'],
    };
}

