/* tslint:disable */
/* eslint-disable */
/**
 * BondsApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { YookassaAmount } from './YookassaAmount';
import {
    YookassaAmountFromJSON,
    YookassaAmountFromJSONTyped,
    YookassaAmountToJSON,
} from './YookassaAmount';
import type { YookassaPaymentMethod } from './YookassaPaymentMethod';
import {
    YookassaPaymentMethodFromJSON,
    YookassaPaymentMethodFromJSONTyped,
    YookassaPaymentMethodToJSON,
} from './YookassaPaymentMethod';

/**
 * 
 * @export
 * @interface YookassaPaymentObject
 */
export interface YookassaPaymentObject {
    /**
     * 
     * @type {string}
     * @memberof YookassaPaymentObject
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof YookassaPaymentObject
     */
    status?: string | null;
    /**
     * 
     * @type {YookassaAmount}
     * @memberof YookassaPaymentObject
     */
    amount?: YookassaAmount;
    /**
     * 
     * @type {string}
     * @memberof YookassaPaymentObject
     */
    description?: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof YookassaPaymentObject
     */
    metadata?: { [key: string]: string; } | null;
    /**
     * 
     * @type {YookassaPaymentMethod}
     * @memberof YookassaPaymentObject
     */
    paymentMethod?: YookassaPaymentMethod;
}

/**
 * Check if a given object implements the YookassaPaymentObject interface.
 */
export function instanceOfYookassaPaymentObject(value: object): value is YookassaPaymentObject {
    return true;
}

export function YookassaPaymentObjectFromJSON(json: any): YookassaPaymentObject {
    return YookassaPaymentObjectFromJSONTyped(json, false);
}

export function YookassaPaymentObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): YookassaPaymentObject {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'] == null ? undefined : json['status'],
        'amount': json['amount'] == null ? undefined : YookassaAmountFromJSON(json['amount']),
        'description': json['description'] == null ? undefined : json['description'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'paymentMethod': json['payment_method'] == null ? undefined : YookassaPaymentMethodFromJSON(json['payment_method']),
    };
}

export function YookassaPaymentObjectToJSON(value?: YookassaPaymentObject | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'status': value['status'],
        'amount': YookassaAmountToJSON(value['amount']),
        'description': value['description'],
        'metadata': value['metadata'],
        'payment_method': YookassaPaymentMethodToJSON(value['paymentMethod']),
    };
}

